/**
 * @fileoverview gRPC-Web generated client stub for billing
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.27.0-rc2
// source: biller_service.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as biller_service_pb from './biller_service_pb'; // proto import: "biller_service.proto"


export class BillingChargeServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorInfo = new grpcWeb.MethodDescriptor(
    '/billing.BillingChargeService/Info',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.Empty,
    biller_service_pb.ServiceInfo,
    (request: biller_service_pb.Empty) => {
      return request.serializeBinary();
    },
    biller_service_pb.ServiceInfo.deserializeBinary
  );

  info(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.ServiceInfo>;

  info(
    request: biller_service_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.ServiceInfo) => void): grpcWeb.ClientReadableStream<biller_service_pb.ServiceInfo>;

  info(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.ServiceInfo) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingChargeService/Info',
        request,
        metadata || {},
        this.methodDescriptorInfo,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingChargeService/Info',
    request,
    metadata || {},
    this.methodDescriptorInfo);
  }

  methodDescriptorCharge = new grpcWeb.MethodDescriptor(
    '/billing.BillingChargeService/Charge',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.ChargeRequest,
    biller_service_pb.BillResponce,
    (request: biller_service_pb.ChargeRequest) => {
      return request.serializeBinary();
    },
    biller_service_pb.BillResponce.deserializeBinary
  );

  charge(
    request: biller_service_pb.ChargeRequest,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.BillResponce>;

  charge(
    request: biller_service_pb.ChargeRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.BillResponce) => void): grpcWeb.ClientReadableStream<biller_service_pb.BillResponce>;

  charge(
    request: biller_service_pb.ChargeRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.BillResponce) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingChargeService/Charge',
        request,
        metadata || {},
        this.methodDescriptorCharge,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingChargeService/Charge',
    request,
    metadata || {},
    this.methodDescriptorCharge);
  }

  methodDescriptorSetup = new grpcWeb.MethodDescriptor(
    '/billing.BillingChargeService/Setup',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.SetupData,
    biller_service_pb.Empty,
    (request: biller_service_pb.SetupData) => {
      return request.serializeBinary();
    },
    biller_service_pb.Empty.deserializeBinary
  );

  setup(
    request: biller_service_pb.SetupData,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.Empty>;

  setup(
    request: biller_service_pb.SetupData,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.Empty) => void): grpcWeb.ClientReadableStream<biller_service_pb.Empty>;

  setup(
    request: biller_service_pb.SetupData,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingChargeService/Setup',
        request,
        metadata || {},
        this.methodDescriptorSetup,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingChargeService/Setup',
    request,
    metadata || {},
    this.methodDescriptorSetup);
  }

}

export class BillingTariffProviderClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorInfo = new grpcWeb.MethodDescriptor(
    '/billing.BillingTariffProvider/Info',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.Empty,
    biller_service_pb.ServiceInfo,
    (request: biller_service_pb.Empty) => {
      return request.serializeBinary();
    },
    biller_service_pb.ServiceInfo.deserializeBinary
  );

  info(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.ServiceInfo>;

  info(
    request: biller_service_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.ServiceInfo) => void): grpcWeb.ClientReadableStream<biller_service_pb.ServiceInfo>;

  info(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.ServiceInfo) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingTariffProvider/Info',
        request,
        metadata || {},
        this.methodDescriptorInfo,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingTariffProvider/Info',
    request,
    metadata || {},
    this.methodDescriptorInfo);
  }

  methodDescriptorGetSetupData = new grpcWeb.MethodDescriptor(
    '/billing.BillingTariffProvider/GetSetupData',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.Empty,
    biller_service_pb.SetupData,
    (request: biller_service_pb.Empty) => {
      return request.serializeBinary();
    },
    biller_service_pb.SetupData.deserializeBinary
  );

  getSetupData(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.SetupData>;

  getSetupData(
    request: biller_service_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.SetupData) => void): grpcWeb.ClientReadableStream<biller_service_pb.SetupData>;

  getSetupData(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.SetupData) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingTariffProvider/GetSetupData',
        request,
        metadata || {},
        this.methodDescriptorGetSetupData,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingTariffProvider/GetSetupData',
    request,
    metadata || {},
    this.methodDescriptorGetSetupData);
  }

  methodDescriptorGetServiceTypes = new grpcWeb.MethodDescriptor(
    '/billing.BillingTariffProvider/GetServiceTypes',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.Empty,
    biller_service_pb.GET_SERVICETYPES,
    (request: biller_service_pb.Empty) => {
      return request.serializeBinary();
    },
    biller_service_pb.GET_SERVICETYPES.deserializeBinary
  );

  getServiceTypes(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.GET_SERVICETYPES>;

  getServiceTypes(
    request: biller_service_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.GET_SERVICETYPES) => void): grpcWeb.ClientReadableStream<biller_service_pb.GET_SERVICETYPES>;

  getServiceTypes(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.GET_SERVICETYPES) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingTariffProvider/GetServiceTypes',
        request,
        metadata || {},
        this.methodDescriptorGetServiceTypes,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingTariffProvider/GetServiceTypes',
    request,
    metadata || {},
    this.methodDescriptorGetServiceTypes);
  }

  methodDescriptorGetChargeTypes = new grpcWeb.MethodDescriptor(
    '/billing.BillingTariffProvider/GetChargeTypes',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.Empty,
    biller_service_pb.GET_CHARGETYPES,
    (request: biller_service_pb.Empty) => {
      return request.serializeBinary();
    },
    biller_service_pb.GET_CHARGETYPES.deserializeBinary
  );

  getChargeTypes(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.GET_CHARGETYPES>;

  getChargeTypes(
    request: biller_service_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.GET_CHARGETYPES) => void): grpcWeb.ClientReadableStream<biller_service_pb.GET_CHARGETYPES>;

  getChargeTypes(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.GET_CHARGETYPES) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingTariffProvider/GetChargeTypes',
        request,
        metadata || {},
        this.methodDescriptorGetChargeTypes,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingTariffProvider/GetChargeTypes',
    request,
    metadata || {},
    this.methodDescriptorGetChargeTypes);
  }

  methodDescriptorGetEntityTypes = new grpcWeb.MethodDescriptor(
    '/billing.BillingTariffProvider/GetEntityTypes',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.Empty,
    biller_service_pb.GET_ENTITYTYPES,
    (request: biller_service_pb.Empty) => {
      return request.serializeBinary();
    },
    biller_service_pb.GET_ENTITYTYPES.deserializeBinary
  );

  getEntityTypes(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.GET_ENTITYTYPES>;

  getEntityTypes(
    request: biller_service_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.GET_ENTITYTYPES) => void): grpcWeb.ClientReadableStream<biller_service_pb.GET_ENTITYTYPES>;

  getEntityTypes(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.GET_ENTITYTYPES) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingTariffProvider/GetEntityTypes',
        request,
        metadata || {},
        this.methodDescriptorGetEntityTypes,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingTariffProvider/GetEntityTypes',
    request,
    metadata || {},
    this.methodDescriptorGetEntityTypes);
  }

  methodDescriptorGetChargeRegularCalcStrategy = new grpcWeb.MethodDescriptor(
    '/billing.BillingTariffProvider/GetChargeRegularCalcStrategy',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.Empty,
    biller_service_pb.GET_CHARGEREGULARCALCSTRATEGY,
    (request: biller_service_pb.Empty) => {
      return request.serializeBinary();
    },
    biller_service_pb.GET_CHARGEREGULARCALCSTRATEGY.deserializeBinary
  );

  getChargeRegularCalcStrategy(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.GET_CHARGEREGULARCALCSTRATEGY>;

  getChargeRegularCalcStrategy(
    request: biller_service_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.GET_CHARGEREGULARCALCSTRATEGY) => void): grpcWeb.ClientReadableStream<biller_service_pb.GET_CHARGEREGULARCALCSTRATEGY>;

  getChargeRegularCalcStrategy(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.GET_CHARGEREGULARCALCSTRATEGY) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingTariffProvider/GetChargeRegularCalcStrategy',
        request,
        metadata || {},
        this.methodDescriptorGetChargeRegularCalcStrategy,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingTariffProvider/GetChargeRegularCalcStrategy',
    request,
    metadata || {},
    this.methodDescriptorGetChargeRegularCalcStrategy);
  }

  methodDescriptorGetTransCodes = new grpcWeb.MethodDescriptor(
    '/billing.BillingTariffProvider/GetTransCodes',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.Empty,
    biller_service_pb.TransCodesRes,
    (request: biller_service_pb.Empty) => {
      return request.serializeBinary();
    },
    biller_service_pb.TransCodesRes.deserializeBinary
  );

  getTransCodes(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.TransCodesRes>;

  getTransCodes(
    request: biller_service_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.TransCodesRes) => void): grpcWeb.ClientReadableStream<biller_service_pb.TransCodesRes>;

  getTransCodes(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.TransCodesRes) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingTariffProvider/GetTransCodes',
        request,
        metadata || {},
        this.methodDescriptorGetTransCodes,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingTariffProvider/GetTransCodes',
    request,
    metadata || {},
    this.methodDescriptorGetTransCodes);
  }

  methodDescriptorGetAllCTGConsumptionServiceTariffs = new grpcWeb.MethodDescriptor(
    '/billing.BillingTariffProvider/GetAllCTGConsumptionServiceTariffs',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.Empty,
    biller_service_pb.ArrCTGConsumptionServiceTariff,
    (request: biller_service_pb.Empty) => {
      return request.serializeBinary();
    },
    biller_service_pb.ArrCTGConsumptionServiceTariff.deserializeBinary
  );

  getAllCTGConsumptionServiceTariffs(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.ArrCTGConsumptionServiceTariff>;

  getAllCTGConsumptionServiceTariffs(
    request: biller_service_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.ArrCTGConsumptionServiceTariff) => void): grpcWeb.ClientReadableStream<biller_service_pb.ArrCTGConsumptionServiceTariff>;

  getAllCTGConsumptionServiceTariffs(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.ArrCTGConsumptionServiceTariff) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingTariffProvider/GetAllCTGConsumptionServiceTariffs',
        request,
        metadata || {},
        this.methodDescriptorGetAllCTGConsumptionServiceTariffs,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingTariffProvider/GetAllCTGConsumptionServiceTariffs',
    request,
    metadata || {},
    this.methodDescriptorGetAllCTGConsumptionServiceTariffs);
  }

  methodDescriptorSaveCTGConsumptionServiceTariff = new grpcWeb.MethodDescriptor(
    '/billing.BillingTariffProvider/SaveCTGConsumptionServiceTariff',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.CTGConsumptionServiceTariff,
    biller_service_pb.Empty,
    (request: biller_service_pb.CTGConsumptionServiceTariff) => {
      return request.serializeBinary();
    },
    biller_service_pb.Empty.deserializeBinary
  );

  saveCTGConsumptionServiceTariff(
    request: biller_service_pb.CTGConsumptionServiceTariff,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.Empty>;

  saveCTGConsumptionServiceTariff(
    request: biller_service_pb.CTGConsumptionServiceTariff,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.Empty) => void): grpcWeb.ClientReadableStream<biller_service_pb.Empty>;

  saveCTGConsumptionServiceTariff(
    request: biller_service_pb.CTGConsumptionServiceTariff,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingTariffProvider/SaveCTGConsumptionServiceTariff',
        request,
        metadata || {},
        this.methodDescriptorSaveCTGConsumptionServiceTariff,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingTariffProvider/SaveCTGConsumptionServiceTariff',
    request,
    metadata || {},
    this.methodDescriptorSaveCTGConsumptionServiceTariff);
  }

  methodDescriptorGetAllTariffs = new grpcWeb.MethodDescriptor(
    '/billing.BillingTariffProvider/GetAllTariffs',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.Empty,
    biller_service_pb.ArrTariffs,
    (request: biller_service_pb.Empty) => {
      return request.serializeBinary();
    },
    biller_service_pb.ArrTariffs.deserializeBinary
  );

  getAllTariffs(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.ArrTariffs>;

  getAllTariffs(
    request: biller_service_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.ArrTariffs) => void): grpcWeb.ClientReadableStream<biller_service_pb.ArrTariffs>;

  getAllTariffs(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.ArrTariffs) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingTariffProvider/GetAllTariffs',
        request,
        metadata || {},
        this.methodDescriptorGetAllTariffs,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingTariffProvider/GetAllTariffs',
    request,
    metadata || {},
    this.methodDescriptorGetAllTariffs);
  }

  methodDescriptorSaveTariffs = new grpcWeb.MethodDescriptor(
    '/billing.BillingTariffProvider/SaveTariffs',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.Tariffs,
    biller_service_pb.Tariffs,
    (request: biller_service_pb.Tariffs) => {
      return request.serializeBinary();
    },
    biller_service_pb.Tariffs.deserializeBinary
  );

  saveTariffs(
    request: biller_service_pb.Tariffs,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.Tariffs>;

  saveTariffs(
    request: biller_service_pb.Tariffs,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.Tariffs) => void): grpcWeb.ClientReadableStream<biller_service_pb.Tariffs>;

  saveTariffs(
    request: biller_service_pb.Tariffs,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.Tariffs) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingTariffProvider/SaveTariffs',
        request,
        metadata || {},
        this.methodDescriptorSaveTariffs,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingTariffProvider/SaveTariffs',
    request,
    metadata || {},
    this.methodDescriptorSaveTariffs);
  }

  methodDescriptorSaveTariffsData = new grpcWeb.MethodDescriptor(
    '/billing.BillingTariffProvider/SaveTariffsData',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.TariffsData,
    biller_service_pb.Empty,
    (request: biller_service_pb.TariffsData) => {
      return request.serializeBinary();
    },
    biller_service_pb.Empty.deserializeBinary
  );

  saveTariffsData(
    request: biller_service_pb.TariffsData,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.Empty>;

  saveTariffsData(
    request: biller_service_pb.TariffsData,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.Empty) => void): grpcWeb.ClientReadableStream<biller_service_pb.Empty>;

  saveTariffsData(
    request: biller_service_pb.TariffsData,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingTariffProvider/SaveTariffsData',
        request,
        metadata || {},
        this.methodDescriptorSaveTariffsData,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingTariffProvider/SaveTariffsData',
    request,
    metadata || {},
    this.methodDescriptorSaveTariffsData);
  }

  methodDescriptorGetTariffCodeHistory = new grpcWeb.MethodDescriptor(
    '/billing.BillingTariffProvider/GetTariffCodeHistory',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.TariffCodeReq,
    biller_service_pb.TariffsDataRes,
    (request: biller_service_pb.TariffCodeReq) => {
      return request.serializeBinary();
    },
    biller_service_pb.TariffsDataRes.deserializeBinary
  );

  getTariffCodeHistory(
    request: biller_service_pb.TariffCodeReq,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.TariffsDataRes>;

  getTariffCodeHistory(
    request: biller_service_pb.TariffCodeReq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.TariffsDataRes) => void): grpcWeb.ClientReadableStream<biller_service_pb.TariffsDataRes>;

  getTariffCodeHistory(
    request: biller_service_pb.TariffCodeReq,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.TariffsDataRes) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingTariffProvider/GetTariffCodeHistory',
        request,
        metadata || {},
        this.methodDescriptorGetTariffCodeHistory,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingTariffProvider/GetTariffCodeHistory',
    request,
    metadata || {},
    this.methodDescriptorGetTariffCodeHistory);
  }

  methodDescriptorGetAllTariffBands = new grpcWeb.MethodDescriptor(
    '/billing.BillingTariffProvider/GetAllTariffBands',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.TariffIdReq,
    biller_service_pb.ArrTariffBands,
    (request: biller_service_pb.TariffIdReq) => {
      return request.serializeBinary();
    },
    biller_service_pb.ArrTariffBands.deserializeBinary
  );

  getAllTariffBands(
    request: biller_service_pb.TariffIdReq,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.ArrTariffBands>;

  getAllTariffBands(
    request: biller_service_pb.TariffIdReq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.ArrTariffBands) => void): grpcWeb.ClientReadableStream<biller_service_pb.ArrTariffBands>;

  getAllTariffBands(
    request: biller_service_pb.TariffIdReq,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.ArrTariffBands) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingTariffProvider/GetAllTariffBands',
        request,
        metadata || {},
        this.methodDescriptorGetAllTariffBands,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingTariffProvider/GetAllTariffBands',
    request,
    metadata || {},
    this.methodDescriptorGetAllTariffBands);
  }

  methodDescriptorSaveTariffBands = new grpcWeb.MethodDescriptor(
    '/billing.BillingTariffProvider/SaveTariffBands',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.TariffBands,
    biller_service_pb.Empty,
    (request: biller_service_pb.TariffBands) => {
      return request.serializeBinary();
    },
    biller_service_pb.Empty.deserializeBinary
  );

  saveTariffBands(
    request: biller_service_pb.TariffBands,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.Empty>;

  saveTariffBands(
    request: biller_service_pb.TariffBands,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.Empty) => void): grpcWeb.ClientReadableStream<biller_service_pb.Empty>;

  saveTariffBands(
    request: biller_service_pb.TariffBands,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingTariffProvider/SaveTariffBands',
        request,
        metadata || {},
        this.methodDescriptorSaveTariffBands,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingTariffProvider/SaveTariffBands',
    request,
    metadata || {},
    this.methodDescriptorSaveTariffBands);
  }

  methodDescriptorGetAllTariffExtraFees = new grpcWeb.MethodDescriptor(
    '/billing.BillingTariffProvider/GetAllTariffExtraFees',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.TariffIdReq,
    biller_service_pb.ArrTariffExtraFees,
    (request: biller_service_pb.TariffIdReq) => {
      return request.serializeBinary();
    },
    biller_service_pb.ArrTariffExtraFees.deserializeBinary
  );

  getAllTariffExtraFees(
    request: biller_service_pb.TariffIdReq,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.ArrTariffExtraFees>;

  getAllTariffExtraFees(
    request: biller_service_pb.TariffIdReq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.ArrTariffExtraFees) => void): grpcWeb.ClientReadableStream<biller_service_pb.ArrTariffExtraFees>;

  getAllTariffExtraFees(
    request: biller_service_pb.TariffIdReq,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.ArrTariffExtraFees) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingTariffProvider/GetAllTariffExtraFees',
        request,
        metadata || {},
        this.methodDescriptorGetAllTariffExtraFees,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingTariffProvider/GetAllTariffExtraFees',
    request,
    metadata || {},
    this.methodDescriptorGetAllTariffExtraFees);
  }

  methodDescriptorSaveTariffExtraFees = new grpcWeb.MethodDescriptor(
    '/billing.BillingTariffProvider/SaveTariffExtraFees',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.TariffExtraFees,
    biller_service_pb.Empty,
    (request: biller_service_pb.TariffExtraFees) => {
      return request.serializeBinary();
    },
    biller_service_pb.Empty.deserializeBinary
  );

  saveTariffExtraFees(
    request: biller_service_pb.TariffExtraFees,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.Empty>;

  saveTariffExtraFees(
    request: biller_service_pb.TariffExtraFees,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.Empty) => void): grpcWeb.ClientReadableStream<biller_service_pb.Empty>;

  saveTariffExtraFees(
    request: biller_service_pb.TariffExtraFees,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingTariffProvider/SaveTariffExtraFees',
        request,
        metadata || {},
        this.methodDescriptorSaveTariffExtraFees,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingTariffProvider/SaveTariffExtraFees',
    request,
    metadata || {},
    this.methodDescriptorSaveTariffExtraFees);
  }

  methodDescriptorGetAllRegularCharges = new grpcWeb.MethodDescriptor(
    '/billing.BillingTariffProvider/GetAllRegularCharges',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.Empty,
    biller_service_pb.RegularChargeRequest,
    (request: biller_service_pb.Empty) => {
      return request.serializeBinary();
    },
    biller_service_pb.RegularChargeRequest.deserializeBinary
  );

  getAllRegularCharges(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.RegularChargeRequest>;

  getAllRegularCharges(
    request: biller_service_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.RegularChargeRequest) => void): grpcWeb.ClientReadableStream<biller_service_pb.RegularChargeRequest>;

  getAllRegularCharges(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.RegularChargeRequest) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingTariffProvider/GetAllRegularCharges',
        request,
        metadata || {},
        this.methodDescriptorGetAllRegularCharges,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingTariffProvider/GetAllRegularCharges',
    request,
    metadata || {},
    this.methodDescriptorGetAllRegularCharges);
  }

  methodDescriptorGetRegularChargeInfo = new grpcWeb.MethodDescriptor(
    '/billing.BillingTariffProvider/GetRegularChargeInfo',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.RegularChargeIdReq,
    biller_service_pb.RegularChargeInfo,
    (request: biller_service_pb.RegularChargeIdReq) => {
      return request.serializeBinary();
    },
    biller_service_pb.RegularChargeInfo.deserializeBinary
  );

  getRegularChargeInfo(
    request: biller_service_pb.RegularChargeIdReq,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.RegularChargeInfo>;

  getRegularChargeInfo(
    request: biller_service_pb.RegularChargeIdReq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.RegularChargeInfo) => void): grpcWeb.ClientReadableStream<biller_service_pb.RegularChargeInfo>;

  getRegularChargeInfo(
    request: biller_service_pb.RegularChargeIdReq,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.RegularChargeInfo) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingTariffProvider/GetRegularChargeInfo',
        request,
        metadata || {},
        this.methodDescriptorGetRegularChargeInfo,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingTariffProvider/GetRegularChargeInfo',
    request,
    metadata || {},
    this.methodDescriptorGetRegularChargeInfo);
  }

  methodDescriptorSaveRegularCharges = new grpcWeb.MethodDescriptor(
    '/billing.BillingTariffProvider/SaveRegularCharges',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.RegularCharge,
    biller_service_pb.Empty,
    (request: biller_service_pb.RegularCharge) => {
      return request.serializeBinary();
    },
    biller_service_pb.Empty.deserializeBinary
  );

  saveRegularCharges(
    request: biller_service_pb.RegularCharge,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.Empty>;

  saveRegularCharges(
    request: biller_service_pb.RegularCharge,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.Empty) => void): grpcWeb.ClientReadableStream<biller_service_pb.Empty>;

  saveRegularCharges(
    request: biller_service_pb.RegularCharge,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingTariffProvider/SaveRegularCharges',
        request,
        metadata || {},
        this.methodDescriptorSaveRegularCharges,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingTariffProvider/SaveRegularCharges',
    request,
    metadata || {},
    this.methodDescriptorSaveRegularCharges);
  }

  methodDescriptorGetAllRegularRelationEntity = new grpcWeb.MethodDescriptor(
    '/billing.BillingTariffProvider/GetAllRegularRelationEntity',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.RegularChargeReq,
    biller_service_pb.ArrRegularRelationEntity,
    (request: biller_service_pb.RegularChargeReq) => {
      return request.serializeBinary();
    },
    biller_service_pb.ArrRegularRelationEntity.deserializeBinary
  );

  getAllRegularRelationEntity(
    request: biller_service_pb.RegularChargeReq,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.ArrRegularRelationEntity>;

  getAllRegularRelationEntity(
    request: biller_service_pb.RegularChargeReq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.ArrRegularRelationEntity) => void): grpcWeb.ClientReadableStream<biller_service_pb.ArrRegularRelationEntity>;

  getAllRegularRelationEntity(
    request: biller_service_pb.RegularChargeReq,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.ArrRegularRelationEntity) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingTariffProvider/GetAllRegularRelationEntity',
        request,
        metadata || {},
        this.methodDescriptorGetAllRegularRelationEntity,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingTariffProvider/GetAllRegularRelationEntity',
    request,
    metadata || {},
    this.methodDescriptorGetAllRegularRelationEntity);
  }

  methodDescriptorSaveRegularRelationEntity = new grpcWeb.MethodDescriptor(
    '/billing.BillingTariffProvider/SaveRegularRelationEntity',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.RegularRelationEntity,
    biller_service_pb.Empty,
    (request: biller_service_pb.RegularRelationEntity) => {
      return request.serializeBinary();
    },
    biller_service_pb.Empty.deserializeBinary
  );

  saveRegularRelationEntity(
    request: biller_service_pb.RegularRelationEntity,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.Empty>;

  saveRegularRelationEntity(
    request: biller_service_pb.RegularRelationEntity,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.Empty) => void): grpcWeb.ClientReadableStream<biller_service_pb.Empty>;

  saveRegularRelationEntity(
    request: biller_service_pb.RegularRelationEntity,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingTariffProvider/SaveRegularRelationEntity',
        request,
        metadata || {},
        this.methodDescriptorSaveRegularRelationEntity,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingTariffProvider/SaveRegularRelationEntity',
    request,
    metadata || {},
    this.methodDescriptorSaveRegularRelationEntity);
  }

  methodDescriptorGetAllRegularRelationValues = new grpcWeb.MethodDescriptor(
    '/billing.BillingTariffProvider/GetAllRegularRelationValues',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.RegularChargeReq,
    biller_service_pb.ArrRegularRelationValues,
    (request: biller_service_pb.RegularChargeReq) => {
      return request.serializeBinary();
    },
    biller_service_pb.ArrRegularRelationValues.deserializeBinary
  );

  getAllRegularRelationValues(
    request: biller_service_pb.RegularChargeReq,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.ArrRegularRelationValues>;

  getAllRegularRelationValues(
    request: biller_service_pb.RegularChargeReq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.ArrRegularRelationValues) => void): grpcWeb.ClientReadableStream<biller_service_pb.ArrRegularRelationValues>;

  getAllRegularRelationValues(
    request: biller_service_pb.RegularChargeReq,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.ArrRegularRelationValues) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingTariffProvider/GetAllRegularRelationValues',
        request,
        metadata || {},
        this.methodDescriptorGetAllRegularRelationValues,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingTariffProvider/GetAllRegularRelationValues',
    request,
    metadata || {},
    this.methodDescriptorGetAllRegularRelationValues);
  }

  methodDescriptorSaveRegularRelationValues = new grpcWeb.MethodDescriptor(
    '/billing.BillingTariffProvider/SaveRegularRelationValues',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.RegularRelationValues,
    biller_service_pb.Empty,
    (request: biller_service_pb.RegularRelationValues) => {
      return request.serializeBinary();
    },
    biller_service_pb.Empty.deserializeBinary
  );

  saveRegularRelationValues(
    request: biller_service_pb.RegularRelationValues,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.Empty>;

  saveRegularRelationValues(
    request: biller_service_pb.RegularRelationValues,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.Empty) => void): grpcWeb.ClientReadableStream<biller_service_pb.Empty>;

  saveRegularRelationValues(
    request: biller_service_pb.RegularRelationValues,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingTariffProvider/SaveRegularRelationValues',
        request,
        metadata || {},
        this.methodDescriptorSaveRegularRelationValues,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingTariffProvider/SaveRegularRelationValues',
    request,
    metadata || {},
    this.methodDescriptorSaveRegularRelationValues);
  }

}

export class BillingDataProviderClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorInfo = new grpcWeb.MethodDescriptor(
    '/billing.BillingDataProvider/Info',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.Empty,
    biller_service_pb.ServiceInfo,
    (request: biller_service_pb.Empty) => {
      return request.serializeBinary();
    },
    biller_service_pb.ServiceInfo.deserializeBinary
  );

  info(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.ServiceInfo>;

  info(
    request: biller_service_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.ServiceInfo) => void): grpcWeb.ClientReadableStream<biller_service_pb.ServiceInfo>;

  info(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.ServiceInfo) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingDataProvider/Info',
        request,
        metadata || {},
        this.methodDescriptorInfo,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingDataProvider/Info',
    request,
    metadata || {},
    this.methodDescriptorInfo);
  }

  methodDescriptorGetCustomerByCustkey = new grpcWeb.MethodDescriptor(
    '/billing.BillingDataProvider/GetCustomerByCustkey',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.Key,
    biller_service_pb.Customer,
    (request: biller_service_pb.Key) => {
      return request.serializeBinary();
    },
    biller_service_pb.Customer.deserializeBinary
  );

  getCustomerByCustkey(
    request: biller_service_pb.Key,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.Customer>;

  getCustomerByCustkey(
    request: biller_service_pb.Key,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.Customer) => void): grpcWeb.ClientReadableStream<biller_service_pb.Customer>;

  getCustomerByCustkey(
    request: biller_service_pb.Key,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.Customer) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingDataProvider/GetCustomerByCustkey',
        request,
        metadata || {},
        this.methodDescriptorGetCustomerByCustkey,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingDataProvider/GetCustomerByCustkey',
    request,
    metadata || {},
    this.methodDescriptorGetCustomerByCustkey);
  }

  methodDescriptorGetCustomersByBillgroup = new grpcWeb.MethodDescriptor(
    '/billing.BillingDataProvider/GetCustomersByBillgroup',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.Key,
    biller_service_pb.CustomersList,
    (request: biller_service_pb.Key) => {
      return request.serializeBinary();
    },
    biller_service_pb.CustomersList.deserializeBinary
  );

  getCustomersByBillgroup(
    request: biller_service_pb.Key,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.CustomersList>;

  getCustomersByBillgroup(
    request: biller_service_pb.Key,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.CustomersList) => void): grpcWeb.ClientReadableStream<biller_service_pb.CustomersList>;

  getCustomersByBillgroup(
    request: biller_service_pb.Key,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.CustomersList) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingDataProvider/GetCustomersByBillgroup',
        request,
        metadata || {},
        this.methodDescriptorGetCustomersByBillgroup,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingDataProvider/GetCustomersByBillgroup',
    request,
    metadata || {},
    this.methodDescriptorGetCustomersByBillgroup);
  }

  methodDescriptorGetLoockup = new grpcWeb.MethodDescriptor(
    '/billing.BillingDataProvider/GetLoockup',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.Entity,
    biller_service_pb.LookUpsResponce,
    (request: biller_service_pb.Entity) => {
      return request.serializeBinary();
    },
    biller_service_pb.LookUpsResponce.deserializeBinary
  );

  getLoockup(
    request: biller_service_pb.Entity,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.LookUpsResponce>;

  getLoockup(
    request: biller_service_pb.Entity,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.LookUpsResponce) => void): grpcWeb.ClientReadableStream<biller_service_pb.LookUpsResponce>;

  getLoockup(
    request: biller_service_pb.Entity,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.LookUpsResponce) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingDataProvider/GetLoockup',
        request,
        metadata || {},
        this.methodDescriptorGetLoockup,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingDataProvider/GetLoockup',
    request,
    metadata || {},
    this.methodDescriptorGetLoockup);
  }

  methodDescriptorGetCtgs = new grpcWeb.MethodDescriptor(
    '/billing.BillingDataProvider/GetCtgs',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.Empty,
    biller_service_pb.CtgsResponce,
    (request: biller_service_pb.Empty) => {
      return request.serializeBinary();
    },
    biller_service_pb.CtgsResponce.deserializeBinary
  );

  getCtgs(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.CtgsResponce>;

  getCtgs(
    request: biller_service_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.CtgsResponce) => void): grpcWeb.ClientReadableStream<biller_service_pb.CtgsResponce>;

  getCtgs(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.CtgsResponce) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingDataProvider/GetCtgs',
        request,
        metadata || {},
        this.methodDescriptorGetCtgs,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingDataProvider/GetCtgs',
    request,
    metadata || {},
    this.methodDescriptorGetCtgs);
  }

  methodDescriptorGetBillsByCustkey = new grpcWeb.MethodDescriptor(
    '/billing.BillingDataProvider/GetBillsByCustkey',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.GetBillRequest,
    biller_service_pb.BillResponce,
    (request: biller_service_pb.GetBillRequest) => {
      return request.serializeBinary();
    },
    biller_service_pb.BillResponce.deserializeBinary
  );

  getBillsByCustkey(
    request: biller_service_pb.GetBillRequest,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.BillResponce>;

  getBillsByCustkey(
    request: biller_service_pb.GetBillRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.BillResponce) => void): grpcWeb.ClientReadableStream<biller_service_pb.BillResponce>;

  getBillsByCustkey(
    request: biller_service_pb.GetBillRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.BillResponce) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingDataProvider/GetBillsByCustkey',
        request,
        metadata || {},
        this.methodDescriptorGetBillsByCustkey,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingDataProvider/GetBillsByCustkey',
    request,
    metadata || {},
    this.methodDescriptorGetBillsByCustkey);
  }

  methodDescriptorGetBillsByFormNo = new grpcWeb.MethodDescriptor(
    '/billing.BillingDataProvider/GetBillsByFormNo',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.GetBillRequest,
    biller_service_pb.BillResponce,
    (request: biller_service_pb.GetBillRequest) => {
      return request.serializeBinary();
    },
    biller_service_pb.BillResponce.deserializeBinary
  );

  getBillsByFormNo(
    request: biller_service_pb.GetBillRequest,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.BillResponce>;

  getBillsByFormNo(
    request: biller_service_pb.GetBillRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.BillResponce) => void): grpcWeb.ClientReadableStream<biller_service_pb.BillResponce>;

  getBillsByFormNo(
    request: biller_service_pb.GetBillRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.BillResponce) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingDataProvider/GetBillsByFormNo',
        request,
        metadata || {},
        this.methodDescriptorGetBillsByFormNo,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingDataProvider/GetBillsByFormNo',
    request,
    metadata || {},
    this.methodDescriptorGetBillsByFormNo);
  }

  methodDescriptorLogin = new grpcWeb.MethodDescriptor(
    '/billing.BillingDataProvider/Login',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.LoginRequest,
    biller_service_pb.LoginResponce,
    (request: biller_service_pb.LoginRequest) => {
      return request.serializeBinary();
    },
    biller_service_pb.LoginResponce.deserializeBinary
  );

  login(
    request: biller_service_pb.LoginRequest,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.LoginResponce>;

  login(
    request: biller_service_pb.LoginRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.LoginResponce) => void): grpcWeb.ClientReadableStream<biller_service_pb.LoginResponce>;

  login(
    request: biller_service_pb.LoginRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.LoginResponce) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingDataProvider/Login',
        request,
        metadata || {},
        this.methodDescriptorLogin,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingDataProvider/Login',
    request,
    metadata || {},
    this.methodDescriptorLogin);
  }

}

export class BillingDataCousumerClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorInfo = new grpcWeb.MethodDescriptor(
    '/billing.BillingDataCousumer/Info',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.Empty,
    biller_service_pb.ServiceInfo,
    (request: biller_service_pb.Empty) => {
      return request.serializeBinary();
    },
    biller_service_pb.ServiceInfo.deserializeBinary
  );

  info(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.ServiceInfo>;

  info(
    request: biller_service_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.ServiceInfo) => void): grpcWeb.ClientReadableStream<biller_service_pb.ServiceInfo>;

  info(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.ServiceInfo) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingDataCousumer/Info',
        request,
        metadata || {},
        this.methodDescriptorInfo,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingDataCousumer/Info',
    request,
    metadata || {},
    this.methodDescriptorInfo);
  }

  methodDescriptorWriteFinantialData = new grpcWeb.MethodDescriptor(
    '/billing.BillingDataCousumer/WriteFinantialData',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.PostMessage,
    biller_service_pb.Empty,
    (request: biller_service_pb.PostMessage) => {
      return request.serializeBinary();
    },
    biller_service_pb.Empty.deserializeBinary
  );

  writeFinantialData(
    request: biller_service_pb.PostMessage,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.Empty>;

  writeFinantialData(
    request: biller_service_pb.PostMessage,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.Empty) => void): grpcWeb.ClientReadableStream<biller_service_pb.Empty>;

  writeFinantialData(
    request: biller_service_pb.PostMessage,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingDataCousumer/WriteFinantialData',
        request,
        metadata || {},
        this.methodDescriptorWriteFinantialData,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingDataCousumer/WriteFinantialData',
    request,
    metadata || {},
    this.methodDescriptorWriteFinantialData);
  }

  methodDescriptorWriteFinantialDataOne = new grpcWeb.MethodDescriptor(
    '/billing.BillingDataCousumer/WriteFinantialDataOne',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.PostMessage,
    biller_service_pb.Empty,
    (request: biller_service_pb.PostMessage) => {
      return request.serializeBinary();
    },
    biller_service_pb.Empty.deserializeBinary
  );

  writeFinantialDataOne(
    request: biller_service_pb.PostMessage,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.Empty>;

  writeFinantialDataOne(
    request: biller_service_pb.PostMessage,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.Empty) => void): grpcWeb.ClientReadableStream<biller_service_pb.Empty>;

  writeFinantialDataOne(
    request: biller_service_pb.PostMessage,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.BillingDataCousumer/WriteFinantialDataOne',
        request,
        metadata || {},
        this.methodDescriptorWriteFinantialDataOne,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.BillingDataCousumer/WriteFinantialDataOne',
    request,
    metadata || {},
    this.methodDescriptorWriteFinantialDataOne);
  }

}

export class EngineClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorInfo = new grpcWeb.MethodDescriptor(
    '/billing.Engine/Info',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.Empty,
    biller_service_pb.ServiceInfo,
    (request: biller_service_pb.Empty) => {
      return request.serializeBinary();
    },
    biller_service_pb.ServiceInfo.deserializeBinary
  );

  info(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.ServiceInfo>;

  info(
    request: biller_service_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.ServiceInfo) => void): grpcWeb.ClientReadableStream<biller_service_pb.ServiceInfo>;

  info(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.ServiceInfo) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.Engine/Info',
        request,
        metadata || {},
        this.methodDescriptorInfo,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.Engine/Info',
    request,
    metadata || {},
    this.methodDescriptorInfo);
  }

  methodDescriptorCalulate = new grpcWeb.MethodDescriptor(
    '/billing.Engine/Calulate',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.ChargeRequest,
    biller_service_pb.BillResponce,
    (request: biller_service_pb.ChargeRequest) => {
      return request.serializeBinary();
    },
    biller_service_pb.BillResponce.deserializeBinary
  );

  calulate(
    request: biller_service_pb.ChargeRequest,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.BillResponce>;

  calulate(
    request: biller_service_pb.ChargeRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.BillResponce) => void): grpcWeb.ClientReadableStream<biller_service_pb.BillResponce>;

  calulate(
    request: biller_service_pb.ChargeRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.BillResponce) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.Engine/Calulate',
        request,
        metadata || {},
        this.methodDescriptorCalulate,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.Engine/Calulate',
    request,
    metadata || {},
    this.methodDescriptorCalulate);
  }

  methodDescriptorPost = new grpcWeb.MethodDescriptor(
    '/billing.Engine/Post',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.PostMessage,
    biller_service_pb.Empty,
    (request: biller_service_pb.PostMessage) => {
      return request.serializeBinary();
    },
    biller_service_pb.Empty.deserializeBinary
  );

  post(
    request: biller_service_pb.PostMessage,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.Empty>;

  post(
    request: biller_service_pb.PostMessage,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.Empty) => void): grpcWeb.ClientReadableStream<biller_service_pb.Empty>;

  post(
    request: biller_service_pb.PostMessage,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.Engine/Post',
        request,
        metadata || {},
        this.methodDescriptorPost,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.Engine/Post',
    request,
    metadata || {},
    this.methodDescriptorPost);
  }

  methodDescriptorPostOne = new grpcWeb.MethodDescriptor(
    '/billing.Engine/PostOne',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.PostMessage,
    biller_service_pb.Empty,
    (request: biller_service_pb.PostMessage) => {
      return request.serializeBinary();
    },
    biller_service_pb.Empty.deserializeBinary
  );

  postOne(
    request: biller_service_pb.PostMessage,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.Empty>;

  postOne(
    request: biller_service_pb.PostMessage,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.Empty) => void): grpcWeb.ClientReadableStream<biller_service_pb.Empty>;

  postOne(
    request: biller_service_pb.PostMessage,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.Engine/PostOne',
        request,
        metadata || {},
        this.methodDescriptorPostOne,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.Engine/PostOne',
    request,
    metadata || {},
    this.methodDescriptorPostOne);
  }

  methodDescriptorGetCustomerByCustkey = new grpcWeb.MethodDescriptor(
    '/billing.Engine/GetCustomerByCustkey',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.Key,
    biller_service_pb.Customer,
    (request: biller_service_pb.Key) => {
      return request.serializeBinary();
    },
    biller_service_pb.Customer.deserializeBinary
  );

  getCustomerByCustkey(
    request: biller_service_pb.Key,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.Customer>;

  getCustomerByCustkey(
    request: biller_service_pb.Key,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.Customer) => void): grpcWeb.ClientReadableStream<biller_service_pb.Customer>;

  getCustomerByCustkey(
    request: biller_service_pb.Key,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.Customer) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.Engine/GetCustomerByCustkey',
        request,
        metadata || {},
        this.methodDescriptorGetCustomerByCustkey,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.Engine/GetCustomerByCustkey',
    request,
    metadata || {},
    this.methodDescriptorGetCustomerByCustkey);
  }

  methodDescriptorGetLoockup = new grpcWeb.MethodDescriptor(
    '/billing.Engine/GetLoockup',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.Entity,
    biller_service_pb.LookUpsResponce,
    (request: biller_service_pb.Entity) => {
      return request.serializeBinary();
    },
    biller_service_pb.LookUpsResponce.deserializeBinary
  );

  getLoockup(
    request: biller_service_pb.Entity,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.LookUpsResponce>;

  getLoockup(
    request: biller_service_pb.Entity,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.LookUpsResponce) => void): grpcWeb.ClientReadableStream<biller_service_pb.LookUpsResponce>;

  getLoockup(
    request: biller_service_pb.Entity,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.LookUpsResponce) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.Engine/GetLoockup',
        request,
        metadata || {},
        this.methodDescriptorGetLoockup,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.Engine/GetLoockup',
    request,
    metadata || {},
    this.methodDescriptorGetLoockup);
  }

  methodDescriptorGetCtgs = new grpcWeb.MethodDescriptor(
    '/billing.Engine/GetCtgs',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.Empty,
    biller_service_pb.CtgsResponce,
    (request: biller_service_pb.Empty) => {
      return request.serializeBinary();
    },
    biller_service_pb.CtgsResponce.deserializeBinary
  );

  getCtgs(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.CtgsResponce>;

  getCtgs(
    request: biller_service_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.CtgsResponce) => void): grpcWeb.ClientReadableStream<biller_service_pb.CtgsResponce>;

  getCtgs(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.CtgsResponce) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.Engine/GetCtgs',
        request,
        metadata || {},
        this.methodDescriptorGetCtgs,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.Engine/GetCtgs',
    request,
    metadata || {},
    this.methodDescriptorGetCtgs);
  }

  methodDescriptorGetBillsByCustkey = new grpcWeb.MethodDescriptor(
    '/billing.Engine/GetBillsByCustkey',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.GetBillRequest,
    biller_service_pb.BillResponce,
    (request: biller_service_pb.GetBillRequest) => {
      return request.serializeBinary();
    },
    biller_service_pb.BillResponce.deserializeBinary
  );

  getBillsByCustkey(
    request: biller_service_pb.GetBillRequest,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.BillResponce>;

  getBillsByCustkey(
    request: biller_service_pb.GetBillRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.BillResponce) => void): grpcWeb.ClientReadableStream<biller_service_pb.BillResponce>;

  getBillsByCustkey(
    request: biller_service_pb.GetBillRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.BillResponce) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.Engine/GetBillsByCustkey',
        request,
        metadata || {},
        this.methodDescriptorGetBillsByCustkey,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.Engine/GetBillsByCustkey',
    request,
    metadata || {},
    this.methodDescriptorGetBillsByCustkey);
  }

  methodDescriptorGetBillsByFormNo = new grpcWeb.MethodDescriptor(
    '/billing.Engine/GetBillsByFormNo',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.GetBillRequest,
    biller_service_pb.BillResponce,
    (request: biller_service_pb.GetBillRequest) => {
      return request.serializeBinary();
    },
    biller_service_pb.BillResponce.deserializeBinary
  );

  getBillsByFormNo(
    request: biller_service_pb.GetBillRequest,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.BillResponce>;

  getBillsByFormNo(
    request: biller_service_pb.GetBillRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.BillResponce) => void): grpcWeb.ClientReadableStream<biller_service_pb.BillResponce>;

  getBillsByFormNo(
    request: biller_service_pb.GetBillRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.BillResponce) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.Engine/GetBillsByFormNo',
        request,
        metadata || {},
        this.methodDescriptorGetBillsByFormNo,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.Engine/GetBillsByFormNo',
    request,
    metadata || {},
    this.methodDescriptorGetBillsByFormNo);
  }

}

export class LoginServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorLogin = new grpcWeb.MethodDescriptor(
    '/billing.LoginService/Login',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.LoginRequest,
    biller_service_pb.LoginResponce,
    (request: biller_service_pb.LoginRequest) => {
      return request.serializeBinary();
    },
    biller_service_pb.LoginResponce.deserializeBinary
  );

  login(
    request: biller_service_pb.LoginRequest,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.LoginResponce>;

  login(
    request: biller_service_pb.LoginRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.LoginResponce) => void): grpcWeb.ClientReadableStream<biller_service_pb.LoginResponce>;

  login(
    request: biller_service_pb.LoginRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.LoginResponce) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.LoginService/Login',
        request,
        metadata || {},
        this.methodDescriptorLogin,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.LoginService/Login',
    request,
    metadata || {},
    this.methodDescriptorLogin);
  }

  methodDescriptorInfo = new grpcWeb.MethodDescriptor(
    '/billing.LoginService/Info',
    grpcWeb.MethodType.UNARY,
    biller_service_pb.Empty,
    biller_service_pb.ServiceInfo,
    (request: biller_service_pb.Empty) => {
      return request.serializeBinary();
    },
    biller_service_pb.ServiceInfo.deserializeBinary
  );

  info(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<biller_service_pb.ServiceInfo>;

  info(
    request: biller_service_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: biller_service_pb.ServiceInfo) => void): grpcWeb.ClientReadableStream<biller_service_pb.ServiceInfo>;

  info(
    request: biller_service_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: biller_service_pb.ServiceInfo) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/billing.LoginService/Info',
        request,
        metadata || {},
        this.methodDescriptorInfo,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/billing.LoginService/Info',
    request,
    metadata || {},
    this.methodDescriptorInfo);
  }

}

