/**
 * @fileoverview gRPC-Web generated client stub for PkgQueries
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.27.0-rc2
// source: queries.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as queries_pb from './queries_pb'; // proto import: "queries.proto"


export class QueryServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSearchCustomer = new grpcWeb.MethodDescriptor(
    '/PkgQueries.QueryService/SearchCustomer',
    grpcWeb.MethodType.UNARY,
    queries_pb.SearchCustomerRq,
    queries_pb.SearchCustomerRs,
    (request: queries_pb.SearchCustomerRq) => {
      return request.serializeBinary();
    },
    queries_pb.SearchCustomerRs.deserializeBinary
  );

  searchCustomer(
    request: queries_pb.SearchCustomerRq,
    metadata?: grpcWeb.Metadata | null): Promise<queries_pb.SearchCustomerRs>;

  searchCustomer(
    request: queries_pb.SearchCustomerRq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: queries_pb.SearchCustomerRs) => void): grpcWeb.ClientReadableStream<queries_pb.SearchCustomerRs>;

  searchCustomer(
    request: queries_pb.SearchCustomerRq,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: queries_pb.SearchCustomerRs) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/PkgQueries.QueryService/SearchCustomer',
        request,
        metadata || {},
        this.methodDescriptorSearchCustomer,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/PkgQueries.QueryService/SearchCustomer',
    request,
    metadata || {},
    this.methodDescriptorSearchCustomer);
  }

  methodDescriptorGetAllBillgroups = new grpcWeb.MethodDescriptor(
    '/PkgQueries.QueryService/GetAllBillgroups',
    grpcWeb.MethodType.UNARY,
    queries_pb.Empty,
    queries_pb.ArrBILLING_GROUPS,
    (request: queries_pb.Empty) => {
      return request.serializeBinary();
    },
    queries_pb.ArrBILLING_GROUPS.deserializeBinary
  );

  getAllBillgroups(
    request: queries_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<queries_pb.ArrBILLING_GROUPS>;

  getAllBillgroups(
    request: queries_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: queries_pb.ArrBILLING_GROUPS) => void): grpcWeb.ClientReadableStream<queries_pb.ArrBILLING_GROUPS>;

  getAllBillgroups(
    request: queries_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: queries_pb.ArrBILLING_GROUPS) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/PkgQueries.QueryService/GetAllBillgroups',
        request,
        metadata || {},
        this.methodDescriptorGetAllBillgroups,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/PkgQueries.QueryService/GetAllBillgroups',
    request,
    metadata || {},
    this.methodDescriptorGetAllBillgroups);
  }

  methodDescriptorGetCustomerBooksByBillgroup = new grpcWeb.MethodDescriptor(
    '/PkgQueries.QueryService/GetCustomerBooksByBillgroup',
    grpcWeb.MethodType.UNARY,
    queries_pb.BillgroupRq,
    queries_pb.ArrCUSTOMER_Books,
    (request: queries_pb.BillgroupRq) => {
      return request.serializeBinary();
    },
    queries_pb.ArrCUSTOMER_Books.deserializeBinary
  );

  getCustomerBooksByBillgroup(
    request: queries_pb.BillgroupRq,
    metadata?: grpcWeb.Metadata | null): Promise<queries_pb.ArrCUSTOMER_Books>;

  getCustomerBooksByBillgroup(
    request: queries_pb.BillgroupRq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: queries_pb.ArrCUSTOMER_Books) => void): grpcWeb.ClientReadableStream<queries_pb.ArrCUSTOMER_Books>;

  getCustomerBooksByBillgroup(
    request: queries_pb.BillgroupRq,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: queries_pb.ArrCUSTOMER_Books) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/PkgQueries.QueryService/GetCustomerBooksByBillgroup',
        request,
        metadata || {},
        this.methodDescriptorGetCustomerBooksByBillgroup,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/PkgQueries.QueryService/GetCustomerBooksByBillgroup',
    request,
    metadata || {},
    this.methodDescriptorGetCustomerBooksByBillgroup);
  }

  methodDescriptorGetCustomerMainDataByCustkey = new grpcWeb.MethodDescriptor(
    '/PkgQueries.QueryService/GetCustomerMainDataByCustkey',
    grpcWeb.MethodType.UNARY,
    queries_pb.CustkeyRq,
    queries_pb.CUSTOMER_MAIN_DATA,
    (request: queries_pb.CustkeyRq) => {
      return request.serializeBinary();
    },
    queries_pb.CUSTOMER_MAIN_DATA.deserializeBinary
  );

  getCustomerMainDataByCustkey(
    request: queries_pb.CustkeyRq,
    metadata?: grpcWeb.Metadata | null): Promise<queries_pb.CUSTOMER_MAIN_DATA>;

  getCustomerMainDataByCustkey(
    request: queries_pb.CustkeyRq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: queries_pb.CUSTOMER_MAIN_DATA) => void): grpcWeb.ClientReadableStream<queries_pb.CUSTOMER_MAIN_DATA>;

  getCustomerMainDataByCustkey(
    request: queries_pb.CustkeyRq,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: queries_pb.CUSTOMER_MAIN_DATA) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/PkgQueries.QueryService/GetCustomerMainDataByCustkey',
        request,
        metadata || {},
        this.methodDescriptorGetCustomerMainDataByCustkey,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/PkgQueries.QueryService/GetCustomerMainDataByCustkey',
    request,
    metadata || {},
    this.methodDescriptorGetCustomerMainDataByCustkey);
  }

  methodDescriptorGetCustomerTransactions = new grpcWeb.MethodDescriptor(
    '/PkgQueries.QueryService/GetCustomerTransactions',
    grpcWeb.MethodType.UNARY,
    queries_pb.CustkeyRq,
    queries_pb.ArrTRANSACTIONS,
    (request: queries_pb.CustkeyRq) => {
      return request.serializeBinary();
    },
    queries_pb.ArrTRANSACTIONS.deserializeBinary
  );

  getCustomerTransactions(
    request: queries_pb.CustkeyRq,
    metadata?: grpcWeb.Metadata | null): Promise<queries_pb.ArrTRANSACTIONS>;

  getCustomerTransactions(
    request: queries_pb.CustkeyRq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: queries_pb.ArrTRANSACTIONS) => void): grpcWeb.ClientReadableStream<queries_pb.ArrTRANSACTIONS>;

  getCustomerTransactions(
    request: queries_pb.CustkeyRq,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: queries_pb.ArrTRANSACTIONS) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/PkgQueries.QueryService/GetCustomerTransactions',
        request,
        metadata || {},
        this.methodDescriptorGetCustomerTransactions,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/PkgQueries.QueryService/GetCustomerTransactions',
    request,
    metadata || {},
    this.methodDescriptorGetCustomerTransactions);
  }

  methodDescriptorGetCustomerStatements = new grpcWeb.MethodDescriptor(
    '/PkgQueries.QueryService/GetCustomerStatements',
    grpcWeb.MethodType.UNARY,
    queries_pb.CustkeyRq,
    queries_pb.ArrSTATMENT,
    (request: queries_pb.CustkeyRq) => {
      return request.serializeBinary();
    },
    queries_pb.ArrSTATMENT.deserializeBinary
  );

  getCustomerStatements(
    request: queries_pb.CustkeyRq,
    metadata?: grpcWeb.Metadata | null): Promise<queries_pb.ArrSTATMENT>;

  getCustomerStatements(
    request: queries_pb.CustkeyRq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: queries_pb.ArrSTATMENT) => void): grpcWeb.ClientReadableStream<queries_pb.ArrSTATMENT>;

  getCustomerStatements(
    request: queries_pb.CustkeyRq,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: queries_pb.ArrSTATMENT) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/PkgQueries.QueryService/GetCustomerStatements',
        request,
        metadata || {},
        this.methodDescriptorGetCustomerStatements,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/PkgQueries.QueryService/GetCustomerStatements',
    request,
    metadata || {},
    this.methodDescriptorGetCustomerStatements);
  }

  methodDescriptorGetCustomerAgreements = new grpcWeb.MethodDescriptor(
    '/PkgQueries.QueryService/GetCustomerAgreements',
    grpcWeb.MethodType.UNARY,
    queries_pb.CustkeyRq,
    queries_pb.ArrCustAgreem,
    (request: queries_pb.CustkeyRq) => {
      return request.serializeBinary();
    },
    queries_pb.ArrCustAgreem.deserializeBinary
  );

  getCustomerAgreements(
    request: queries_pb.CustkeyRq,
    metadata?: grpcWeb.Metadata | null): Promise<queries_pb.ArrCustAgreem>;

  getCustomerAgreements(
    request: queries_pb.CustkeyRq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: queries_pb.ArrCustAgreem) => void): grpcWeb.ClientReadableStream<queries_pb.ArrCustAgreem>;

  getCustomerAgreements(
    request: queries_pb.CustkeyRq,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: queries_pb.ArrCustAgreem) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/PkgQueries.QueryService/GetCustomerAgreements',
        request,
        metadata || {},
        this.methodDescriptorGetCustomerAgreements,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/PkgQueries.QueryService/GetCustomerAgreements',
    request,
    metadata || {},
    this.methodDescriptorGetCustomerAgreements);
  }

  methodDescriptorGetCustomerReadings = new grpcWeb.MethodDescriptor(
    '/PkgQueries.QueryService/GetCustomerReadings',
    grpcWeb.MethodType.UNARY,
    queries_pb.CustkeyRq,
    queries_pb.ArrREADINGS,
    (request: queries_pb.CustkeyRq) => {
      return request.serializeBinary();
    },
    queries_pb.ArrREADINGS.deserializeBinary
  );

  getCustomerReadings(
    request: queries_pb.CustkeyRq,
    metadata?: grpcWeb.Metadata | null): Promise<queries_pb.ArrREADINGS>;

  getCustomerReadings(
    request: queries_pb.CustkeyRq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: queries_pb.ArrREADINGS) => void): grpcWeb.ClientReadableStream<queries_pb.ArrREADINGS>;

  getCustomerReadings(
    request: queries_pb.CustkeyRq,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: queries_pb.ArrREADINGS) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/PkgQueries.QueryService/GetCustomerReadings',
        request,
        metadata || {},
        this.methodDescriptorGetCustomerReadings,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/PkgQueries.QueryService/GetCustomerReadings',
    request,
    metadata || {},
    this.methodDescriptorGetCustomerReadings);
  }

  methodDescriptorGetBillPrintCust = new grpcWeb.MethodDescriptor(
    '/PkgQueries.QueryService/GetBillPrintCust',
    grpcWeb.MethodType.UNARY,
    queries_pb.CustkeyRq,
    queries_pb.ArrBILL_PRINT,
    (request: queries_pb.CustkeyRq) => {
      return request.serializeBinary();
    },
    queries_pb.ArrBILL_PRINT.deserializeBinary
  );

  getBillPrintCust(
    request: queries_pb.CustkeyRq,
    metadata?: grpcWeb.Metadata | null): Promise<queries_pb.ArrBILL_PRINT>;

  getBillPrintCust(
    request: queries_pb.CustkeyRq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: queries_pb.ArrBILL_PRINT) => void): grpcWeb.ClientReadableStream<queries_pb.ArrBILL_PRINT>;

  getBillPrintCust(
    request: queries_pb.CustkeyRq,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: queries_pb.ArrBILL_PRINT) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/PkgQueries.QueryService/GetBillPrintCust',
        request,
        metadata || {},
        this.methodDescriptorGetBillPrintCust,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/PkgQueries.QueryService/GetBillPrintCust',
    request,
    metadata || {},
    this.methodDescriptorGetBillPrintCust);
  }

  methodDescriptorGetAllCustomerHistory = new grpcWeb.MethodDescriptor(
    '/PkgQueries.QueryService/GetAllCustomerHistory',
    grpcWeb.MethodType.UNARY,
    queries_pb.CustkeyRq,
    queries_pb.ArrCST_HISTORY,
    (request: queries_pb.CustkeyRq) => {
      return request.serializeBinary();
    },
    queries_pb.ArrCST_HISTORY.deserializeBinary
  );

  getAllCustomerHistory(
    request: queries_pb.CustkeyRq,
    metadata?: grpcWeb.Metadata | null): Promise<queries_pb.ArrCST_HISTORY>;

  getAllCustomerHistory(
    request: queries_pb.CustkeyRq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: queries_pb.ArrCST_HISTORY) => void): grpcWeb.ClientReadableStream<queries_pb.ArrCST_HISTORY>;

  getAllCustomerHistory(
    request: queries_pb.CustkeyRq,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: queries_pb.ArrCST_HISTORY) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/PkgQueries.QueryService/GetAllCustomerHistory',
        request,
        metadata || {},
        this.methodDescriptorGetAllCustomerHistory,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/PkgQueries.QueryService/GetAllCustomerHistory',
    request,
    metadata || {},
    this.methodDescriptorGetAllCustomerHistory);
  }

  methodDescriptorTestRpc = new grpcWeb.MethodDescriptor(
    '/PkgQueries.QueryService/TestRpc',
    grpcWeb.MethodType.UNARY,
    queries_pb.TEST,
    queries_pb.JSON_TEST,
    (request: queries_pb.TEST) => {
      return request.serializeBinary();
    },
    queries_pb.JSON_TEST.deserializeBinary
  );

  testRpc(
    request: queries_pb.TEST,
    metadata?: grpcWeb.Metadata | null): Promise<queries_pb.JSON_TEST>;

  testRpc(
    request: queries_pb.TEST,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: queries_pb.JSON_TEST) => void): grpcWeb.ClientReadableStream<queries_pb.JSON_TEST>;

  testRpc(
    request: queries_pb.TEST,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: queries_pb.JSON_TEST) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/PkgQueries.QueryService/TestRpc',
        request,
        metadata || {},
        this.methodDescriptorTestRpc,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/PkgQueries.QueryService/TestRpc',
    request,
    metadata || {},
    this.methodDescriptorTestRpc);
  }

  methodDescriptorGetCustWalletDetails = new grpcWeb.MethodDescriptor(
    '/PkgQueries.QueryService/GetCustWalletDetails',
    grpcWeb.MethodType.UNARY,
    queries_pb.WalletDetailsRq,
    queries_pb.ArrWalletDetails,
    (request: queries_pb.WalletDetailsRq) => {
      return request.serializeBinary();
    },
    queries_pb.ArrWalletDetails.deserializeBinary
  );

  getCustWalletDetails(
    request: queries_pb.WalletDetailsRq,
    metadata?: grpcWeb.Metadata | null): Promise<queries_pb.ArrWalletDetails>;

  getCustWalletDetails(
    request: queries_pb.WalletDetailsRq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: queries_pb.ArrWalletDetails) => void): grpcWeb.ClientReadableStream<queries_pb.ArrWalletDetails>;

  getCustWalletDetails(
    request: queries_pb.WalletDetailsRq,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: queries_pb.ArrWalletDetails) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/PkgQueries.QueryService/GetCustWalletDetails',
        request,
        metadata || {},
        this.methodDescriptorGetCustWalletDetails,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/PkgQueries.QueryService/GetCustWalletDetails',
    request,
    metadata || {},
    this.methodDescriptorGetCustWalletDetails);
  }

  methodDescriptorGetCustomermetersReadings = new grpcWeb.MethodDescriptor(
    '/PkgQueries.QueryService/GetCustomermetersReadings',
    grpcWeb.MethodType.UNARY,
    queries_pb.CustkeyRq,
    queries_pb.ArrCustREADINGS,
    (request: queries_pb.CustkeyRq) => {
      return request.serializeBinary();
    },
    queries_pb.ArrCustREADINGS.deserializeBinary
  );

  getCustomermetersReadings(
    request: queries_pb.CustkeyRq,
    metadata?: grpcWeb.Metadata | null): Promise<queries_pb.ArrCustREADINGS>;

  getCustomermetersReadings(
    request: queries_pb.CustkeyRq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: queries_pb.ArrCustREADINGS) => void): grpcWeb.ClientReadableStream<queries_pb.ArrCustREADINGS>;

  getCustomermetersReadings(
    request: queries_pb.CustkeyRq,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: queries_pb.ArrCustREADINGS) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/PkgQueries.QueryService/GetCustomermetersReadings',
        request,
        metadata || {},
        this.methodDescriptorGetCustomermetersReadings,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/PkgQueries.QueryService/GetCustomermetersReadings',
    request,
    metadata || {},
    this.methodDescriptorGetCustomermetersReadings);
  }

}

