export interface BILLCTYPEAP {
  CUSTKEY: string;
  CYCLE_ID: number;
  C_TYPE: string;
  CONSUMP: number | null;
  CONSUMP_TYPE: number | null;
  CONSUMP_PERC: number | null;
  NO_UNITS: number | null;
  PAYMENT_NO: string;
  WATER_AMT: number;
  SEWER_AMT: number;
  BASIC_AMT: number | null;
  TAX_AMT: number | null;
  INSTALLS_AMT: number | null;
  DBT_AMT: number | null;
  CRDT_AMT: number | null;
  AGREEM_AMT: number | null;
  TAKAFUL_AMT: number | null;
  TANZEEM_AMT: number | null;
  METER_INSTALLS_AMT: number | null;
  CONN_INSTALLS_AMT: number | null;
  ROUND_AMT: number | null;
  OTHER_AMT: number | null;
  OTHER_AMT1: number | null;
  OTHER_AMT2: number | null;
  OTHER_AMT3: number | null;
  OTHER_AMT4: number | null;
  OTHER_AMT5: number | null;
  METER_AMT: number | null;
  CONN_AMT: number | null;
  METER_MAN_AMT: number | null;
  COMPUTER_AMT: number | null;
  CONTRACT_AMT: number | null;
  GOV_AMT: number | null;
  UNI_AMT: number | null;
  OTHER_CUR_AMT: number | null;
  CLEAN_AMT: number | null;
  COLLECTION_AMT: number | null;
  PARTIAL_CUR_AMT: number | null;
}

export type BILLCTYPEApi = BILLCTYPEAP;
