interface IDistributionItem {
  STATION_NO: number | null;
  STATION_NAME: string;
  EMP_ID: number | null;
  CUSTKEY: string;
  PROP_REF: string;
  SEQ_NO: number | null;
  KEY: string;
  ISSUED_AMOUNT: number | null;
  ISSUED_COUNT: number | null;
  BILLGROUP: string;
  BILNG_DATE: string | null;
  BOOK_NO: string;
  WALK_NO: string;
  CYCLE_ID: number | null;
  DEVICE_ID: string;
  CTG: string;
  PERCENTAGE: number | null;
  SURNAME: string;
  ADDRESS: string;
  REACHED_COUNT: number | null;
  UNREACHED_COUNT: number | null;
  POSTED_COUNT: number | null;
  POSTED_AMOUNT: number | null;
  C_BAND: number | null;
  R_BAND: string;
  LOCATION_DIFF: number | null;
  REACH_DATE: string | null;
  DESCRIPTION: string;
  IS_CLOSED: boolean | null;
  IS_POSTED: boolean | null;
  IS_CLOSED_INDEVICE: boolean | null;
  IS_CANCELLED: boolean | null;
  IS_REACHED: boolean | null;
  OLD_KEY: string;
  ERROR_MESSAGE: string;
  IS_CTYPES: boolean | null;
  USER: string;
  STAMP_DATE: string | null;
  LAST_FOR_COLLECT_CYCLE?: boolean;
}

export type DISTRIPUTIONITEMAPI = Partial<IDistributionItem>;
