export interface EMPApi {
  ID: number;
  USER_NAME: string;
  PASSWORD: string;
  FULL_NAME: string;
  ADDRESS: string;
  TEL: string;
  DEVICE_ID: string;
  BRANCH_ID: number | null;
  NOTES: string;
  DISABLED: boolean | null;
  READING: boolean | null;
  COLLECTION: boolean | null;
  SYS_ADMIN: boolean | null;
  DATA_ADMIN: boolean | null;
  DATA_ENTRY: boolean | null;
  REPORTING_VIEWER: boolean | null;
  CASHER: boolean | null;
  MOBILE1: string;
  MOBILE2: string;
  NID: string;
  EMAIL: string;
  ALlOW_CANCEL: boolean | null;
  ALLOW_MODIFY_READING: boolean | null;
  FLAGE1: boolean | null;
  FLAGE2: boolean | null;
  VALUE1: string;
  VALUE2: string;
  ORIGINAL_STATION: string;
  EMP_TYPE: number | null;
  BILNG_EMP_ID: string;
  MARKETING: boolean | null;
  IS_STORE_MAN: boolean | null;
  KEEPER: boolean | null;
  QUOTA: number | null;
  DASHBOARD: boolean | null;
  CLOSE_READING_CYCLE: boolean | null;
  CLOSE_COLLECTION_CYCLE: boolean | null;
  ALLOW_OVER_PAYMENT: boolean | null;
  ENABLE_HH_PRINTING: boolean | null;
  PARTIAL_COLLECTION_STATE: number | null;
  RANDOMLY_METER_PICTURE_PERCENT: number | null;
  DIR_COLLECTION: string | null;
  READING_ESTIM_PERCENT: number | null;
  READING_PERCENT: number | null;
  DAY_READING_PERCENT: number | null;
  DEPOSIT_DURATION: number | null;
  OFFLINE_PERIOD: number | null;
  BILLS_COUNT_ALLOWED_OFFLINE: number | null;
  DEPOSIT_DURATION_EXTRA_DAYES: number | null;
  DEPOSITS_QUOTA: number | null;
}
