import { HSTHANDMHSTApi } from './hstHandMhst';

export interface IHANDMHST extends HSTHANDMHSTApi {
  BILLGROUP: string;
  BOOK_NO_C: string;
  WALK_NO_C: string;
  BOOK_NO_R: string;
  WALK_NO_R: string;
  EMPID_C: number | null;
  IS_READING_ROW: number;
  IS_COLLECTION_ROW: number;
  delivery_st: number | null;
  payment_no: string;
  STATM_NO: number | null;
  READING_DEVICEID: string;
  COLLECTION_DEVICEID: string;
  SEQ_NO_C: number | null;
  SEQ_NO_R: number | null;
  tent_name: string;
  description: string;
  meter_type: string;
  meter_ref: string;
  ua_adress1: string;
  ua_adress2: string;
  ua_adress3: string;
  ua_adress4: string;
  prop_ref: string;
  cr_reading: number | null;
  pr_read1: number | null;
  consump: number | null;
  descrepancy: number | null;
  stamp_date: string | null;
  stamp_user: string;
  op_status: number | null;
  min_consump: number | null;
  max_consump: number | null;
  ctypegrp_id: string;
  serv_aloc: string;
  lat_c: number | null;
  lng_c: number | null;
  lat_r: number | null;
  lng_r: number | null;
  READING_DATE: string | null;
  IS_POSTED_R: boolean | null;
  POST_DATE_R: string | null;
  READING_NOTE: number | null;
  COLLECTION_NOTE: number | null;
  LOCATION_SOURCE: number | null;
  EMPID_R: number | null;
  ACCURECY_C: number | null;
  ACCURECY_R: number | null;
  OLD_KEY: string;
  UPDATE_COUNT_C: number | null;
  SYNC_COUNT_C: number | null;
  UPDATE_COUNT_R: number | null;
  SYNC_COUNT_R: number | null;
  IS_CANCELLED_C: boolean | null;
  IS_CANCELLED_R: boolean | null;
  CANCEL_DATE_C: string | null;
  CANCEL_DATE_R: string | null;
  CANCEL_BY_C: string;
  CANCEL_BY_R: string;
  IS_LOCKED_C: boolean | null;
  IS_LOCKED_R: boolean | null;
  LAT_REF: number | null;
  LNG_REF: number | null;
  IS_REF: boolean | null;
  DISTANCE_REF: number | null;
  READING_DISTANCE: number | null;
  OPERATION_FLAGE: number | null;
  GARD: boolean | null;
  INSTALMENT_RATIO: string;
  CONSUMPTION_TYPE: string;
  S_METER_TYPE: string;
  HAFZA_PRINT_COUNT: number | null;
  BUILDING_NO: number | null;
  GROUP_CODE: number | null;
  FILE_NO: number | null;
  ACCES_CODE: string;
  PR_ACCES_CODE: string;
  PR_OP_STATUS: number | null;
  NO_DIALS: number | null;
  CLOCK_OVER: boolean | null;
  SUPER_LOCK_R: boolean | null;
  PR_AVRG_CONS: number | null;
  PREV_METER_REF: string;
  INSTALMENT: number | null;
  CUR_PAYMNTS: number | null;
  BILL_READY: boolean | null;
  PR_READ2: number | null;
  PR_CONS: number | null;
  CALC_TYPE: string;
  PR_READ_TYPE: string;
  MARKED: boolean | null;
  MARKE_NOTE: string;
  NEGATIVE_FLAGE: number | null;
  IS_GARD_POST: boolean | null;
  PORTAL_CR_READING: number | null;
  PORTAL_CR_DATE: number | null;
  GARD_STAMPDATE: string | null;
  GARD_USER: string;
  IS_MULTI_CTYPES: boolean | null;
  AMOUNT_COLLECTED: number | null;
  BILL_AMOUNT: number | null;
  DUE_AMOUNT: number | null;
  ISSUE_ST: number | null;
  ISSUE_TYPE: number | null;
  ISSUE_ST_ID: number | null;
  PRINT_READY: boolean | null;
  BILL_ADJ_AMOUNT: number | null;
  INSTALMENT_DATE: string | null;
  MIN_CHARGE: number | null;
  PREV_OWNER_C: number | null;
  TRANSFEER_DATE_C: string | null;
  PREV_OWNER_R: number | null;
  TRANSFEER_DATE_R: string | null;
  READING_CYCLEID: number | null;
  READING_BILNGDATE: string | null;
  READ_BY: string;
  READ_METHOD: string;
  IS_ESTIM_READING: boolean | null;
  NO_UNITS_NEW: number | null;
  C_TYPE_NEW: string;
  IS_SEWER_ALLOCATE_NEW: boolean | null;
  HHUSER_C: string;
  HHUSER_R: string;
  NOTE_C: string;
  NOTE_R: string;
  VALUE_R: number | null;
  STR_VALUE_R1: string;
  HHDEVICE_VERSION: string;
  IS_HH_NOTIFIED: boolean | null;
  IS_HQ_NOTIFIED_C: boolean | null;
  IS_HQ_NOTIFIED_R: boolean | null;
  IS_ACC_CONSUMP: boolean | null;
  ACC_DATE: string | null;
  PAY_PRINT_COUNT: number | null;
  PRV_PRINT_COUNT: number | null;
  CUSTOMER_ID: number | null;
  CONNECTION_ID: number | null;
  PROPERTY_ID: number | null;
  METER_ID: number | null;
  COLLECTION_DATE: string | null;
  LOCATION_DATE: string | null;
  ACC_END_DATE: string | null;
  WALK_DELIVERY_ID: number | null;
  GARD_PAYMENT_NO: string;
  IS_MULTI_CONN: boolean | null;
  TOTAL_CL_BLNCE: number | null;
  RECEIPT_TYPE: number | null;
  SYNC_MAS_ST: number;
  SYNC_MAS_HH: number;
  STOP_ISSUE: boolean | null;
  RECALC_ID: number | null;
  IS_MANUAL_ESTIM: boolean | null;
  ALLOW_ESTIM_CONSUMP: boolean | null;
}
