export interface SUMBCYCAPI {
  BILLGROUP: string;
  BILNG_DATE: string;
  DESCRIPTION: string;
  ACT01_DONE: number | null;
  ACT02_DONE: number | null;
  ACT03_DONE: number | null;
  ACT04_DONE: number | null;
  ACT05_DONE: number | null;
  ACT06_DONE: number | null;
  CYCLE_CLSD: number | null;
  CUTOFF_MTR: string | null;
  CUTOFF_EST: string | null;
  CUTOFF_INV: string | null;
  CUTOFF_STM: string | null;
  PR_STMDATE: string | null;
  PR_DISDATE: string | null;
  PR_BILMNTH: number | null;
  PR_BILYEAR: number | null;
  PR_MSG1: string | null;
  PR_MSG2: string | null;
  PR_MSG3: string | null;
  PR_MSG4: string | null;
  STAMP_DATE: string | null;
  STAMP_USER: string;
  CYCLE_LEN: number | null;
  CYCLE_ID: number | null;
  SD_START: string | null;
  SD_CLOSE: string | null;
}
