export interface USERApi {
  ID?: number;
  STATION_NO?: number | null;
  FULL_NAME?: string;
  USER_NAME?: string;
  PASSWORD?: string;
  SYS_ADMIN?: boolean | null;
  READING_ADMIN?: boolean | null;
  COLLECTION_ADMIN?: boolean | null;
  REPORING_ADMIN?: boolean | null;
  HH_MONITOR?: boolean | null;
  USER_MANAGEMENT?: boolean | null;
  SYSTEM_MNTINANCE?: boolean | null;
  DATA_ADMIN?: boolean | null;
  IS_ENC?: boolean | null;
  NID?: string;
  EMAIL?: string;
  ALLOW_COLLECTION?: boolean | null;
  ALLOW_MODIFY_READING?: boolean | null;
  ALLOW_DEPOSIT?: boolean | null;
  ALLOW_CANCEL?: boolean | null;
  ALLOW_POST_C?: boolean | null;
  ALLOW_POST_R?: boolean | null;
  ALLOW_COMPENSATION?: boolean | null;
  VALUE1?: string;
  VALUE2?: string;
  MAP_READING?: boolean | null;
  MAP_COLLECTION?: boolean | null;
  MAP_LOCATION?: boolean | null;
  MAP_PATH?: boolean | null;
  MAP_COMPLAINTS?: boolean | null;
  MAP_BAD_CONN?: boolean | null;
  WALK_ARRANGE_POST?: boolean | null;
  UPDATE_CUSTOMER_LOCATION?: boolean | null;
  ALLOW_CANCEL_DEP_COL?: boolean | null;
  ALLOW_RECOL_CANCEL?: boolean | null;
  ALLOW_MAPS?: boolean | null;
  ALLOW_LOADDATA_C?: boolean | null;
  ALLOW_LOADDATA_R?: boolean | null;
  IS_CASHIER?: boolean | null;
  CASHIER_ID?: number | null;
  EDAMS_CLEAR_READINGS?: boolean | null;
  EDAMS_RECALC?: boolean | null;
  EDAMS_CS?: boolean | null;
  ALLOW_METER_MODIFY?: boolean | null;
  ALLOW_GARD?: boolean | null;
  RESEND_COLLECTION?: boolean | null;
  RESEND_READING?: boolean | null;
  CLOSE_COLLECTION?: boolean | null;
  CLOSE_READING?: boolean | null;
  COLLECTION_DISCOUNT?: boolean | null;
  REFRESH_BILLS_DATA?: boolean | null;
  REFRESH_CUSTOMER_BILLS?: boolean | null;
  CALCULATE_DUE_AMOUNT?: boolean | null;
  COLLECT_BILL_SINGL_UINT?: boolean | null;
  PRINT_PAYMENT_REQUEST?: boolean | null;
  PARTIAL_COLLECTION?: boolean | null;
  ALONE_PANEL?: boolean | null;
  EDAMS_RECALC_NEW?: boolean | null;
  ALLOW_MODIFY_PREV_READING?: boolean | null;
  LIST_COLLECTION?: boolean | null;
  MARKETING?: boolean | null;
  PREPEAR_HAFZA?: boolean | null;
  CASH_BOX?: boolean | null;
  SWITCH?: boolean | null;
  UFLAG?: boolean | null;
  PORTAL?: boolean | null;
  ALLOW_FAWRY_OPEN?: boolean | null;
  ALLOW_FAWRY_CLOSE?: boolean | null;
  SURVEY?: boolean | null;
  REPORTS?: boolean | null;
  DASHBOARD?: boolean | null;
  QUERY?: boolean | null;
  DEVICE_MANAGMENT?: boolean | null;
  SYNC?: boolean | null;
  CANCEL_BILL?: boolean | null;
  CANCEL_DELIVERY?: boolean | null;
  DEPARTMENT?: number | null;
  ALLOW_CUST_MOD?: boolean | null;
  ALLOW_ESTIM_READING?: boolean | null;
  ALLOW_BATCH_ESTIM_READING?: boolean | null;
  PRINTER_TYPE?: string;
  CLOSE_COLLECTION_INDEVICE?: boolean | null;
  CLOSE_READING_INDEVICE?: boolean | null;
  ALLOW_METER_STATUS_CHANGE?: boolean | null;
  ALLOW_CUSTOMER_RESEQUENCE?: boolean | null;
  ALLOW_GOV_COLLECTION?: boolean | null;
  EMP_MANAGEMENT?: boolean | null;
  WALKC_ASSIGNMENT?: boolean | null;
  WALKR_ASSIGNMENT?: boolean | null;
  ALLOW_TAX_PUSH?: boolean | null;
  ALLOW_ESTIM_CONSUMP?: boolean | null;
  REOPEN_READING?: boolean | null;
}
