export interface VWHANDBILL2 {
  STATION_NO: number;
  CUSTKEY: string;
  CYCLE_ID: number;
  STATM_NO: number | null;
  READING_DEVICEID: string;
  COLLECTION_DEVICEID: string;
  BILNG_DATE: string;
  BILLGROUP: string;
  BOOK_NO_C: string;
  WALK_NO_C: string;
  SEQ_NO_C: number | null;
  BOOK_NO_R: string;
  WALK_NO_R: string;
  SEQ_NO_R: number | null;
  tent_name: string;
  c_type: string;
  description: string;
  meter_type: string;
  meter_ref: string;
  ua_adress1: string;
  ua_adress2: string;
  ua_adress3: string;
  ua_adress4: string;
  prop_ref: string;
  cr_reading: number | null;
  pr_read1: number | null;
  consump: number | null;
  descrepancy: number | null;
  stamp_date: string | null;
  stamp_user: string;
  op_status: number | null;
  cl_blnce: number | null;
  delivery_st: number | null;
  payment_no: string;
  min_consump: number | null;
  max_consump: number | null;
  ctypegrp_id: string;
  no_units: number | null;
  serv_aloc: string;
  lat_c: number | null;
  lng_c: number | null;
  lat_r: number | null;
  lng_r: number | null;
  IS_READING_ROW: number;
  IS_COLLECTION_ROW: number;
  NO_UNITS_NEW: number | null;
  C_TYPE_NEW: string;
  IS_SEWER_ALLOCATE_NEW: boolean | null;
  READING_DATE: string | null;
  COLLECTION_DATE: string | null;
  IS_POSTED_R: boolean | null;
  POST_DATE_R: string | null;
  READING_NOTE: number | null;
  COLLECTION_NOTE: number | null;
  LOCATION_SOURCE: number | null;
  LOCATION_DATE: string | null;
  EMPID_C: number | null;
  EMPID_R: number | null;
  HHUSER_C: string;
  HHUSER_R: string;
  ACCURECY_C: number | null;
  ACCURECY_R: number | null;
  OLD_KEY: string;
  UPDATE_COUNT_C: number | null;
  SYNC_COUNT_C: number | null;
  UPDATE_COUNT_R: number | null;
  SYNC_COUNT_R: number | null;
  IS_CANCELLED_C: boolean | null;
  IS_CANCELLED_R: boolean | null;
  CANCEL_DATE_C: string | null;
  CANCEL_DATE_R: string | null;
  CANCEL_BY_C: string;
  CANCEL_BY_R: string;
  IS_LOCKED_C: boolean | null;
  IS_LOCKED_R: boolean | null;
  LAT_REF: number | null;
  LNG_REF: number | null;
  IS_REF: boolean | null;
  DISTANCE_REF: number | null;
  READING_DISTANCE: number | null;
  OPERATION_FLAGE: number | null;
  GARD: boolean | null;
  PAY_PRINT_COUNT: number | null;
  PRV_PRINT_COUNT: number | null;
  INSTALMENT_RATIO: string;
  CONSUMPTION_TYPE: string;
  READ_TYPE: number | null;
  S_METER_TYPE: string;
  S_CONSUMP: number | null;
  S_PR_READING: number | null;
  S_CR_READING: number | null;
  HAFZA_PRINT_COUNT: number | null;
  BUILDING_NO: number | null;
  GROUP_CODE: number | null;
  FILE_NO: number | null;
  ACCES_CODE: string;
  PR_ACCES_CODE: string;
  PR_OP_STATUS: number | null;
  NO_DIALS: number | null;
  CLOCK_OVER: boolean | null;
  SUPER_LOCK_R: boolean | null;
  IS_HH_NOTIFIED: boolean | null;
  IS_HQ_NOTIFIED_C: boolean | null;
  IS_HQ_NOTIFIED_R: boolean | null;
  MODIFIED_AVRG_CONSUMP: number | null;
  CONN_AVRG_CONSUMP: number | null;
  PR_AVRG_CONS: number | null;
  PREV_METER_REF: string;
  WATER_AMT: number | null;
  SEWER_AMT: number | null;
  BASIC_AMT: number | null;
  TAX_AMT: number | null;
  INSTALLS_AMT: number | null;
  DBT_AMT: number | null;
  CRDT_AMT: number | null;
  AGREEM_AMT: number | null;
  TAKAFUL_AMT: number | null;
  TANZEEM_AMT: number | null;
  METER_INSTALLS_AMT: number | null;
  CONN_INSTALLS_AMT: number | null;
  ROUND_AMT: number | null;
  OTHER_AMT: number | null;
  OTHER_AMT1: number | null;
  OTHER_AMT2: number | null;
  OTHER_AMT3: number | null;
  OTHER_AMT4: number | null;
  OTHER_AMT5: number | null;
  METER_AMT: number | null;
  CONN_AMT: number | null;
  METER_MAN_AMT: number | null;
  COMPUTER_AMT: number | null;
  CONTRACT_AMT: number | null;
  GOV_AMT: number | null;
  UNI_AMT: number | null;
  OP_BLNCE: number | null;
  INSTALMENT: number | null;
  CUR_PAYMNTS: number | null;
  CUR_CHARGES: number | null;
  BILL_READY: boolean | null;
  PR_READ2: number | null;
  PR_CONS: number | null;
  CALC_TYPE: string;
  PR_READ_TYPE: string;
  IS_ACC_CONSUMP: boolean | null;
  ACC_DATE: string | null;
  MARKED: boolean | null;
  MARKE_NOTE: string;
  NEGATIVE_FLAGE: number | null;
  IS_GARD_POST: boolean | null;
  PORTAL_CR_READING: number | null;
  PORTAL_CR_DATE: number | null;
  GARD_STAMPDATE: string | null;
  GARD_USER: string;
  IS_MULTI_CTYPES: boolean | null;
  OTHER_CUR_AMT: number | null;
  CLEAN_AMT: number | null;
  COLLECTION_AMT: number | null;
  PARTIAL_CUR_AMT: number | null;
  AMOUNT_COLLECTED: number | null;
  BILL_AMOUNT: number | null;
  DUE_AMOUNT: number | null;
  ISSUE_ST: number | null;
  ISSUE_TYPE: number | null;
  ISSUE_ST_ID: number | null;
  PRINT_READY: boolean | null;
  BILL_ADJ_AMOUNT: number | null;
  INSTALMENT_DATE: string | null;
  MIN_CHARGE: number | null;
  PREV_OWNER_C: number | null;
  TRANSFEER_DATE_C: string | null;
  PREV_OWNER_R: number | null;
  TRANSFEER_DATE_R: string | null;
  READING_CYCLEID: number | null;
  READING_BILNGDATE: string | null;
  READ_BY: string;
  READ_METHOD: string;
  IS_ESTIM_READING: boolean | null;
  IS_MULTI_CONN: boolean | null;
}
