import type z from "zod";
import type { FormSchema } from "./component/threefields/FormSchema";

export interface FormThreeFieldsRef {
  submit: () => void;
}
export type FormThreeFieldTypes = z.infer<typeof FormSchema>;
export type FormThreeFieldsProps = {
  onSubmit: (formData: FormThreeFieldTypes) => void;
  data?: billGroupsTypes[];
  defaultValues?: FormThreeFieldTypes;
  onClose?: () => void;
  id: string;
};
export type SelectOption = {
  value: string | number;
  label: string;
};
export type billGroupsTypes = {
  GROUP_ID: string;
  DESCRIPTION: string;
  STATION_NO: number;
  UNUSED: boolean;
  READING_CYCLE_LEN: number;
};
export type UploadCardsProps = {
  data?: billGroupsTypes[];
};

export type ShowDialogProps = {
  data: billGroupsTypes[];
  title: string;
  id: string;
};
export type BookType = {
  OWNERS: [];
  STATION_NO: number;
  BILLGROUP: string;
  BOOK_NO: string;
  WALK_NO: string;
  CYCLE_ID: number;
  IS_COLLECTION: boolean;
  IS_READING: boolean;
  BILNG_DATE: string;
  BDB_CDB_C: number;
  BDB_CDB_DATE_C: string;
  BDB_CDB_USER_C: string;
  BDB_CDB_R: number;
  BDB_CDB_DATE_R: string;
  BDB_CDB_USER_R: string;
  CDB_HH_C: number;
  CDB_HH_DATE_C: string;
  CDB_HH_R: number;
  CDB_HH_DATE_R: string;
  HH_CDB_C: number;
  HH_CDB_R: number;
  CDB_BDB_C: number;
  CDB_BDB_DATE_C: string;
  CDB_BDB_USER_C: string;
  CDB_BDB_R: number;
  ISCYCLE_COMPLETED_C: number;
  ISCYCLE_COMPLETED_R: number;
  DEVICEID_R: string;
  DEVICEID_C: string;
  WALK_DESCRIPTION: string;
  BILNG_DESCRIPTION: string;
  IS_ALLOWED_C: boolean;
  IS_ALLOWED_R: boolean;
  IS_READY_C: boolean;
  IS_READY_R: boolean;
  COUNT_C: number;
  COUNT_R: number;
  EMPID_C: number;
  EMPID_R: number;
  ISSUED_AMOUNT: number;
  IS_METER_BOOK?: boolean;
  IS_CUSTOMER_BOOK: boolean;
  ALLOW_FAWRY: boolean;
  BILLS: [];
  READER: string;
  COLLECTOR: string;
  COUNT_CYCLES: number;
  ALL_BILL_DATE: boolean;
  Cycles: [];
  IS_ALLOWED_C_FRONT: boolean;
  IS_ALLOWED_R_FRONT: boolean;
};

export type WalkType = {
  OWNERS: [];
  STATION_NO: number;
  BILLGROUP: string;
  BOOK_NO: string;
  WALK_NO: string;
  CYCLE_ID: number;
  IS_COLLECTION: boolean;
  IS_READING: boolean;
  ASSIGNED_TO_HH: number;
  BILNG_DATE: string;
  BDB_CDB_C: number;
  BDB_CDB_DATE_C: string;
  BDB_CDB_USER_C: string;
  BDB_CDB_R: number;
  BDB_CDB_DATE_R: string;
  BDB_CDB_USER_R: string;
  CDB_HH_C: number;
  CDB_HH_DATE_C: string;
  CDB_HH_R: number;
  CDB_HH_DATE_R: string;
  HH_CDB_C: number;
  HH_CDB_R: number;
  CDB_BDB_C: number;
  CDB_BDB_DATE_C: string;
  CDB_BDB_USER_C: string;
  CDB_BDB_R: number;
  ISCYCLE_COMPLETED_C: number;
  ISCYCLE_COMPLETED_R: number;
  DEVICEID_R: string;
  DEVICEID_C: string;
  WALK_DESCRIPTION: string;
  BILNG_DESCRIPTION: string;
  IS_ALLOWED_C: boolean;
  IS_ALLOWED_R: boolean;
  IS_READY_C: boolean;
  IS_READY_R: boolean;
  COUNT_C: number;
  COUNT_R: number;
  EMPID_C: number;
  EMPID_R: number;
  ISSUED_AMOUNT: number;
  IS_CUSTOMER_BOOK: boolean;
  ALLOW_FAWRY: boolean;
  MARKETING: number;
  BILLS: [];
  READER: string;
  COLLECTOR: string;
  COUNT_CYCLES: number;
  ALL_BILL_DATE: boolean;
  Cycles: [];
  IS_ALLOWED_C_FRONT: boolean;
  IS_ALLOWED_R_FRONT: boolean;
};
