export const PermissionsScreens = [
  {
    name: "الخزنة",
    permissions: [
      { key: "treasury_admin", label: "أمين خزينة (الجلسات)" },
      { key: "edit_treasury", label: "تعديل الخزائن" },
      { key: "print_receipt", label: "إعادة طباعة إيصال (مصل مكتب)" },
      { key: "cancel_receipt", label: "إلغاء إيصال" },
      { key: "allow_print_taf", label: "السماح بطباعة إيصال تالف" },
      { key: "change_payment_method", label: "تغيير طريقة الدفع" },
      { key: "review_treasury", label: "مراجعة الخزائن" },
      { key: "close_session", label: "اغلاق جلسة الخزينة" },
    ],
  },
  {
    name: "BPM",
    permissions: [
      { key: "system_admin", label: "مدير النظام" },
      { key: "dashboard", label: "داشبورد" },
      { key: "formulas_expenses", label: "المعادلات والمصروفات" },
      { key: "orders_screen", label: "شاشة الطلبات" },
      { key: "reports_screen", label: "شاشة التقارير" },
      { key: "orders_reports", label: "تقارير الطلبات" },
      { key: "general_reports", label: "تقارير عامة" },
      { key: "cancel_order", label: "الغاء الطلب" },
    ],
  },
  {
    name: "AUTH",
    permissions: [
      { key: "add_users", label: "اضافة المستخدمين" },
      { key: "add_jobs", label: "اضافة الوظائف" },
      { key: "delete_jobs", label: "حذف الوظائف" },
      { key: "delete_user_linked_jobs", label: "حذف وظائف مرتبطه بمستخدمين" },
      { key: "delete_users", label: "حذف المستخدمين" },
      { key: "edit_users", label: "تعديل المستخدمين" },
      { key: "edit_jobs", label: "تعديل الوظائف" },
      { key: "departments", label: "الاقسام" },
      { key: "define_companies", label: "تعريف الشركات" },
    ],
  },
  {
    name: "BI",
    permissions: [
      { key: "issuance_reports", label: "تقارير (الاصدار)" },
      { key: "customer_service_reports", label: "تقارير (خدمة العملاء)" },
      { key: "crystal_user_reports", label: "تقارير المستخدم (Crystal)" },
      { key: "mas_reports", label: "تقارير (ماس)" },
      { key: "other_reports", label: "تقارير (اخرى)" },
      { key: "issuance_inquiries", label: "استعلامات الاصدار" },
      { key: "additional_customer_data", label: "بيانات العميل الاضافية" },
      { key: "crm_inquiries", label: "استعلامات CRM" },
      { key: "mas_inquiries", label: "استعلامات MAS" },
      { key: "tax_inquiries", label: "استعلامات TAX" },
      { key: "report_settings", label: "اعدادات التقارير" },
      { key: "statistics", label: "الاحصائيات" },
      { key: "bpm_stats", label: "احصائيات BPM" },
      { key: "mas_stats", label: "احصائيات MAS" },
      { key: "cdu_stats", label: "احصائيات CDU" },
      { key: "tax_stats", label: "احصائيات TAX" },
      { key: "issuance_stats", label: "احصائيات الاصدار" },
      { key: "view_customer_file", label: "عرض ملف العميل" },
      { key: "long_session", label: "LONG_SESSION" },
      { key: "collections_dashboard", label: "داش بورد التحصيلات" },
    ],
  },
  {
    name: "BILLER",
    permissions: [
      { key: "system_admin", label: "مدير النظام" },
      { key: "biller_main", label: "BILLER" },
      { key: "cancel_order", label: "الغاء الطلب" },
      { key: "close_order", label: "إغلاق الطلب" },
      { key: "create_order", label: "إنشاء الطلب" },
      { key: "clear_order", label: "مسح الطلب" },
      { key: "edit_order", label: "تعديل الطلب" },
      { key: "resend_invoice", label: "اعادة ارسال فاتورة" },
    ],
  },
  {
    name: "صلاحيات Cdu",
    permissions: [
      { key: "system_admin", label: "مدير النظام" },
      { key: "approval", label: "اعتماد" },
      { key: "session_approval", label: "اعتماد الجلسة" },
      { key: "committee", label: "لجنة" },
      { key: "dashboard", label: "داشبورد" },
      { key: "edit", label: "تعديل" },
      { key: "reports", label: "التقارير" },
      { key: "review", label: "مراجعة" },
      { key: "session_review", label: "مراجعة الجلسة" },
    ],
  },
  {
    name: "ماس",
    permissions: [
      { key: "aggregate_readings_est", label: "تقدير قراءات مجمع" },
      { key: "cancel_invoice_payment", label: "الغاء تحصيل فاتورة" },
      {
        key: "cancel_supplied_invoice_payment",
        label: "الغاء تحصيل فاتورة موردة",
      },
      { key: "invoice_collection", label: "تحصيل فاتورة" },
      { key: "customer_settlement", label: "تسوية بين العملاء" },
      { key: "supply", label: "التوريد" },
      { key: "individual_reading_est", label: "تقدير قراءات فردى" },
      {
        key: "disable_fawri_collection",
        label: "تعطيل التحصيل من خلال منافذ فورى",
      },
      {
        key: "allow_fawri_collection",
        label: "السماح بالتحصيل من خلال منافذ فورى",
      },
      { key: "inventory", label: "الجرد" },
      { key: "maps", label: "الخرائط" },
      { key: "edit_previous_reading", label: "تعديل قراءة سابقة" },
      { key: "edit_reading", label: "تعديل قراءة" },
      { key: "reprint_cancelled_invoice", label: "اعادة تحصيل فاتورة ملغاه" },
      {
        key: "individual_invoice_dashboard",
        label: "لوحة التحكم فواتير فردية",
      },
      { key: "biller_tag", label: "BILLER" },
      { key: "close_order_biller", label: "قفل طلب - biller" },
      { key: "cancel_order_biller", label: "الغاء طلب - biller" },
      { key: "create_order_biller", label: "انشاء طلب - biller" },
      { key: "delete_order_biller", label: "حذف طلب - biller" },
      { key: "edit_order_biller", label: "تعديل طلب - biller" },
      {
        key: "calc_individual_invoice_value",
        label: "احتساب قيمة الفواتير الفردية",
      },
      { key: "cancel_invoice", label: "الغاء فاتورة" },
      { key: "cancel_custody_handover", label: "الغاء تسليم عهدة" },
      { key: "treasury", label: "الخزينة" },
      {
        key: "close_collection_inventory_path",
        label: "اغلاق مسار التحصيل والجرد",
      },
      { key: "close_readings_path", label: "اغلاق مسار القراءات" },
      { key: "collection_supervisor", label: "مشرف تحصيل" },
      { key: "individual_invoice_entry", label: "ادخال تحصيل فاتورة فردية" },
      { key: "dashboard", label: "داشبورد" },
      { key: "data_management", label: "ادارة البيانات" },
      { key: "deleted_tag", label: "DELETED" },
      { key: "units_management", label: "ادارة الوحدات" },
      { key: "advanced_calculation_retry", label: "اعادة الاحتساب المطورة" },
      { key: "paths_status", label: "حالة المسارات" },
      { key: "office_collection", label: "التحصيل بالمكتب" },
      { key: "list_collection", label: "التحصيل باستخدام القائمة" },
      { key: "vandalism_locations", label: "مواقع التوصيلات الخلسة" },
      { key: "collection_locations", label: "مواقع التحصيل" },
      { key: "complaint_locations", label: "مواقع الشكاوى" },
      { key: "unit_locations", label: "مواقع الوحدات" },
      { key: "unit_tracking", label: "تتبع الوحدات" },
      { key: "reading_locations", label: "مواقع القراءات" },
      { key: "marketing", label: "التسويق" },
      { key: "partial_collection", label: "التحصيل الجزئى" },
      { key: "electronic_portal", label: "البوابة الالكترونية" },
      { key: "portfolio_preparation", label: "تجهيز الحافظة" },
      { key: "present_cancel_bill", label: "PRESENT_CANCEL_BILL" },
      {
        key: "individual_requirements_print",
        label: "طباعة المتطلبات الفردية",
      },
      { key: "inquiries", label: "الاستعلامات" },
      { key: "reading_supervisor", label: "مشرف قراءات" },
      {
        key: "update_invoice_customer_data",
        label: "تحديث بيانات الفواتير بالعميل",
      },
      {
        key: "update_group_invoice_data",
        label: "تحديث بيانات الفواتير بالمجموعة",
      },
      { key: "user_reports", label: "تقارير المستخدم" },
      { key: "reports", label: "التقارير" },
      { key: "resend_collection", label: "اعادة ارسال التحصيل" },
      { key: "resend_readings", label: "اعادة ارسال القراءات" },
      { key: "data_update", label: "تحديث البيانات" },
      { key: "custody_exchange", label: "تبديل عهدة" },
      { key: "sync", label: "التزامن" },
      { key: "system_maintenance", label: "صيانة النظام" },
      { key: "system_admin_alt", label: "ادارة النظام" },
      { key: "uflag", label: "UFLAG" },
      { key: "update_customer_locations", label: "تحديث مواقع العملاء" },
      { key: "user_management", label: "ادارة المستخدمين" },
      { key: "route_reorder", label: "ترحيل ترتيب المسارات" },
      {
        key: "close_collection_route_handheld",
        label: "اغلاق مسار للتحصيل على الوحدة المحمولة",
      },
      {
        key: "close_reading_route_handheld",
        label: "اغلاق مسار للقراءة على الوحدة المحمولة",
      },
      { key: "edamscs_requests", label: "(خاص بطلبات ايدامز) edamscs" },
      { key: "average_consumption_edit", label: "تعديل متوسط الاستهلاك" },
      { key: "route_reorder_retry", label: "اعادة ترتيب المسارات" },
      {
        key: "edit_broken_meter_status",
        label: "امكانية تعديل حالة العداد المعطلة",
      },
      { key: "tax_portal_upload", label: "الرفع لبوابة الضرائب" },
      { key: "reader_management", label: "ادراة الكشافين" },
      { key: "collection_route_assign", label: "تخصيص مسارات التحصيل" },
      { key: "reading_route_assign", label: "تخصيص مسارات القراءة" },
      { key: "calc_retry", label: "إعادة احتساب" },
      { key: "collection_route_migrate", label: "ترحيل التحصيل" },
      { key: "reading_route_migrate", label: "ترحيل القراءة" },
      { key: "reprint_damaged_receipt", label: "اعادة طباعة ايصال تالف" },
      { key: "add_delete_collection_routes", label: "اضافة وحذف مسارات تحصيل" },
      { key: "customer_notices", label: "اخطارات العملاء" },
      {
        key: "customer_notice_templates",
        label: "ادارة نماذج اخطارات العملاء",
      },
    ],
  },
  {
    name: "صلاحيات GOV",
    permissions: [
      { key: "gov_collection", label: "التحصيل الحكومي" },
      { key: "collection", label: "التحصيل" },
      { key: "add_collection_file", label: "اضافه ملف تحصيل" },
      { key: "edit_collection_file", label: "تعديل ملف تحصيل" },
      { key: "remove_collection_file", label: "ازاله ملف تحصيل" },
      { key: "add_collection_doc", label: "اضافه مستند تحصيل" },
      { key: "edit_collection_doc", label: "تعديل مستند تحصيل" },
      { key: "remove_collection_doc", label: "ازاله مستند تحصيل" },
      { key: "add_employee", label: "اضافة موظف" },
      { key: "edit_employee", label: "تعديل موظف" },
      { key: "cancel_collection", label: "الغاء التحصيل" },
      { key: "reports", label: "التقارير" },
      { key: "central_review", label: "مراجعة المركزية" },
      { key: "central_approval", label: "إعتماد المركزية" },
      { key: "central_delete", label: "حذف المركزية" },
      { key: "central_add", label: "اضافة المركزية" },
      { key: "central_reports", label: "تقارير المركزية" },
      { key: "add_amount_to_doc", label: "اضافة مبلغ جديد لمستند موجود" },
      {
        key: "redistribute_remaining_amount",
        label: "اعادة توزيع المبلغ المتبقى من المستند الرئيسي",
      },
      { key: "merge_items_in_one", label: "دمج جميع البنود في بند واحد" },
      {
        key: "merge_items_water_drain",
        label: "دمج جميع البنود في (مياه - صرف)",
      },
      { key: "auto_distribute_amount", label: "توزيع المبلغ على البنود آلي" },
    ],
  },
  {
    name: "صلاحيات TAX",
    permissions: [
      { key: "manage_products", label: "ادارة المنتجات" },
      { key: "manage_customers", label: "ادارة العملاء" },
      { key: "transfer_client_to_entity", label: "تحويل العميل لجهة" },
      { key: "main_entities", label: "الجهات الرئيسية" },
      { key: "branch_departments", label: "الادارات الفرعية" },
      { key: "approve_aggregated_invoices", label: "اعتماد الفواتير المجمعة" },
      { key: "aggregate_invoices_dept", label: "تجميع فواتير ادارات" },
      { key: "add_customer_to_dept", label: "اضافة عملاء داخل الادارة" },
      { key: "manage_invoices_in_dept", label: "ادارة الفواتير داخل الادارة" },
      { key: "cancel_aggregate_invoices", label: "الغاء تجميع الفواتير" },
      {
        key: "approve_aggregated_invoices_dept",
        label: "اعتماد الفواتير المجمعة لادارة",
      },
      { key: "tax_types", label: "انواع الضرائب" },
      { key: "activities", label: "الانشطة" },
      { key: "program_reports", label: "تقارير البرنامج" },
      { key: "other_reports", label: "تقارير اخرى" },
      { key: "accept_purchases", label: "قبول المشتريات" },
      { key: "reject_purchases", label: "رفض المشتريات" },
      { key: "create_invoice", label: "انشاء فاتورة" },
      { key: "upload_invoice_group", label: "رفع مجموعة فواتير" },
      { key: "draft_invoices", label: "فواتير المسودة" },
      { key: "approve_draft_invoices", label: "اعتماد فواتير المسودة" },
      { key: "review_invoices", label: "مراجعة الفواتير" },
      { key: "approve_invoices", label: "اعتماد الفواتير" },
      { key: "sent_invoices", label: "الفواتير المرسلة" },
      { key: "print_from_program", label: "طباعة من البرنامج" },
      { key: "print_from_tax_portal", label: "طباعة من بوابة الضرائب" },
    ],
  },
];
