import z from "zod";

export const ScoutesSchema = z.object({
  ID: z.number(),
  FULL_NAME: z.string().min(1, "برجاء ادخال اسم الكشاف"),
  BRANCH_ID: z.string().optional(),
  DEVICE_ID: z.string().optional(),
  READING: z.boolean().optional(),
  usercode: z.string().optional(),
  type: z.string().optional(),
  mobile1: z.string().optional(),
  mobile2: z.string().optional(),
  portalPhones: z.string().optional(),
  username: z.string().optional(),
  password: z.string().optional(),
  address: z.string().optional(),
  allowCancel: z.boolean().optional(),
  allowModifyReading: z.boolean().optional(),
  allowOverPayment: z.boolean().optional(),
  billsCountAllowedOffline: z.boolean().optional(),
  bilngEmpId: z.string().optional(),
  casher: z.string().optional(),
  closeCollectionCycle: z.boolean().optional(),
  closeReadingCycle: z.boolean().optional(),
  collection: z.string().optional(),
  dashboard: z.string().optional(),
  dataAdmin: z.string().optional(),
  dataEntry: z.string().optional(),
  dayReadingPercent: z.string().optional(),
  depositDuration: z.string().optional(),
  depositDurationExtraDays: z.string().optional(),
  deposits_qouta: z.string().optional(),
  dirCollection: z.string().optional(),
  disabled: z.boolean().optional(),
  email: z.string().optional(),
  empType: z.string().optional(),
  enableHhPrinting: z.boolean().optional(),
  flage1: z.boolean().optional(),
  flage2: z.boolean().optional(),
  isStoreMan: z.boolean().optional(),
  keeper: z.string().optional(),
  marketing: z.string().optional(),
  nid: z.string().optional(),
  notes: z.string().optional(),
  offlinePeriod: z.string().optional(),
  originalStation: z.string().optional(),
  partialCollectionState: z.string().optional(),
  quota: z.string().optional(),
  randomlyMeterPicturePercentage: z.string().optional(),
  readinPercent: z.string().optional(),
  reading: z.boolean().optional(),
  readingEstimPercent: z.string().optional(),
  reportingViewer: z.string().optional(),
  station_name: z.string().optional(),
  sysAdmin: z.string().optional(),
  tel: z.string().optional(),

  value1: z.string().optional(),
  value2: z.string().optional(),
});
