export interface HHBCYC {
  BOOK_NO: string;
  WALK_NO: string;
  CYCLE_ID: number;
  IS_COLLECTION: boolean;
  IS_READING: boolean;
  STATION_NO: number | null;
  BRANCH: string;
  BILLGROUP: string;
  BILNG_DATE: string | null;
  BDB_CDB_C: number | null;
  BDB_CDB_DATE_C: string | null;
  BDB_CDB_USER_C: string;
  BDB_CDB_R: number | null;
  BDB_CDB_DATE_R: string | null;
  BDB_CDB_USER_R: string;
  CDB_HH_R: number | null;
  CDB_HH_DATE_R: string | null;
  CDB_HH_USER_R: string;
  CDB_HH_C: number | null;
  CDB_HH_DATE_C: string | null;
  CDB_HH_USER_C: string;
  HH_CDB_C: number | null;
  HH_CDB_DATE_C: string | null;
  HH_CDB_USER_C: string;
  HH_CDB_R: number | null;
  HH_CDB_DATE_R: string | null;
  HH_CDB_USER_R: string;
  CDB_BDB_R: number | null;
  CDB_BDB_DATE_R: string | null;
  CDB_BDB_USER_R: string;
  CDB_BDB_C: number | null;
  CDB_BDB_DATE_C: string | null;
  CDB_BDB_USER_C: string;
  ISCYCLE_COMPLETED_C: number | null;
  ISCYCLE_COMPLETED_R: number | null;
  CLOSE_DATE_C: string | null;
  CLOSE_BY_C: string;
  CLOSE_DATE_R: string | null;
  CLOSE_BY_R: string;
  DEVICEID_C: string;
  DEVICEID_R: string;
  EMPID_C: number | null;
  EMPID_R: number | null;
  COUNT_C: number | null;
  COUNT_R: number | null;
  CL_BLNCE: number | null;
  DESCRIPTION: string;
  IS_ALLOWED_C: boolean | null;
  IS_ALLOWED_R: boolean | null;
  COLLECTED_AMOUNT: number | null;
  COLLECTED_COUNT: number | null;
  READED_COUNT: number | null;
  REACHED_C: number | null;
  REACHED_R: number | null;
  POSTED_C: number | null;
  POSTED_R: number | null;
  IS_METER_WALK: boolean | null;
  IS_CUSTOMER_WALK: boolean | null;
  ISCLOSED_INDEVICE_C: boolean | null;
  ISCLOSED_INDEVICE_R: boolean | null;
  CLOSE_INDEVICE_DATE_R: string | null;
  CLOSE_INDEVICE_DATE_C: string | null;
  CLOSE_INDEVICE_COLLECTED: number | null;
  CLOSE_INDEVICE_READED: number | null;
  IS_REVIRSE_C: boolean | null;
  IS_REVIRSE_R: boolean | null;
  IS_NOTIFIED: boolean | null;
  NOTIFICATION_DATE: string | null;
  LAT_MIN: number | null;
  LAT_MAX: number | null;
  LNG_MIN: number | null;
  LNG_MAX: number | null;
  APPLY_REF: number | null;
  CLIENT_VERSION: string;
  NEXT_SEQ: number | null;
  CLOSE_INDEVICE_BY_C: string;
  CLOSE_INDEVICE_BY_R: string;
  GARD: boolean | null;
  GARD_OK: boolean | null;
  GARD_START_DATE: string | null;
  GARD_END_DATE: string | null;
  GARD_BY: string;
  EDAMS_CYCLE_C: boolean | null;
  EDAMS_CYCLE_R: boolean | null;
  ERROR_MESSAGE: string;
  SECTOR_CODE: number | null;
  IS_BILL_PREPEARED: boolean | null;
  PREV_OWNER_C: number | null;
  TRANSFEER_DATE_C: string | null;
  PREV_OWNER_R: number | null;
  TRANSFEER_DATE_R: string | null;
  ALLOW_FAWRY: number | null;
  FAWRY_OPEN_BY: string;
  FAWRY_CLOSE_BY: string;
  FAWRY_OPEN_DATE: string | null;
  FAWRY_CLOSE_DATE: string | null;
  IS_HH_PRINTING: boolean | null;
  PORTAL_READING_START: string | null;
  PORTAL_READING_END: string | null;
}
export interface BCYCREQ {
  deviceid: string;
  empid?: number;
}
