// @generated by protobuf-ts 2.9.4 with parameter use_proto_field_name,add_pb_suffix,force_optimize_code_size,ts_nocheck,long_type_string
// @generated from protobuf file "bi.proto" (package "mashh", syntax proto3)
// tslint:disable
// @ts-nocheck
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { mashh_bi } from "./bi_pb";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GardResponse } from "./bi_pb";
import type { GardRequest } from "./bi_pb";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service mashh.mashh_bi
 */
export interface Imashh_biClient {
    /**
     * @generated from protobuf rpc: GetGovGard(mashh.GardRequest) returns (mashh.GardResponse);
     */
    getGovGard(input: GardRequest, options?: RpcOptions): UnaryCall<GardRequest, GardResponse>;
}
/**
 * @generated from protobuf service mashh.mashh_bi
 */
export class mashh_biClient implements Imashh_biClient, ServiceInfo {
    typeName = mashh_bi.typeName;
    methods = mashh_bi.methods;
    options = mashh_bi.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetGovGard(mashh.GardRequest) returns (mashh.GardResponse);
     */
    getGovGard(input: GardRequest, options?: RpcOptions): UnaryCall<GardRequest, GardResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GardRequest, GardResponse>("unary", this._transport, method, opt, input);
    }
}
