// @generated by protobuf-ts 2.9.4 with parameter use_proto_field_name,add_pb_suffix,force_optimize_code_size,ts_nocheck,long_type_string
// @generated from protobuf file "biller_service.proto" (package "billing", syntax proto2)
// tslint:disable
// @ts-nocheck
import { LoginService } from "./biller_service_pb";
import { Engine } from "./biller_service_pb";
import { BillingDataCousumer } from "./biller_service_pb";
import type { PostMessage } from "./biller_service_pb";
import { BillingDataProvider } from "./biller_service_pb";
import type { LoginResponce } from "./biller_service_pb";
import type { LoginRequest } from "./biller_service_pb";
import type { GetBillRequest } from "./biller_service_pb";
import type { CtgsResponce } from "./biller_service_pb";
import type { LookUpsResponce } from "./biller_service_pb";
import type { Entity } from "./biller_service_pb";
import type { CustomersList } from "./biller_service_pb";
import type { Customer } from "./biller_service_pb";
import type { Key } from "./biller_service_pb";
import { BillingTariffProvider } from "./biller_service_pb";
import type { RegularRelationValues } from "./biller_service_pb";
import type { ArrRegularRelationValues } from "./biller_service_pb";
import type { RegularRelationEntity } from "./biller_service_pb";
import type { ArrRegularRelationEntity } from "./biller_service_pb";
import type { RegularChargeReq } from "./biller_service_pb";
import type { RegularCharge } from "./biller_service_pb";
import type { RegularChargeInfo } from "./biller_service_pb";
import type { RegularChargeIdReq } from "./biller_service_pb";
import type { RegularChargeRequest } from "./biller_service_pb";
import type { TariffExtraFees } from "./biller_service_pb";
import type { ArrTariffExtraFees } from "./biller_service_pb";
import type { TariffBands } from "./biller_service_pb";
import type { ArrTariffBands } from "./biller_service_pb";
import type { TariffIdReq } from "./biller_service_pb";
import type { TariffsDataRes } from "./biller_service_pb";
import type { TariffCodeReq } from "./biller_service_pb";
import type { TariffsData } from "./biller_service_pb";
import type { Tariffs } from "./biller_service_pb";
import type { ArrTariffs } from "./biller_service_pb";
import type { CTGConsumptionServiceTariff } from "./biller_service_pb";
import type { ArrCTGConsumptionServiceTariff } from "./biller_service_pb";
import type { TransCodesRes } from "./biller_service_pb";
import type { GET_CHARGEREGULARCALCSTRATEGY } from "./biller_service_pb";
import type { GET_ENTITYTYPES } from "./biller_service_pb";
import type { GET_CHARGETYPES } from "./biller_service_pb";
import type { GET_SERVICETYPES } from "./biller_service_pb";
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo as ServiceInfo$ } from "@protobuf-ts/runtime-rpc";
import { BillingChargeService } from "./biller_service_pb";
import type { SetupData } from "./biller_service_pb";
import type { BillResponce } from "./biller_service_pb";
import type { ChargeRequest } from "./biller_service_pb";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "./biller_service_pb";
import type { Empty } from "./biller_service_pb";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
// /////////////////////////PROVIDER///////////////////////

/**
 * @generated from protobuf service billing.BillingChargeService
 */
export interface IBillingChargeServiceClient {
    /**
     * @generated from protobuf rpc: Info(billing.Empty) returns (billing.ServiceInfo);
     */
    info(input: Empty, options?: RpcOptions): UnaryCall<Empty, ServiceInfo>;
    /**
     * @generated from protobuf rpc: Charge(billing.ChargeRequest) returns (billing.BillResponce);
     */
    charge(input: ChargeRequest, options?: RpcOptions): UnaryCall<ChargeRequest, BillResponce>;
    /**
     * @generated from protobuf rpc: Setup(billing.SetupData) returns (billing.Empty);
     */
    setup(input: SetupData, options?: RpcOptions): UnaryCall<SetupData, Empty>;
}
// /////////////////////////PROVIDER///////////////////////

/**
 * @generated from protobuf service billing.BillingChargeService
 */
export class BillingChargeServiceClient implements IBillingChargeServiceClient, ServiceInfo$ {
    typeName = BillingChargeService.typeName;
    methods = BillingChargeService.methods;
    options = BillingChargeService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Info(billing.Empty) returns (billing.ServiceInfo);
     */
    info(input: Empty, options?: RpcOptions): UnaryCall<Empty, ServiceInfo> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, ServiceInfo>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Charge(billing.ChargeRequest) returns (billing.BillResponce);
     */
    charge(input: ChargeRequest, options?: RpcOptions): UnaryCall<ChargeRequest, BillResponce> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ChargeRequest, BillResponce>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Setup(billing.SetupData) returns (billing.Empty);
     */
    setup(input: SetupData, options?: RpcOptions): UnaryCall<SetupData, Empty> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetupData, Empty>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service billing.BillingTariffProvider
 */
export interface IBillingTariffProviderClient {
    /**
     * @generated from protobuf rpc: Info(billing.Empty) returns (billing.ServiceInfo);
     */
    info(input: Empty, options?: RpcOptions): UnaryCall<Empty, ServiceInfo>;
    /**
     * @generated from protobuf rpc: GetSetupData(billing.Empty) returns (billing.SetupData);
     */
    getSetupData(input: Empty, options?: RpcOptions): UnaryCall<Empty, SetupData>;
    /**
     * enums
     *
     * @generated from protobuf rpc: GetServiceTypes(billing.Empty) returns (billing.GET_SERVICETYPES);
     */
    getServiceTypes(input: Empty, options?: RpcOptions): UnaryCall<Empty, GET_SERVICETYPES>;
    /**
     * @generated from protobuf rpc: GetChargeTypes(billing.Empty) returns (billing.GET_CHARGETYPES);
     */
    getChargeTypes(input: Empty, options?: RpcOptions): UnaryCall<Empty, GET_CHARGETYPES>;
    /**
     * @generated from protobuf rpc: GetEntityTypes(billing.Empty) returns (billing.GET_ENTITYTYPES);
     */
    getEntityTypes(input: Empty, options?: RpcOptions): UnaryCall<Empty, GET_ENTITYTYPES>;
    /**
     * @generated from protobuf rpc: GetChargeRegularCalcStrategy(billing.Empty) returns (billing.GET_CHARGEREGULARCALCSTRATEGY);
     */
    getChargeRegularCalcStrategy(input: Empty, options?: RpcOptions): UnaryCall<Empty, GET_CHARGEREGULARCALCSTRATEGY>;
    /**
     * @generated from protobuf rpc: GetTransCodes(billing.Empty) returns (billing.TransCodesRes);
     */
    getTransCodes(input: Empty, options?: RpcOptions): UnaryCall<Empty, TransCodesRes>;
    /**
     * CTGConsumptionServiceTariff RPCs
     *
     * @generated from protobuf rpc: GetAllCTGConsumptionServiceTariffs(billing.Empty) returns (billing.ArrCTGConsumptionServiceTariff);
     */
    getAllCTGConsumptionServiceTariffs(input: Empty, options?: RpcOptions): UnaryCall<Empty, ArrCTGConsumptionServiceTariff>;
    /**
     * @generated from protobuf rpc: SaveCTGConsumptionServiceTariff(billing.CTGConsumptionServiceTariff) returns (billing.Empty);
     */
    saveCTGConsumptionServiceTariff(input: CTGConsumptionServiceTariff, options?: RpcOptions): UnaryCall<CTGConsumptionServiceTariff, Empty>;
    /**
     * Tariffs RPCs
     *
     * @generated from protobuf rpc: GetAllTariffs(billing.Empty) returns (billing.ArrTariffs);
     */
    getAllTariffs(input: Empty, options?: RpcOptions): UnaryCall<Empty, ArrTariffs>;
    /**
     * @generated from protobuf rpc: SaveTariffs(billing.Tariffs) returns (billing.Tariffs);
     */
    saveTariffs(input: Tariffs, options?: RpcOptions): UnaryCall<Tariffs, Tariffs>;
    /**
     * @generated from protobuf rpc: SaveTariffsData(billing.TariffsData) returns (billing.Empty);
     */
    saveTariffsData(input: TariffsData, options?: RpcOptions): UnaryCall<TariffsData, Empty>;
    /**
     * @generated from protobuf rpc: GetTariffCodeHistory(billing.TariffCodeReq) returns (billing.TariffsDataRes);
     */
    getTariffCodeHistory(input: TariffCodeReq, options?: RpcOptions): UnaryCall<TariffCodeReq, TariffsDataRes>;
    /**
     * TariffBands RPCs
     *
     * @generated from protobuf rpc: GetAllTariffBands(billing.TariffIdReq) returns (billing.ArrTariffBands);
     */
    getAllTariffBands(input: TariffIdReq, options?: RpcOptions): UnaryCall<TariffIdReq, ArrTariffBands>;
    /**
     * @generated from protobuf rpc: SaveTariffBands(billing.TariffBands) returns (billing.Empty);
     */
    saveTariffBands(input: TariffBands, options?: RpcOptions): UnaryCall<TariffBands, Empty>;
    /**
     * TariffExtraFees RPCs
     *
     * @generated from protobuf rpc: GetAllTariffExtraFees(billing.TariffIdReq) returns (billing.ArrTariffExtraFees);
     */
    getAllTariffExtraFees(input: TariffIdReq, options?: RpcOptions): UnaryCall<TariffIdReq, ArrTariffExtraFees>;
    /**
     * @generated from protobuf rpc: SaveTariffExtraFees(billing.TariffExtraFees) returns (billing.Empty);
     */
    saveTariffExtraFees(input: TariffExtraFees, options?: RpcOptions): UnaryCall<TariffExtraFees, Empty>;
    /**
     * RegularCharges RPCs
     *
     * @generated from protobuf rpc: GetAllRegularCharges(billing.Empty) returns (billing.RegularChargeRequest);
     */
    getAllRegularCharges(input: Empty, options?: RpcOptions): UnaryCall<Empty, RegularChargeRequest>;
    /**
     * @generated from protobuf rpc: GetRegularChargeInfo(billing.RegularChargeIdReq) returns (billing.RegularChargeInfo);
     */
    getRegularChargeInfo(input: RegularChargeIdReq, options?: RpcOptions): UnaryCall<RegularChargeIdReq, RegularChargeInfo>;
    /**
     * @generated from protobuf rpc: SaveRegularCharges(billing.RegularCharge) returns (billing.Empty);
     */
    saveRegularCharges(input: RegularCharge, options?: RpcOptions): UnaryCall<RegularCharge, Empty>;
    /**
     * RegularRelationEntity RPCs
     *
     * @generated from protobuf rpc: GetAllRegularRelationEntity(billing.RegularChargeReq) returns (billing.ArrRegularRelationEntity);
     */
    getAllRegularRelationEntity(input: RegularChargeReq, options?: RpcOptions): UnaryCall<RegularChargeReq, ArrRegularRelationEntity>;
    /**
     * @generated from protobuf rpc: SaveRegularRelationEntity(billing.RegularRelationEntity) returns (billing.Empty);
     */
    saveRegularRelationEntity(input: RegularRelationEntity, options?: RpcOptions): UnaryCall<RegularRelationEntity, Empty>;
    /**
     * RegularRelationValues RPCs
     *
     * @generated from protobuf rpc: GetAllRegularRelationValues(billing.RegularChargeReq) returns (billing.ArrRegularRelationValues);
     */
    getAllRegularRelationValues(input: RegularChargeReq, options?: RpcOptions): UnaryCall<RegularChargeReq, ArrRegularRelationValues>;
    /**
     * @generated from protobuf rpc: SaveRegularRelationValues(billing.RegularRelationValues) returns (billing.Empty);
     */
    saveRegularRelationValues(input: RegularRelationValues, options?: RpcOptions): UnaryCall<RegularRelationValues, Empty>;
}
/**
 * @generated from protobuf service billing.BillingTariffProvider
 */
export class BillingTariffProviderClient implements IBillingTariffProviderClient, ServiceInfo$ {
    typeName = BillingTariffProvider.typeName;
    methods = BillingTariffProvider.methods;
    options = BillingTariffProvider.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Info(billing.Empty) returns (billing.ServiceInfo);
     */
    info(input: Empty, options?: RpcOptions): UnaryCall<Empty, ServiceInfo> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, ServiceInfo>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetSetupData(billing.Empty) returns (billing.SetupData);
     */
    getSetupData(input: Empty, options?: RpcOptions): UnaryCall<Empty, SetupData> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, SetupData>("unary", this._transport, method, opt, input);
    }
    /**
     * enums
     *
     * @generated from protobuf rpc: GetServiceTypes(billing.Empty) returns (billing.GET_SERVICETYPES);
     */
    getServiceTypes(input: Empty, options?: RpcOptions): UnaryCall<Empty, GET_SERVICETYPES> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, GET_SERVICETYPES>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetChargeTypes(billing.Empty) returns (billing.GET_CHARGETYPES);
     */
    getChargeTypes(input: Empty, options?: RpcOptions): UnaryCall<Empty, GET_CHARGETYPES> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, GET_CHARGETYPES>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetEntityTypes(billing.Empty) returns (billing.GET_ENTITYTYPES);
     */
    getEntityTypes(input: Empty, options?: RpcOptions): UnaryCall<Empty, GET_ENTITYTYPES> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, GET_ENTITYTYPES>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetChargeRegularCalcStrategy(billing.Empty) returns (billing.GET_CHARGEREGULARCALCSTRATEGY);
     */
    getChargeRegularCalcStrategy(input: Empty, options?: RpcOptions): UnaryCall<Empty, GET_CHARGEREGULARCALCSTRATEGY> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, GET_CHARGEREGULARCALCSTRATEGY>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetTransCodes(billing.Empty) returns (billing.TransCodesRes);
     */
    getTransCodes(input: Empty, options?: RpcOptions): UnaryCall<Empty, TransCodesRes> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, TransCodesRes>("unary", this._transport, method, opt, input);
    }
    /**
     * CTGConsumptionServiceTariff RPCs
     *
     * @generated from protobuf rpc: GetAllCTGConsumptionServiceTariffs(billing.Empty) returns (billing.ArrCTGConsumptionServiceTariff);
     */
    getAllCTGConsumptionServiceTariffs(input: Empty, options?: RpcOptions): UnaryCall<Empty, ArrCTGConsumptionServiceTariff> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, ArrCTGConsumptionServiceTariff>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SaveCTGConsumptionServiceTariff(billing.CTGConsumptionServiceTariff) returns (billing.Empty);
     */
    saveCTGConsumptionServiceTariff(input: CTGConsumptionServiceTariff, options?: RpcOptions): UnaryCall<CTGConsumptionServiceTariff, Empty> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<CTGConsumptionServiceTariff, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * Tariffs RPCs
     *
     * @generated from protobuf rpc: GetAllTariffs(billing.Empty) returns (billing.ArrTariffs);
     */
    getAllTariffs(input: Empty, options?: RpcOptions): UnaryCall<Empty, ArrTariffs> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, ArrTariffs>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SaveTariffs(billing.Tariffs) returns (billing.Tariffs);
     */
    saveTariffs(input: Tariffs, options?: RpcOptions): UnaryCall<Tariffs, Tariffs> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<Tariffs, Tariffs>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SaveTariffsData(billing.TariffsData) returns (billing.Empty);
     */
    saveTariffsData(input: TariffsData, options?: RpcOptions): UnaryCall<TariffsData, Empty> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<TariffsData, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetTariffCodeHistory(billing.TariffCodeReq) returns (billing.TariffsDataRes);
     */
    getTariffCodeHistory(input: TariffCodeReq, options?: RpcOptions): UnaryCall<TariffCodeReq, TariffsDataRes> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return stackIntercept<TariffCodeReq, TariffsDataRes>("unary", this._transport, method, opt, input);
    }
    /**
     * TariffBands RPCs
     *
     * @generated from protobuf rpc: GetAllTariffBands(billing.TariffIdReq) returns (billing.ArrTariffBands);
     */
    getAllTariffBands(input: TariffIdReq, options?: RpcOptions): UnaryCall<TariffIdReq, ArrTariffBands> {
        const method = this.methods[13], opt = this._transport.mergeOptions(options);
        return stackIntercept<TariffIdReq, ArrTariffBands>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SaveTariffBands(billing.TariffBands) returns (billing.Empty);
     */
    saveTariffBands(input: TariffBands, options?: RpcOptions): UnaryCall<TariffBands, Empty> {
        const method = this.methods[14], opt = this._transport.mergeOptions(options);
        return stackIntercept<TariffBands, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * TariffExtraFees RPCs
     *
     * @generated from protobuf rpc: GetAllTariffExtraFees(billing.TariffIdReq) returns (billing.ArrTariffExtraFees);
     */
    getAllTariffExtraFees(input: TariffIdReq, options?: RpcOptions): UnaryCall<TariffIdReq, ArrTariffExtraFees> {
        const method = this.methods[15], opt = this._transport.mergeOptions(options);
        return stackIntercept<TariffIdReq, ArrTariffExtraFees>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SaveTariffExtraFees(billing.TariffExtraFees) returns (billing.Empty);
     */
    saveTariffExtraFees(input: TariffExtraFees, options?: RpcOptions): UnaryCall<TariffExtraFees, Empty> {
        const method = this.methods[16], opt = this._transport.mergeOptions(options);
        return stackIntercept<TariffExtraFees, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * RegularCharges RPCs
     *
     * @generated from protobuf rpc: GetAllRegularCharges(billing.Empty) returns (billing.RegularChargeRequest);
     */
    getAllRegularCharges(input: Empty, options?: RpcOptions): UnaryCall<Empty, RegularChargeRequest> {
        const method = this.methods[17], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, RegularChargeRequest>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetRegularChargeInfo(billing.RegularChargeIdReq) returns (billing.RegularChargeInfo);
     */
    getRegularChargeInfo(input: RegularChargeIdReq, options?: RpcOptions): UnaryCall<RegularChargeIdReq, RegularChargeInfo> {
        const method = this.methods[18], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegularChargeIdReq, RegularChargeInfo>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SaveRegularCharges(billing.RegularCharge) returns (billing.Empty);
     */
    saveRegularCharges(input: RegularCharge, options?: RpcOptions): UnaryCall<RegularCharge, Empty> {
        const method = this.methods[19], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegularCharge, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * RegularRelationEntity RPCs
     *
     * @generated from protobuf rpc: GetAllRegularRelationEntity(billing.RegularChargeReq) returns (billing.ArrRegularRelationEntity);
     */
    getAllRegularRelationEntity(input: RegularChargeReq, options?: RpcOptions): UnaryCall<RegularChargeReq, ArrRegularRelationEntity> {
        const method = this.methods[20], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegularChargeReq, ArrRegularRelationEntity>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SaveRegularRelationEntity(billing.RegularRelationEntity) returns (billing.Empty);
     */
    saveRegularRelationEntity(input: RegularRelationEntity, options?: RpcOptions): UnaryCall<RegularRelationEntity, Empty> {
        const method = this.methods[21], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegularRelationEntity, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * RegularRelationValues RPCs
     *
     * @generated from protobuf rpc: GetAllRegularRelationValues(billing.RegularChargeReq) returns (billing.ArrRegularRelationValues);
     */
    getAllRegularRelationValues(input: RegularChargeReq, options?: RpcOptions): UnaryCall<RegularChargeReq, ArrRegularRelationValues> {
        const method = this.methods[22], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegularChargeReq, ArrRegularRelationValues>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SaveRegularRelationValues(billing.RegularRelationValues) returns (billing.Empty);
     */
    saveRegularRelationValues(input: RegularRelationValues, options?: RpcOptions): UnaryCall<RegularRelationValues, Empty> {
        const method = this.methods[23], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegularRelationValues, Empty>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service billing.BillingDataProvider
 */
export interface IBillingDataProviderClient {
    /**
     * @generated from protobuf rpc: Info(billing.Empty) returns (billing.ServiceInfo);
     */
    info(input: Empty, options?: RpcOptions): UnaryCall<Empty, ServiceInfo>;
    /**
     * @generated from protobuf rpc: GetCustomerByCustkey(billing.Key) returns (billing.Customer);
     */
    getCustomerByCustkey(input: Key, options?: RpcOptions): UnaryCall<Key, Customer>;
    /**
     * @generated from protobuf rpc: GetCustomersByBillgroup(billing.Key) returns (billing.CustomersList);
     */
    getCustomersByBillgroup(input: Key, options?: RpcOptions): UnaryCall<Key, CustomersList>;
    /**
     * @generated from protobuf rpc: GetLoockup(billing.Entity) returns (billing.LookUpsResponce);
     */
    getLoockup(input: Entity, options?: RpcOptions): UnaryCall<Entity, LookUpsResponce>;
    /**
     * @generated from protobuf rpc: GetCtgs(billing.Empty) returns (billing.CtgsResponce);
     */
    getCtgs(input: Empty, options?: RpcOptions): UnaryCall<Empty, CtgsResponce>;
    /**
     * @generated from protobuf rpc: GetBillsByCustkey(billing.GetBillRequest) returns (billing.BillResponce);
     */
    getBillsByCustkey(input: GetBillRequest, options?: RpcOptions): UnaryCall<GetBillRequest, BillResponce>;
    /**
     * @generated from protobuf rpc: GetBillsByFormNo(billing.GetBillRequest) returns (billing.BillResponce);
     */
    getBillsByFormNo(input: GetBillRequest, options?: RpcOptions): UnaryCall<GetBillRequest, BillResponce>;
    /**
     * @generated from protobuf rpc: Login(billing.LoginRequest) returns (billing.LoginResponce);
     */
    login(input: LoginRequest, options?: RpcOptions): UnaryCall<LoginRequest, LoginResponce>;
}
/**
 * @generated from protobuf service billing.BillingDataProvider
 */
export class BillingDataProviderClient implements IBillingDataProviderClient, ServiceInfo$ {
    typeName = BillingDataProvider.typeName;
    methods = BillingDataProvider.methods;
    options = BillingDataProvider.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Info(billing.Empty) returns (billing.ServiceInfo);
     */
    info(input: Empty, options?: RpcOptions): UnaryCall<Empty, ServiceInfo> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, ServiceInfo>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCustomerByCustkey(billing.Key) returns (billing.Customer);
     */
    getCustomerByCustkey(input: Key, options?: RpcOptions): UnaryCall<Key, Customer> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<Key, Customer>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCustomersByBillgroup(billing.Key) returns (billing.CustomersList);
     */
    getCustomersByBillgroup(input: Key, options?: RpcOptions): UnaryCall<Key, CustomersList> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<Key, CustomersList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetLoockup(billing.Entity) returns (billing.LookUpsResponce);
     */
    getLoockup(input: Entity, options?: RpcOptions): UnaryCall<Entity, LookUpsResponce> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<Entity, LookUpsResponce>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCtgs(billing.Empty) returns (billing.CtgsResponce);
     */
    getCtgs(input: Empty, options?: RpcOptions): UnaryCall<Empty, CtgsResponce> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, CtgsResponce>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetBillsByCustkey(billing.GetBillRequest) returns (billing.BillResponce);
     */
    getBillsByCustkey(input: GetBillRequest, options?: RpcOptions): UnaryCall<GetBillRequest, BillResponce> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetBillRequest, BillResponce>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetBillsByFormNo(billing.GetBillRequest) returns (billing.BillResponce);
     */
    getBillsByFormNo(input: GetBillRequest, options?: RpcOptions): UnaryCall<GetBillRequest, BillResponce> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetBillRequest, BillResponce>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Login(billing.LoginRequest) returns (billing.LoginResponce);
     */
    login(input: LoginRequest, options?: RpcOptions): UnaryCall<LoginRequest, LoginResponce> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<LoginRequest, LoginResponce>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service billing.BillingDataCousumer
 */
export interface IBillingDataCousumerClient {
    /**
     * @generated from protobuf rpc: Info(billing.Empty) returns (billing.ServiceInfo);
     */
    info(input: Empty, options?: RpcOptions): UnaryCall<Empty, ServiceInfo>;
    /**
     * @generated from protobuf rpc: WriteFinantialData(billing.PostMessage) returns (billing.Empty);
     */
    writeFinantialData(input: PostMessage, options?: RpcOptions): UnaryCall<PostMessage, Empty>;
    /**
     * @generated from protobuf rpc: WriteFinantialDataOne(billing.PostMessage) returns (billing.Empty);
     */
    writeFinantialDataOne(input: PostMessage, options?: RpcOptions): UnaryCall<PostMessage, Empty>;
}
/**
 * @generated from protobuf service billing.BillingDataCousumer
 */
export class BillingDataCousumerClient implements IBillingDataCousumerClient, ServiceInfo$ {
    typeName = BillingDataCousumer.typeName;
    methods = BillingDataCousumer.methods;
    options = BillingDataCousumer.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Info(billing.Empty) returns (billing.ServiceInfo);
     */
    info(input: Empty, options?: RpcOptions): UnaryCall<Empty, ServiceInfo> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, ServiceInfo>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: WriteFinantialData(billing.PostMessage) returns (billing.Empty);
     */
    writeFinantialData(input: PostMessage, options?: RpcOptions): UnaryCall<PostMessage, Empty> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<PostMessage, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: WriteFinantialDataOne(billing.PostMessage) returns (billing.Empty);
     */
    writeFinantialDataOne(input: PostMessage, options?: RpcOptions): UnaryCall<PostMessage, Empty> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<PostMessage, Empty>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service billing.Engine
 */
export interface IEngineClient {
    /**
     * @generated from protobuf rpc: Info(billing.Empty) returns (billing.ServiceInfo);
     */
    info(input: Empty, options?: RpcOptions): UnaryCall<Empty, ServiceInfo>;
    /**
     * @generated from protobuf rpc: Calulate(billing.ChargeRequest) returns (billing.BillResponce);
     */
    calulate(input: ChargeRequest, options?: RpcOptions): UnaryCall<ChargeRequest, BillResponce>;
    /**
     * @generated from protobuf rpc: Post(billing.PostMessage) returns (billing.Empty);
     */
    post(input: PostMessage, options?: RpcOptions): UnaryCall<PostMessage, Empty>;
    /**
     * @generated from protobuf rpc: PostOne(billing.PostMessage) returns (billing.Empty);
     */
    postOne(input: PostMessage, options?: RpcOptions): UnaryCall<PostMessage, Empty>;
    /**
     * @generated from protobuf rpc: GetCustomerByCustkey(billing.Key) returns (billing.Customer);
     */
    getCustomerByCustkey(input: Key, options?: RpcOptions): UnaryCall<Key, Customer>;
    /**
     * @generated from protobuf rpc: GetLoockup(billing.Entity) returns (billing.LookUpsResponce);
     */
    getLoockup(input: Entity, options?: RpcOptions): UnaryCall<Entity, LookUpsResponce>;
    /**
     * @generated from protobuf rpc: GetCtgs(billing.Empty) returns (billing.CtgsResponce);
     */
    getCtgs(input: Empty, options?: RpcOptions): UnaryCall<Empty, CtgsResponce>;
    /**
     * @generated from protobuf rpc: GetBillsByCustkey(billing.GetBillRequest) returns (billing.BillResponce);
     */
    getBillsByCustkey(input: GetBillRequest, options?: RpcOptions): UnaryCall<GetBillRequest, BillResponce>;
    /**
     * @generated from protobuf rpc: GetBillsByFormNo(billing.GetBillRequest) returns (billing.BillResponce);
     */
    getBillsByFormNo(input: GetBillRequest, options?: RpcOptions): UnaryCall<GetBillRequest, BillResponce>;
}
/**
 * @generated from protobuf service billing.Engine
 */
export class EngineClient implements IEngineClient, ServiceInfo$ {
    typeName = Engine.typeName;
    methods = Engine.methods;
    options = Engine.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Info(billing.Empty) returns (billing.ServiceInfo);
     */
    info(input: Empty, options?: RpcOptions): UnaryCall<Empty, ServiceInfo> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, ServiceInfo>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Calulate(billing.ChargeRequest) returns (billing.BillResponce);
     */
    calulate(input: ChargeRequest, options?: RpcOptions): UnaryCall<ChargeRequest, BillResponce> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ChargeRequest, BillResponce>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Post(billing.PostMessage) returns (billing.Empty);
     */
    post(input: PostMessage, options?: RpcOptions): UnaryCall<PostMessage, Empty> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<PostMessage, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: PostOne(billing.PostMessage) returns (billing.Empty);
     */
    postOne(input: PostMessage, options?: RpcOptions): UnaryCall<PostMessage, Empty> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<PostMessage, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCustomerByCustkey(billing.Key) returns (billing.Customer);
     */
    getCustomerByCustkey(input: Key, options?: RpcOptions): UnaryCall<Key, Customer> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<Key, Customer>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetLoockup(billing.Entity) returns (billing.LookUpsResponce);
     */
    getLoockup(input: Entity, options?: RpcOptions): UnaryCall<Entity, LookUpsResponce> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<Entity, LookUpsResponce>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCtgs(billing.Empty) returns (billing.CtgsResponce);
     */
    getCtgs(input: Empty, options?: RpcOptions): UnaryCall<Empty, CtgsResponce> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, CtgsResponce>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetBillsByCustkey(billing.GetBillRequest) returns (billing.BillResponce);
     */
    getBillsByCustkey(input: GetBillRequest, options?: RpcOptions): UnaryCall<GetBillRequest, BillResponce> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetBillRequest, BillResponce>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetBillsByFormNo(billing.GetBillRequest) returns (billing.BillResponce);
     */
    getBillsByFormNo(input: GetBillRequest, options?: RpcOptions): UnaryCall<GetBillRequest, BillResponce> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetBillRequest, BillResponce>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service billing.LoginService
 */
export interface ILoginServiceClient {
    /**
     * @generated from protobuf rpc: Login(billing.LoginRequest) returns (billing.LoginResponce);
     */
    login(input: LoginRequest, options?: RpcOptions): UnaryCall<LoginRequest, LoginResponce>;
    /**
     * @generated from protobuf rpc: Info(billing.Empty) returns (billing.ServiceInfo);
     */
    info(input: Empty, options?: RpcOptions): UnaryCall<Empty, ServiceInfo>;
}
/**
 * @generated from protobuf service billing.LoginService
 */
export class LoginServiceClient implements ILoginServiceClient, ServiceInfo$ {
    typeName = LoginService.typeName;
    methods = LoginService.methods;
    options = LoginService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Login(billing.LoginRequest) returns (billing.LoginResponce);
     */
    login(input: LoginRequest, options?: RpcOptions): UnaryCall<LoginRequest, LoginResponce> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<LoginRequest, LoginResponce>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Info(billing.Empty) returns (billing.ServiceInfo);
     */
    info(input: Empty, options?: RpcOptions): UnaryCall<Empty, ServiceInfo> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, ServiceInfo>("unary", this._transport, method, opt, input);
    }
}
