// @generated by protobuf-ts 2.9.4 with parameter use_proto_field_name,add_pb_suffix,force_optimize_code_size,ts_nocheck,long_type_string
// @generated from protobuf file "bpm-reg.proto" (package "govcollector", syntax proto3)
// tslint:disable
// @ts-nocheck
import { MessageType } from "@protobuf-ts/runtime";
import { MasDateTime } from "./date_pb";
/**
 * @generated from protobuf message govcollector.GOV_ACTIVITIES
 */
export interface GOV_ACTIVITIES {
    /**
     * @generated from protobuf field: optional int32 ID = 1 [json_name = "ID"];
     */
    ID?: number; // @gotags: gorm:"primaryKey;autoIncrement:false;not null"
    /**
     * @generated from protobuf field: optional string ACT_NAME = 2 [json_name = "ACTNAME"];
     */
    ACT_NAME?: string; // @gotags: gorm:"size:255;not null;uniqueIndex"
    /**
     * @generated from protobuf field: optional string DESCRIPTION = 3 [json_name = "DESCRIPTION"];
     */
    DESCRIPTION?: string; // @gotags: gorm:"size:255"
    /**
     * @generated from protobuf field: optional string DESCRIPTION_EN = 4 [json_name = "DESCRIPTIONEN"];
     */
    DESCRIPTION_EN?: string;
    /**
     * @generated from protobuf field: optional bool WITH_FEES = 5 [json_name = "WITHFEES"];
     */
    WITH_FEES?: boolean; // @gotags: gorm:"not null"
    /**
     * @generated from protobuf field: optional bool CAN_MAKE_MORE_APP = 6 [json_name = "CANMAKEMOREAPP"];
     */
    CAN_MAKE_MORE_APP?: boolean;
    /**
     * @generated from protobuf field: repeated govcollector.GOV_LU_FIELDS GOV_LU_FIELDS = 7 [json_name = "GOVLUFIELDS"];
     */
    GOV_LU_FIELDS: GOV_LU_FIELDS[]; // @gotags: gorm:"-"
    /**
     * @generated from protobuf field: optional int32 CLONE_ID = 8 [json_name = "CLONEID"];
     */
    CLONE_ID?: number;
}
/**
 * @generated from protobuf message govcollector.ArrGOV_ACTIVITIES
 */
export interface ArrGOV_ACTIVITIES {
    /**
     * @generated from protobuf field: repeated govcollector.GOV_ACTIVITIES GOV_ACTIVITIES = 1 [json_name = "GOVACTIVITIES"];
     */
    GOV_ACTIVITIES: GOV_ACTIVITIES[];
}
/**
 * @generated from protobuf message govcollector.GOV_LU_FIELDS
 */
export interface GOV_LU_FIELDS {
    /**
     * @generated from protobuf field: optional int64 ID = 1 [json_name = "ID"];
     */
    ID?: string; // @gotags: gorm:"primaryKey;autoIncrement:true"
    /**
     * @generated from protobuf field: optional string NAME = 2 [json_name = "NAME"];
     */
    NAME?: string; // @gotags: gorm:"size:255;not null;uniqueIndex"
    /**
     * @generated from protobuf field: optional govcollector.DATATYPE DATA_TYPE = 3 [json_name = "DATATYPE"];
     */
    DATA_TYPE?: DATATYPE; // @gotags: gorm:"not null"
    /**
     * @generated from protobuf field: optional string DESCRIPTION = 4 [json_name = "DESCRIPTION"];
     */
    DESCRIPTION?: string;
    /**
     * @generated from protobuf field: optional string DESCRIPTION_EN = 5 [json_name = "DESCRIPTIONEN"];
     */
    DESCRIPTION_EN?: string;
    /**
     * @generated from protobuf field: optional string PARENT_NAME = 6 [json_name = "PARENTNAME"];
     */
    PARENT_NAME?: string; // @gotags: gorm:"size:255"
    /**
     * @generated from protobuf field: optional bool IS_SYSTEM = 7 [json_name = "ISSYSTEM"];
     */
    IS_SYSTEM?: boolean;
}
/**
 * @generated from protobuf message govcollector.GOV_FIELDS
 */
export interface GOV_FIELDS {
    /**
     * @generated from protobuf field: optional int64 FIELD_ID = 1 [json_name = "FIELDID"];
     */
    FIELD_ID?: string; // @gotags: gorm:"primaryKey;autoIncrement:false;not null"
    /**
     * @generated from protobuf field: optional int64 APP_ID = 2 [json_name = "APPID"];
     */
    APP_ID?: string; // @gotags: gorm:"primaryKey;autoIncrement:false;not null"
    /**
     * @generated from protobuf field: optional double AS_NUMBER = 3 [json_name = "ASNUMBER"];
     */
    AS_NUMBER?: number;
    /**
     * @generated from protobuf field: optional string AS_STRING = 4 [json_name = "ASSTRING"];
     */
    AS_STRING?: string; // @gotags: gorm:"size:255"
    /**
     * @generated from protobuf field: optional central.types.MasDateTime AS_DATE = 5 [json_name = "ASDATE"];
     */
    AS_DATE?: MasDateTime;
    /**
     * @generated from protobuf field: optional bool AS_BOOLEAN = 6 [json_name = "ASBOOLEAN"];
     */
    AS_BOOLEAN?: boolean;
    /**
     * @generated from protobuf field: optional string AS_BASE64 = 7 [json_name = "ASBASE64"];
     */
    AS_BASE64?: string;
    /**
     * @generated from protobuf field: optional int64 AS_TABLE = 8 [json_name = "ASTABLE"];
     */
    AS_TABLE?: string;
    /**
     * @generated from protobuf field: optional govcollector.ALL_TABLE_VALUES TABLE_VALUES = 9 [json_name = "TABLEVALUES"];
     */
    TABLE_VALUES?: ALL_TABLE_VALUES; // @gotags: gorm:"-"
}
/**
 * @generated from protobuf message govcollector.GOV_TABLE_VALUES
 */
export interface GOV_TABLE_VALUES {
    /**
     * @generated from protobuf field: optional int64 TABLE_ID = 1 [json_name = "TABLEID"];
     */
    TABLE_ID?: string; // @gotags: gorm:"primaryKey;autoIncrement:false"
    /**
     * @generated from protobuf field: optional int32 FIELD_ID = 2 [json_name = "FIELDID"];
     */
    FIELD_ID?: number; // @gotags: gorm:"primaryKey;autoIncrement:false"
    /**
     * @generated from protobuf field: optional int32 ROW_NUMBER = 3 [json_name = "ROWNUMBER"];
     */
    ROW_NUMBER?: number; // @gotags: gorm:"primaryKey;autoIncrement:false"
    /**
     * @generated from protobuf field: optional double AS_NUMBER = 4 [json_name = "ASNUMBER"];
     */
    AS_NUMBER?: number;
    /**
     * @generated from protobuf field: optional string AS_STRING = 5 [json_name = "ASSTRING"];
     */
    AS_STRING?: string;
    /**
     * @generated from protobuf field: optional central.types.MasDateTime AS_DATE = 6 [json_name = "ASDATE"];
     */
    AS_DATE?: MasDateTime;
    /**
     * @generated from protobuf field: optional bool AS_BOOLEAN = 7 [json_name = "ASBOOLEAN"];
     */
    AS_BOOLEAN?: boolean;
    /**
     * @generated from protobuf field: optional int64 AS_TABLE = 8 [json_name = "ASTABLE"];
     */
    AS_TABLE?: string;
}
/**
 * @generated from protobuf message govcollector.GOV_ACTIVITY_FIELDS
 */
export interface GOV_ACTIVITY_FIELDS {
    /**
     * @generated from protobuf field: optional int64 ACT_ID = 1 [json_name = "ACTID"];
     */
    ACT_ID?: string; // @gotags: gorm:"primaryKey;autoIncrement:false;not null"
    /**
     * @generated from protobuf field: optional int64 FIELD_ID = 2 [json_name = "FIELDID"];
     */
    FIELD_ID?: string; // @gotags: gorm:"primaryKey;autoIncrement:false;not null"
    /**
     * @generated from protobuf field: optional bool IS_REQUIRED = 3 [json_name = "ISREQUIRED"];
     */
    IS_REQUIRED?: boolean; // @gotags: gorm:"not null"
    /**
     * @generated from protobuf field: optional string FIELD_NAME = 4 [json_name = "FIELDNAME"];
     */
    FIELD_NAME?: string; // @gotags: gorm:"-"
}
/**
 * @generated from protobuf message govcollector.FIELD_VALUE
 */
export interface FIELD_VALUE {
    /**
     * @generated from protobuf field: optional double AS_NUMBER = 1 [json_name = "ASNUMBER"];
     */
    AS_NUMBER?: number; // @gotags: gorm:"-"
    /**
     * @generated from protobuf field: optional string AS_STRING = 2 [json_name = "ASSTRING"];
     */
    AS_STRING?: string; // @gotags: gorm:"-"
    /**
     * @generated from protobuf field: optional central.types.MasDateTime AS_DATE = 3 [json_name = "ASDATE"];
     */
    AS_DATE?: MasDateTime; // @gotags: gorm:"-"
    /**
     * @generated from protobuf field: optional bool AS_BOOLEAN = 4 [json_name = "ASBOOLEAN"];
     */
    AS_BOOLEAN?: boolean; // @gotags: gorm:"-"
    /**
     * @generated from protobuf field: optional govcollector.ALL_TABLE_VALUES AS_TABLE = 5 [json_name = "ASTABLE"];
     */
    AS_TABLE?: ALL_TABLE_VALUES; // @gotags: gorm:"-"
}
/**
 * @generated from protobuf message govcollector.DataTypes
 */
export interface DataTypes {
    /**
     * @generated from protobuf field: optional int32 CODE = 1 [json_name = "CODE"];
     */
    CODE?: number;
    /**
     * @generated from protobuf field: optional string DESCRIPTION = 2 [json_name = "DESCRIPTION"];
     */
    DESCRIPTION?: string;
}
/**
 * @generated from protobuf message govcollector.AllDataTypes
 */
export interface AllDataTypes {
    /**
     * @generated from protobuf field: repeated govcollector.DataTypes DataTypes = 1 [json_name = "DataTypes"];
     */
    DataTypes: DataTypes[];
}
/**
 * @generated from protobuf message govcollector.TABLE_ROW_VALUE
 */
export interface TABLE_ROW_VALUE {
    /**
     * @generated from protobuf field: map<int32, govcollector.FIELD_VALUE> TABLE_ROW = 1 [json_name = "TABLEROW"];
     */
    TABLE_ROW: {
        [key: number]: FIELD_VALUE;
    };
}
/**
 * @generated from protobuf message govcollector.ALL_TABLE_VALUES
 */
export interface ALL_TABLE_VALUES {
    /**
     * @generated from protobuf field: optional int64 TABLE_ID = 1 [json_name = "TABLEID"];
     */
    TABLE_ID?: string;
    /**
     * @generated from protobuf field: repeated govcollector.TABLE_ROW_VALUE TABLE_ROW_VALUE = 2 [json_name = "TABLEROWVALUE"];
     */
    TABLE_ROW_VALUE: TABLE_ROW_VALUE[];
}
/**
 * @generated from protobuf message govcollector.Lookup
 */
export interface Lookup {
    /**
     * @generated from protobuf field: optional int32 CODE = 1 [json_name = "CODE"];
     */
    CODE?: number;
    /**
     * @generated from protobuf field: optional string DESCRIPTION = 2 [json_name = "DESCRIPTION"];
     */
    DESCRIPTION?: string;
}
/**
 * @generated from protobuf message govcollector.AllLookup
 */
export interface AllLookup {
    /**
     * @generated from protobuf field: repeated govcollector.Lookup Lookup = 1 [json_name = "Lookup"];
     */
    Lookup: Lookup[];
}
/**
 * @generated from protobuf message govcollector.GOV_LU_DATA_TYPE
 */
export interface GOV_LU_DATA_TYPE {
    /**
     * @generated from protobuf field: int32 ID = 1 [json_name = "ID"];
     */
    ID: number; // @gotags: gorm:"primaryKey;autoIncrement:false;not null"
    /**
     * @generated from protobuf field: string DESCRIPTION = 2 [json_name = "DESCRIPTION"];
     */
    DESCRIPTION: string; // @gotags: gorm:"not null"
}
/**
 * @generated from protobuf message govcollector.MessageResp
 */
export interface MessageResp {
    /**
     * @generated from protobuf field: string Msg = 1 [json_name = "Msg"];
     */
    Msg: string;
}
/**
 * @generated from protobuf message govcollector.GOV_MODULE
 */
export interface GOV_MODULE {
    /**
     * @generated from protobuf field: int64 ID = 1 [json_name = "ID"];
     */
    ID: string; // @gotags: gorm:"primaryKey;autoIncrement:false;not null"
    /**
     * @generated from protobuf field: string MODULE_DESC = 2 [json_name = "MODULEDESC"];
     */
    MODULE_DESC: string;
}
/**
 * @generated from protobuf message govcollector.AllModules
 */
export interface AllModules {
    /**
     * @generated from protobuf field: repeated govcollector.GOV_MODULE GOV_MODULE = 1 [json_name = "GOVMODULE"];
     */
    GOV_MODULE: GOV_MODULE[];
}
/**
 * @generated from protobuf message govcollector.APP_EXTERNAL_ACTIVITY
 */
export interface APP_EXTERNAL_ACTIVITY {
    /**
     * @generated from protobuf field: optional int32 BPM_ID = 1 [json_name = "BPMID"];
     */
    BPM_ID?: number;
    /**
     * @generated from protobuf field: optional string ACTIVITY_NAME = 2 [json_name = "ACTIVITYNAME"];
     */
    ACTIVITY_NAME?: string;
    /**
     * @generated from protobuf field: optional int32 BPM_EXTERNAL_MODULE_ID = 3 [json_name = "BPMEXTERNALMODULEID"];
     */
    BPM_EXTERNAL_MODULE_ID?: number;
    /**
     * @generated from protobuf field: optional string IP = 4 [json_name = "IP"];
     */
    IP?: string;
    /**
     * @generated from protobuf field: optional int32 PORT = 5 [json_name = "PORT"];
     */
    PORT?: number;
    /**
     * @generated from protobuf field: repeated govcollector.APP_EXTERNAL_FIELD REQUEST = 6 [json_name = "REQUEST"];
     */
    REQUEST: APP_EXTERNAL_FIELD[];
    /**
     * @generated from protobuf field: repeated govcollector.APP_EXTERNAL_FIELD RESPONSE = 7 [json_name = "RESPONSE"];
     */
    RESPONSE: APP_EXTERNAL_FIELD[];
    /**
     * @generated from protobuf field: repeated govcollector.EXTERNAL_FEES FEES = 8 [json_name = "FEES"];
     */
    FEES: EXTERNAL_FEES[];
    /**
     * @generated from protobuf field: optional bool WITH_FORM = 9 [json_name = "WITHFORM"];
     */
    WITH_FORM?: boolean;
    /**
     * @generated from protobuf field: optional string FORM_CONFIG = 10 [json_name = "FORMCONFIG"];
     */
    FORM_CONFIG?: string;
    /**
     * @generated from protobuf field: optional bool IS_PAYMENT = 11 [json_name = "ISPAYMENT"];
     */
    IS_PAYMENT?: boolean;
    /**
     * @generated from protobuf field: optional string PACKAGE_NAME = 12 [json_name = "PACKAGENAME"];
     */
    PACKAGE_NAME?: string;
    /**
     * @generated from protobuf field: optional string SERVICE_NAME = 13 [json_name = "SERVICENAME"];
     */
    SERVICE_NAME?: string;
    /**
     * @generated from protobuf field: optional string DESCRIPTION = 14 [json_name = "DESCRIPTION"];
     */
    DESCRIPTION?: string;
    /**
     * @generated from protobuf field: optional bool IS_DUMMY = 15 [json_name = "ISDUMMY"];
     */
    IS_DUMMY?: boolean;
    /**
     * @generated from protobuf field: optional string DESCRIPTION_EN = 16 [json_name = "DESCRIPTIONEN"];
     */
    DESCRIPTION_EN?: string;
    /**
     * @generated from protobuf field: optional string BPM_FORM = 17 [json_name = "BPMFORM"];
     */
    BPM_FORM?: string;
    /**
     * @generated from protobuf field: optional bool IS_ASYNC = 18 [json_name = "ISASYNC"];
     */
    IS_ASYNC?: boolean;
    /**
     * @generated from protobuf field: map<string, string> ACT_OPTIONS = 19 [json_name = "ACTOPTIONS"];
     */
    ACT_OPTIONS: {
        [key: string]: string;
    };
    /**
     * @generated from protobuf field: optional string FORM_NAME = 20 [json_name = "FORMNAME"];
     */
    FORM_NAME?: string; // @gotags: gorm:"-"
    /**
     * @generated from protobuf field: optional int64 TRANSACTION_ID = 21 [json_name = "TRANSACTIONID"];
     */
    TRANSACTION_ID?: string;
    /**
     * @generated from protobuf field: repeated string PAGES_NAMES = 22 [json_name = "PAGESNAMES"];
     */
    PAGES_NAMES: string[]; // @gotags: gorm:"-"
    /**
     * @generated from protobuf field: optional bool WITH_REFRESH = 23 [json_name = "WITHREFRESH"];
     */
    WITH_REFRESH?: boolean; // @gotags: gorm:"-"
    /**
     * @generated from protobuf field: optional string URL = 24 [json_name = "URL"];
     */
    URL?: string; // @gotags: gorm:"-"
    /**
     * @generated from protobuf field: optional bool FROM_ACTIVITY = 25 [json_name = "FROMACTIVITY"];
     */
    FROM_ACTIVITY?: boolean; // @gotags: gorm:"-"
    /**
     * @generated from protobuf field: optional int32 ACTION_ID = 26 [json_name = "ACTIONID"];
     */
    ACTION_ID?: number; // @gotags: gorm:"-"
    /**
     * @generated from protobuf field: optional govcollector.APP_TRACER TRACE = 27 [json_name = "TRACE"];
     */
    TRACE?: APP_TRACER; // @gotags: gorm:"-"
}
/**
 * @generated from protobuf message govcollector.APP_EXTERNAL_FIELD
 */
export interface APP_EXTERNAL_FIELD {
    /**
     * @generated from protobuf field: optional int32 BPM_ID = 1 [json_name = "BPMID"];
     */
    BPM_ID?: number;
    /**
     * @generated from protobuf field: optional string NAME = 2 [json_name = "NAME"];
     */
    NAME?: string;
    /**
     * @generated from protobuf field: optional string TITLE = 3 [json_name = "TITLE"];
     */
    TITLE?: string;
    /**
     * @generated from protobuf field: optional govcollector.DATATYPE DATA_TYPE = 4 [json_name = "DATATYPE"];
     */
    DATA_TYPE?: DATATYPE;
    /**
     * @generated from protobuf field: optional govcollector.FIELDKIND KIND = 5 [json_name = "KIND"];
     */
    KIND?: FIELDKIND;
    /**
     * @generated from protobuf field: optional int32 EXTERNAL_MODULE_ID = 6 [json_name = "EXTERNALMODULEID"];
     */
    EXTERNAL_MODULE_ID?: number;
    /**
     * @generated from protobuf field: optional bool IS_REQUIRED = 7 [json_name = "ISREQUIRED"];
     */
    IS_REQUIRED?: boolean;
    /**
     * @generated from protobuf field: repeated govcollector.FIELD_VALUE FIELD_VALUES = 8 [json_name = "FIELDVALUES"];
     */
    FIELD_VALUES: FIELD_VALUE[];
    /**
     * @generated from protobuf field: optional int32 EXTERNAL_PARENT_FIELDID = 9 [json_name = "EXTERNALPARENTFIELDID"];
     */
    EXTERNAL_PARENT_FIELDID?: number;
    /**
     * @generated from protobuf field: optional string EXTERNAL_PARENT_FIELD_NAME = 10 [json_name = "EXTERNALPARENTFIELDNAME"];
     */
    EXTERNAL_PARENT_FIELD_NAME?: string;
    /**
     * @generated from protobuf field: optional bool IS_SYSTEM = 11 [json_name = "ISSYSTEM"];
     */
    IS_SYSTEM?: boolean;
    /**
     * @generated from protobuf field: optional string SYSTEM_COLUMN = 12 [json_name = "SYSTEMCOLUMN"];
     */
    SYSTEM_COLUMN?: string;
    /**
     * @generated from protobuf field: optional int32 MAP_FIELD_ID = 13 [json_name = "MAPFIELDID"];
     */
    MAP_FIELD_ID?: number; // @gotags: gorm:"-"
    /**
     * @generated from protobuf field: optional bool MAP_IS_EXTERNAL = 14 [json_name = "MAPISEXTERNAL"];
     */
    MAP_IS_EXTERNAL?: boolean; // @gotags: gorm:"-"
    /**
     * @generated from protobuf field: optional int32 MAP_MODULE_ID = 15 [json_name = "MAPMODULEID"];
     */
    MAP_MODULE_ID?: number; // @gotags: gorm:"-"
    /**
     * @generated from protobuf field: map<int32, bool> COLUMN_FIELDS = 16 [json_name = "COLUMNFIELDS"];
     */
    COLUMN_FIELDS: {
        [key: number]: boolean;
    }; // @gotags: gorm:"-"
    /**
     * @generated from protobuf field: repeated govcollector.APP_EXTERNAL_FIELD COLUMN_FIELDS_NAMES = 17 [json_name = "COLUMNFIELDSNAMES"];
     */
    COLUMN_FIELDS_NAMES: APP_EXTERNAL_FIELD[]; // @gotags: gorm:"-"
    /**
     * @generated from protobuf field: optional string TITLE_EN = 18 [json_name = "TITLEEN"];
     */
    TITLE_EN?: string;
    /**
     * @generated from protobuf field: optional string TITLE_LANG = 19 [json_name = "TITLELANG"];
     */
    TITLE_LANG?: string; // @gotags: gorm:"-"
}
/**
 * @generated from protobuf message govcollector.EXTERNAL_FEES
 */
export interface EXTERNAL_FEES {
    /**
     * @generated from protobuf field: optional int64 CODE = 1 [json_name = "CODE"];
     */
    CODE?: string;
    /**
     * @generated from protobuf field: optional string FEES_NAME = 2 [json_name = "FEESNAME"];
     */
    FEES_NAME?: string;
    /**
     * @generated from protobuf field: optional double FEES_AMOUNT = 3 [json_name = "FEESAMOUNT"];
     */
    FEES_AMOUNT?: number;
    /**
     * @generated from protobuf field: optional int64 STAMP_DATE_UNX = 4 [json_name = "STAMPDATEUNX"];
     */
    STAMP_DATE_UNX?: string;
    /**
     * @generated from protobuf field: optional central.types.MasDateTime STAMP_DATE = 5 [json_name = "STAMPDATE"];
     */
    STAMP_DATE?: MasDateTime;
    /**
     * @generated from protobuf field: optional double FEES_ORIGINAL_AMOUNT = 6 [json_name = "FEESORIGINALAMOUNT"];
     */
    FEES_ORIGINAL_AMOUNT?: number;
    /**
     * @generated from protobuf field: optional double FEES_VAT_AMOUNT = 7 [json_name = "FEESVATAMOUNT"];
     */
    FEES_VAT_AMOUNT?: number;
    /**
     * @generated from protobuf field: optional double FEES_ADMIN_AMOUNT = 8 [json_name = "FEESADMINAMOUNT"];
     */
    FEES_ADMIN_AMOUNT?: number;
    /**
     * @generated from protobuf field: optional double FEES_ADMIN_VAT_AMOUNT = 9 [json_name = "FEESADMINVATAMOUNT"];
     */
    FEES_ADMIN_VAT_AMOUNT?: number;
    /**
     * @generated from protobuf field: optional bool IS_CANCELLED = 10 [json_name = "ISCANCELLED"];
     */
    IS_CANCELLED?: boolean;
    /**
     * @generated from protobuf field: optional int32 ACTION_ID = 11 [json_name = "ACTIONID"];
     */
    ACTION_ID?: number;
    /**
     * @generated from protobuf field: optional string PARENT_FEE_NAME = 12 [json_name = "PARENTFEENAME"];
     */
    PARENT_FEE_NAME?: string;
    /**
     * @generated from protobuf field: optional string PARENT_FEE_NAME_EN = 13 [json_name = "PARENTFEENAMEEN"];
     */
    PARENT_FEE_NAME_EN?: string;
    /**
     * @generated from protobuf field: optional double FEES_BEFORE_INSTALLMENT = 14 [json_name = "FEESBEFOREINSTALLMENT"];
     */
    FEES_BEFORE_INSTALLMENT?: number;
    /**
     * @generated from protobuf field: optional double INSTALLMENT_AMOUNT = 15 [json_name = "INSTALLMENTAMOUNT"];
     */
    INSTALLMENT_AMOUNT?: number;
    /**
     * @generated from protobuf field: optional double POST_PAID_AMOUNT = 16 [json_name = "POSTPAIDAMOUNT"];
     */
    POST_PAID_AMOUNT?: number;
    /**
     * @generated from protobuf field: optional int64 FEE_TYPE_ID = 17 [json_name = "FEETYPEID"];
     */
    FEE_TYPE_ID?: string;
    /**
     * @generated from protobuf field: optional int32 ACTIVITY_ID = 18 [json_name = "ACTIVITYID"];
     */
    ACTIVITY_ID?: number;
    /**
     * @generated from protobuf field: optional string ACTIVITY_NAME = 19 [json_name = "ACTIVITYNAME"];
     */
    ACTIVITY_NAME?: string;
    /**
     * @generated from protobuf field: optional double QUANTITY_UNIT = 33 [json_name = "QUANTITYUNIT"];
     */
    QUANTITY_UNIT?: number;
    /**
     * @generated from protobuf field: optional string UNIT = 34 [json_name = "UNIT"];
     */
    UNIT?: string;
    /**
     * @generated from protobuf field: optional string EXT_DOCUMENT_NO = 35 [json_name = "EXTDOCUMENTNO"];
     */
    EXT_DOCUMENT_NO?: string;
    /**
     * @generated from protobuf field: optional central.types.MasDateTime ORDER_DATE = 36 [json_name = "ORDERDATE"];
     */
    ORDER_DATE?: MasDateTime;
    /**
     * @generated from protobuf field: optional string META_A = 37 [json_name = "METAA"];
     */
    META_A?: string;
    /**
     * @generated from protobuf field: optional string META_B = 38 [json_name = "METAB"];
     */
    META_B?: string;
    /**
     * @generated from protobuf field: optional string FEE_TYPE_NAME = 39 [json_name = "FEETYPENAME"];
     */
    FEE_TYPE_NAME?: string;
}
/**
 * @generated from protobuf message govcollector.GOV_APPLICATIONS
 */
export interface GOV_APPLICATIONS {
    /**
     * @generated from protobuf field: int64 ID = 1 [json_name = "ID"];
     */
    ID: string; // @gotags: gorm:"primaryKey;autoIncrement:true"
    /**
     * @generated from protobuf field: int32 ACT_ID = 2 [json_name = "ACTID"];
     */
    ACT_ID: number; // @gotags: gorm:"not null"
    /**
     * @generated from protobuf field: string STAMP_USER = 3 [json_name = "STAMPUSER"];
     */
    STAMP_USER: string; // @gotags: gorm:"not null"
    /**
     * @generated from protobuf field: central.types.MasDateTime STAMP_DATE = 4 [json_name = "STAMPDATE"];
     */
    STAMP_DATE?: MasDateTime; // @gotags: gorm:"not null"
    /**
     * @generated from protobuf field: optional string CUSTKEY = 5 [json_name = "CUSTKEY"];
     */
    CUSTKEY?: string;
    /**
     * @generated from protobuf field: bool IS_POSTED = 6 [json_name = "ISPOSTED"];
     */
    IS_POSTED: boolean; // @gotags: gorm:"not null"
    /**
     * @generated from protobuf field: bool IS_CANCELLED = 7 [json_name = "ISCANCELLED"];
     */
    IS_CANCELLED: boolean; // @gotags: gorm:"not null"
    /**
     * @generated from protobuf field: optional string BBM_FORM = 8 [json_name = "BBMFORM"];
     */
    BBM_FORM?: string; // @gotags: gorm:"not null"
    /**
     * @generated from protobuf field: optional int64 CYCLE_ID = 9 [json_name = "CYCLEID"];
     */
    CYCLE_ID?: string;
}
/**
 * @generated from protobuf message govcollector.ArrEXTERNAL_FEES
 */
export interface ArrEXTERNAL_FEES {
    /**
     * @generated from protobuf field: repeated govcollector.EXTERNAL_FEES EXTERNAL_FEES = 1 [json_name = "EXTERNALFEES"];
     */
    EXTERNAL_FEES: EXTERNAL_FEES[];
    /**
     * @generated from protobuf field: optional govcollector.APP_TRACER TRACE = 2 [json_name = "TRACE"];
     */
    TRACE?: APP_TRACER;
}
/**
 * @generated from protobuf message govcollector.APP_TRACER
 */
export interface APP_TRACER {
    /**
     * @generated from protobuf field: optional int64 FORM_NO = 1 [json_name = "FORMNO"];
     */
    FORM_NO?: string; // @gotags: gorm:"primaryKey"
    /**
     * @generated from protobuf field: optional int32 APPLICATION_TYPE_ID = 2 [json_name = "APPLICATIONTYPEID"];
     */
    APPLICATION_TYPE_ID?: number; // @gotags: gorm:"primaryKey"
    /**
     * @generated from protobuf field: optional int32 COMPANY_ID = 3 [json_name = "COMPANYID"];
     */
    COMPANY_ID?: number; // @gotags: gorm:"primaryKey"
    /**
     * @generated from protobuf field: optional int64 ACTIVITY_ID = 4 [json_name = "ACTIVITYID"];
     */
    ACTIVITY_ID?: string; // @gotags: gorm:"primaryKey"
    /**
     * @generated from protobuf field: optional bool ACTIVITY_PAID = 5 [json_name = "ACTIVITYPAID"];
     */
    ACTIVITY_PAID?: boolean; // @gotags: gorm:"primaryKey"
    /**
     * @generated from protobuf field: optional int32 ACTION_ID = 6 [json_name = "ACTIONID"];
     */
    ACTION_ID?: number; // @gotags: gorm:"primaryKey"
    /**
     * @generated from protobuf field: optional int64 ACTION_STAMP_DATE_UNX = 7 [json_name = "ACTIONSTAMPDATEUNX"];
     */
    ACTION_STAMP_DATE_UNX?: string; // @gotags: gorm:"primaryKey"
    /**
     * @generated from protobuf field: optional int64 REFRENCE_PAY = 8 [json_name = "REFRENCEPAY"];
     */
    REFRENCE_PAY?: string; // @gotags: gorm:"primaryKey"
    /**
     * @generated from protobuf field: optional govcollector.REQUEST_MESSAGE_TYPE REQUEST_TYPE = 9 [json_name = "REQUESTTYPE"];
     */
    REQUEST_TYPE?: REQUEST_MESSAGE_TYPE; // @gotags: gorm:"not null"
    /**
     * @generated from protobuf field: optional double AMOUNT = 10 [json_name = "AMOUNT"];
     */
    AMOUNT?: number;
    /**
     * @generated from protobuf field: optional bytes REQUEST_RESPONSE = 11 [json_name = "REQUESTRESPONSE"];
     */
    REQUEST_RESPONSE?: Uint8Array; // @gotags: gorm:"-"
    /**
     * @generated from protobuf field: optional int32 COUNT_REPEATED = 12 [json_name = "COUNTREPEATED"];
     */
    COUNT_REPEATED?: number;
    /**
     * @generated from protobuf field: optional central.types.MasDateTime FIRST_TIME = 13 [json_name = "FIRSTTIME"];
     */
    FIRST_TIME?: MasDateTime;
    /**
     * @generated from protobuf field: optional central.types.MasDateTime LAST_TIME = 14 [json_name = "LASTTIME"];
     */
    LAST_TIME?: MasDateTime;
    /**
     * @generated from protobuf field: optional bytes THIS_REQUEST = 15 [json_name = "THISREQUEST"];
     */
    THIS_REQUEST?: Uint8Array; // @gotags: gorm:"-"
}
/**
 * @generated from protobuf message govcollector.GOV_RECIEPT
 */
export interface GOV_RECIEPT {
    /**
     * @generated from protobuf field: optional int64 FEE_ID = 2 [json_name = "FEEID"];
     */
    FEE_ID?: string; // @gotags: gorm:"primaryKey;autoIncrement:false"
    /**
     * @generated from protobuf field: optional double AMOUNT = 3 [json_name = "AMOUNT"];
     */
    AMOUNT?: number; // @gotags: gorm:"not null"
    /**
     * @generated from protobuf field: optional string STAMP_USER = 4 [json_name = "STAMPUSER"];
     */
    STAMP_USER?: string; // @gotags: gorm:"not null"
    /**
     * @generated from protobuf field: optional central.types.MasDateTime STAMP_DATE = 5 [json_name = "STAMPDATE"];
     */
    STAMP_DATE?: MasDateTime; // @gotags: gorm:"primaryKey;autoIncrement:false"
    /**
     * @generated from protobuf field: optional bool IS_CANCELLED = 6 [json_name = "ISCANCELLED"];
     */
    IS_CANCELLED?: boolean; // @gotags: gorm:"not null"
    /**
     * @generated from protobuf field: optional string CANCELLED_USER = 7 [json_name = "CANCELLEDUSER"];
     */
    CANCELLED_USER?: string;
    /**
     * @generated from protobuf field: optional central.types.MasDateTime CANCELLED_DATE = 8 [json_name = "CANCELLEDDATE"];
     */
    CANCELLED_DATE?: MasDateTime;
    /**
     * @generated from protobuf field: optional int64 APP_ID = 9 [json_name = "APPID"];
     */
    APP_ID?: string; // @gotags: gorm:"primaryKey;autoIncrement:false"
}
/**
 * @generated from protobuf message govcollector.GOV_FEES
 */
export interface GOV_FEES {
    /**
     * @generated from protobuf field: optional string PAYMENT_NO = 1 [json_name = "PAYMENTNO"];
     */
    PAYMENT_NO?: string; // @gotags: gorm:"primaryKey;autoIncrement:false;uniqueIndex:IX_CS_FEES_1"
    /**
     * @generated from protobuf field: optional int64 APP_ID = 2 [json_name = "APPID"];
     */
    APP_ID?: string; // @gotags: gorm:"primaryKey;autoIncrement:false;uniqueIndex:IX_CS_FEES_1"
    /**
     * @generated from protobuf field: optional double AMOUNT = 3 [json_name = "AMOUNT"];
     */
    AMOUNT?: number; // @gotags: gorm:"not null"
    /**
     * @generated from protobuf field: optional central.types.MasDateTime STAMP_DATE = 4 [json_name = "STAMPDATE"];
     */
    STAMP_DATE?: MasDateTime; // @gotags: gorm:"not null"
    /**
     * @generated from protobuf field: optional bool IS_CANCELLED = 5 [json_name = "ISCANCELLED"];
     */
    IS_CANCELLED?: boolean; // @gotags: gorm:"not null"
    /**
     * @generated from protobuf field: optional int64 STAMP_DATE_UNX = 6 [json_name = "STAMPDATEUNX"];
     */
    STAMP_DATE_UNX?: string; // @gotags: gorm:"primaryKey;autoIncrement:false"
}
/**
 * @generated from protobuf message govcollector.CancelPaymentActivity
 */
export interface CancelPaymentActivity {
    /**
     * @generated from protobuf field: optional govcollector.APP_EXTERNAL_ACTIVITY Activity = 1 [json_name = "Activity"];
     */
    Activity?: APP_EXTERNAL_ACTIVITY;
    /**
     * @generated from protobuf field: optional string Cancel_Reason = 2 [json_name = "CancelReason"];
     */
    Cancel_Reason?: string;
}
/**
 * @generated from protobuf message govcollector.CANCEL_GOV_APP
 */
export interface CANCEL_GOV_APP {
    /**
     * @generated from protobuf field: optional string CANCEL_REASON = 1 [json_name = "CANCELREASON"];
     */
    CANCEL_REASON?: string;
    /**
     * @generated from protobuf field: optional string CANCEL_USER = 2 [json_name = "CANCELUSER"];
     */
    CANCEL_USER?: string;
    /**
     * @generated from protobuf field: optional int64 APP_ID = 3 [json_name = "APPID"];
     */
    APP_ID?: string;
}
/**
 * @generated from protobuf message govcollector.LookupValues
 */
export interface LookupValues {
    /**
     * @generated from protobuf field: optional int32 BPM_EXTERNAL_MODULE_ID = 1 [json_name = "BPMEXTERNALMODULEID"];
     */
    BPM_EXTERNAL_MODULE_ID?: number;
    /**
     * @generated from protobuf field: optional int32 APP_TYPE_ID = 2 [json_name = "APPTYPEID"];
     */
    APP_TYPE_ID?: number;
    /**
     * @generated from protobuf field: repeated govcollector.LookupVals LookupVals = 3 [json_name = "LookupVals"];
     */
    LookupVals: LookupVals[];
}
/**
 * @generated from protobuf message govcollector.LookupVals
 */
export interface LookupVals {
    /**
     * @generated from protobuf field: optional int32 FIELD_ID = 1 [json_name = "FIELDID"];
     */
    FIELD_ID?: number;
    /**
     * @generated from protobuf field: optional string CODE = 2 [json_name = "CODE"];
     */
    CODE?: string;
    /**
     * @generated from protobuf field: optional string Description = 3 [json_name = "Description"];
     */
    Description?: string;
}
/**
 * @generated from protobuf message govcollector.LookupDatasource
 */
export interface LookupDatasource {
    /**
     * @generated from protobuf field: optional int32 BPM_EXTERNAL_MODULE_ID = 1 [json_name = "BPMEXTERNALMODULEID"];
     */
    BPM_EXTERNAL_MODULE_ID?: number;
    /**
     * @generated from protobuf field: repeated govcollector.DATA_SOURCSES_VALUES DATA_SOURCSES_VALUES = 2 [json_name = "DATASOURCSESVALUES"];
     */
    DATA_SOURCSES_VALUES: DATA_SOURCSES_VALUES[];
}
/**
 * @generated from protobuf message govcollector.DATA_SOURCSES_VALUES
 */
export interface DATA_SOURCSES_VALUES {
    /**
     * @generated from protobuf field: optional int32 FIELD_ID = 1 [json_name = "FIELDID"];
     */
    FIELD_ID?: number;
    /**
     * @generated from protobuf field: repeated govcollector.FieldDatasource FieldDatasource = 2 [json_name = "FieldDatasource"];
     */
    FieldDatasource: FieldDatasource[];
    /**
     * @generated from protobuf field: optional int32 PARENT_FIELD_ID = 3 [json_name = "PARENTFIELDID"];
     */
    PARENT_FIELD_ID?: number;
}
/**
 * @generated from protobuf message govcollector.FieldDatasource
 */
export interface FieldDatasource {
    /**
     * @generated from protobuf field: optional string CODE = 2 [json_name = "CODE"];
     */
    CODE?: string;
    /**
     * @generated from protobuf field: optional govcollector.FIELD_VALUE FIELD_VALUE = 3 [json_name = "FIELDVALUE"];
     */
    FIELD_VALUE?: FIELD_VALUE;
    /**
     * @generated from protobuf field: optional string PARENT_CODE = 4 [json_name = "PARENTCODE"];
     */
    PARENT_CODE?: string;
    /**
     * @generated from protobuf field: optional int32 PARENT_FIELD_ID = 5 [json_name = "PARENTFIELDID"];
     */
    PARENT_FIELD_ID?: number;
}
/**
 * @generated from protobuf message govcollector.APP_FEES
 */
export interface APP_FEES {
    /**
     * @generated from protobuf field: repeated govcollector.GOV_FEES GOV_FEES = 1 [json_name = "GOVFEES"];
     */
    GOV_FEES: GOV_FEES[];
}
/**
 * @generated from protobuf message govcollector.APP_TRACER_REQUEST_RESPONSE
 */
export interface APP_TRACER_REQUEST_RESPONSE {
    /**
     * @generated from protobuf field: optional int64 FORM_NO = 1 [json_name = "FORMNO"];
     */
    FORM_NO?: string; // @gotags: gorm:"primaryKey"
    /**
     * @generated from protobuf field: optional int32 APPLICATION_TYPE_ID = 2 [json_name = "APPLICATIONTYPEID"];
     */
    APPLICATION_TYPE_ID?: number; // @gotags: gorm:"primaryKey"
    /**
     * @generated from protobuf field: optional int32 COMPANY_ID = 3 [json_name = "COMPANYID"];
     */
    COMPANY_ID?: number; // @gotags: gorm:"primaryKey"
    /**
     * @generated from protobuf field: optional int64 ACTIVITY_ID = 4 [json_name = "ACTIVITYID"];
     */
    ACTIVITY_ID?: string; // @gotags: gorm:"primaryKey"
    /**
     * @generated from protobuf field: optional bool ACTIVITY_PAID = 5 [json_name = "ACTIVITYPAID"];
     */
    ACTIVITY_PAID?: boolean; // @gotags: gorm:"primaryKey"
    /**
     * @generated from protobuf field: optional int32 ACTION_ID = 6 [json_name = "ACTIONID"];
     */
    ACTION_ID?: number; // @gotags: gorm:"primaryKey"
    /**
     * @generated from protobuf field: optional int64 ACTION_STAMP_DATE_UNX = 7 [json_name = "ACTIONSTAMPDATEUNX"];
     */
    ACTION_STAMP_DATE_UNX?: string; // @gotags: gorm:"primaryKey"
    /**
     * @generated from protobuf field: optional int64 REFRENCE_PAY = 8 [json_name = "REFRENCEPAY"];
     */
    REFRENCE_PAY?: string; // @gotags: gorm:"primaryKey"
    /**
     * @generated from protobuf field: optional bytes TRACE_REQUSET = 9 [json_name = "TRACEREQUSET"];
     */
    TRACE_REQUSET?: Uint8Array; // @gotags: `gorm:"type:varbinary(max)"`
    /**
     * @generated from protobuf field: optional bytes TRACE_RESPONSE = 10 [json_name = "TRACERESPONSE"];
     */
    TRACE_RESPONSE?: Uint8Array; // @gotags: `gorm:"type:varbinary(max)"`
}
/**
 * @generated from protobuf enum govcollector.DATATYPE
 */
export enum DATATYPE {
    /**
     * @generated from protobuf enum value: INT = 0;
     */
    INT = 0,
    /**
     * @generated from protobuf enum value: FLOAT = 1;
     */
    FLOAT = 1,
    /**
     * @generated from protobuf enum value: STRING = 2;
     */
    STRING = 2,
    /**
     * @generated from protobuf enum value: BOOL = 3;
     */
    BOOL = 3,
    /**
     * @generated from protobuf enum value: DATE = 4;
     */
    DATE = 4,
    /**
     * @generated from protobuf enum value: DATETIME = 5;
     */
    DATETIME = 5,
    /**
     * USED for byte arrays as images
     *
     * @generated from protobuf enum value: BASE64 = 6;
     */
    BASE64 = 6,
    /**
     * @generated from protobuf enum value: LIST = 7;
     */
    LIST = 7,
    /**
     * @generated from protobuf enum value: OUT_LIST = 8;
     */
    OUT_LIST = 8,
    /**
     * @generated from protobuf enum value: PDF = 9;
     */
    PDF = 9,
    /**
     * @generated from protobuf enum value: TABLE = 10;
     */
    TABLE = 10
}
/**
 * @generated from protobuf enum govcollector.FIELDKIND
 */
export enum FIELDKIND {
    /**
     * @generated from protobuf enum value: TEL = 0;
     */
    TEL = 0,
    /**
     * @generated from protobuf enum value: EMAIL = 2;
     */
    EMAIL = 2,
    /**
     * @generated from protobuf enum value: ID = 3;
     */
    ID = 3,
    /**
     * @generated from protobuf enum value: ADDRESS = 4;
     */
    ADDRESS = 4,
    /**
     * @generated from protobuf enum value: CHECK_LIST = 5;
     */
    CHECK_LIST = 5,
    /**
     * @generated from protobuf enum value: LABEL = 6;
     */
    LABEL = 6,
    /**
     * @generated from protobuf enum value: PARAGRAPH = 7;
     */
    PARAGRAPH = 7
}
/**
 * @generated from protobuf enum govcollector.REQUEST_MESSAGE_TYPE
 */
export enum REQUEST_MESSAGE_TYPE {
    /**
     * @generated from protobuf enum value: INITAL = 0;
     */
    INITAL = 0,
    /**
     * @generated from protobuf enum value: SUCCESS = 1;
     */
    SUCCESS = 1,
    /**
     * @generated from protobuf enum value: ERROR = 2;
     */
    ERROR = 2
}
// @generated message type with reflection information, may provide speed optimized methods
class GOV_ACTIVITIES$Type extends MessageType<GOV_ACTIVITIES> {
    constructor() {
        super("govcollector.GOV_ACTIVITIES", [
            { no: 1, name: "ID", kind: "scalar", localName: "ID", jsonName: "ID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "ACT_NAME", kind: "scalar", localName: "ACT_NAME", jsonName: "ACTNAME", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "DESCRIPTION", kind: "scalar", localName: "DESCRIPTION", jsonName: "DESCRIPTION", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "DESCRIPTION_EN", kind: "scalar", localName: "DESCRIPTION_EN", jsonName: "DESCRIPTIONEN", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "WITH_FEES", kind: "scalar", localName: "WITH_FEES", jsonName: "WITHFEES", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 6, name: "CAN_MAKE_MORE_APP", kind: "scalar", localName: "CAN_MAKE_MORE_APP", jsonName: "CANMAKEMOREAPP", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 7, name: "GOV_LU_FIELDS", kind: "message", localName: "GOV_LU_FIELDS", jsonName: "GOVLUFIELDS", repeat: 1 /*RepeatType.PACKED*/, T: () => GOV_LU_FIELDS },
            { no: 8, name: "CLONE_ID", kind: "scalar", localName: "CLONE_ID", jsonName: "CLONEID", opt: true, T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.GOV_ACTIVITIES
 */
export const GOV_ACTIVITIES = new GOV_ACTIVITIES$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ArrGOV_ACTIVITIES$Type extends MessageType<ArrGOV_ACTIVITIES> {
    constructor() {
        super("govcollector.ArrGOV_ACTIVITIES", [
            { no: 1, name: "GOV_ACTIVITIES", kind: "message", localName: "GOV_ACTIVITIES", jsonName: "GOVACTIVITIES", repeat: 1 /*RepeatType.PACKED*/, T: () => GOV_ACTIVITIES }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.ArrGOV_ACTIVITIES
 */
export const ArrGOV_ACTIVITIES = new ArrGOV_ACTIVITIES$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GOV_LU_FIELDS$Type extends MessageType<GOV_LU_FIELDS> {
    constructor() {
        super("govcollector.GOV_LU_FIELDS", [
            { no: 1, name: "ID", kind: "scalar", localName: "ID", jsonName: "ID", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "NAME", kind: "scalar", localName: "NAME", jsonName: "NAME", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "DATA_TYPE", kind: "enum", localName: "DATA_TYPE", jsonName: "DATATYPE", opt: true, T: () => ["govcollector.DATATYPE", DATATYPE] },
            { no: 4, name: "DESCRIPTION", kind: "scalar", localName: "DESCRIPTION", jsonName: "DESCRIPTION", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "DESCRIPTION_EN", kind: "scalar", localName: "DESCRIPTION_EN", jsonName: "DESCRIPTIONEN", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "PARENT_NAME", kind: "scalar", localName: "PARENT_NAME", jsonName: "PARENTNAME", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "IS_SYSTEM", kind: "scalar", localName: "IS_SYSTEM", jsonName: "ISSYSTEM", opt: true, T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.GOV_LU_FIELDS
 */
export const GOV_LU_FIELDS = new GOV_LU_FIELDS$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GOV_FIELDS$Type extends MessageType<GOV_FIELDS> {
    constructor() {
        super("govcollector.GOV_FIELDS", [
            { no: 1, name: "FIELD_ID", kind: "scalar", localName: "FIELD_ID", jsonName: "FIELDID", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "APP_ID", kind: "scalar", localName: "APP_ID", jsonName: "APPID", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 3, name: "AS_NUMBER", kind: "scalar", localName: "AS_NUMBER", jsonName: "ASNUMBER", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 4, name: "AS_STRING", kind: "scalar", localName: "AS_STRING", jsonName: "ASSTRING", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "AS_DATE", kind: "message", localName: "AS_DATE", jsonName: "ASDATE", T: () => MasDateTime },
            { no: 6, name: "AS_BOOLEAN", kind: "scalar", localName: "AS_BOOLEAN", jsonName: "ASBOOLEAN", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 7, name: "AS_BASE64", kind: "scalar", localName: "AS_BASE64", jsonName: "ASBASE64", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "AS_TABLE", kind: "scalar", localName: "AS_TABLE", jsonName: "ASTABLE", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 9, name: "TABLE_VALUES", kind: "message", localName: "TABLE_VALUES", jsonName: "TABLEVALUES", T: () => ALL_TABLE_VALUES }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.GOV_FIELDS
 */
export const GOV_FIELDS = new GOV_FIELDS$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GOV_TABLE_VALUES$Type extends MessageType<GOV_TABLE_VALUES> {
    constructor() {
        super("govcollector.GOV_TABLE_VALUES", [
            { no: 1, name: "TABLE_ID", kind: "scalar", localName: "TABLE_ID", jsonName: "TABLEID", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "FIELD_ID", kind: "scalar", localName: "FIELD_ID", jsonName: "FIELDID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "ROW_NUMBER", kind: "scalar", localName: "ROW_NUMBER", jsonName: "ROWNUMBER", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "AS_NUMBER", kind: "scalar", localName: "AS_NUMBER", jsonName: "ASNUMBER", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 5, name: "AS_STRING", kind: "scalar", localName: "AS_STRING", jsonName: "ASSTRING", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "AS_DATE", kind: "message", localName: "AS_DATE", jsonName: "ASDATE", T: () => MasDateTime },
            { no: 7, name: "AS_BOOLEAN", kind: "scalar", localName: "AS_BOOLEAN", jsonName: "ASBOOLEAN", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 8, name: "AS_TABLE", kind: "scalar", localName: "AS_TABLE", jsonName: "ASTABLE", opt: true, T: 3 /*ScalarType.INT64*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.GOV_TABLE_VALUES
 */
export const GOV_TABLE_VALUES = new GOV_TABLE_VALUES$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GOV_ACTIVITY_FIELDS$Type extends MessageType<GOV_ACTIVITY_FIELDS> {
    constructor() {
        super("govcollector.GOV_ACTIVITY_FIELDS", [
            { no: 1, name: "ACT_ID", kind: "scalar", localName: "ACT_ID", jsonName: "ACTID", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "FIELD_ID", kind: "scalar", localName: "FIELD_ID", jsonName: "FIELDID", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 3, name: "IS_REQUIRED", kind: "scalar", localName: "IS_REQUIRED", jsonName: "ISREQUIRED", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "FIELD_NAME", kind: "scalar", localName: "FIELD_NAME", jsonName: "FIELDNAME", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.GOV_ACTIVITY_FIELDS
 */
export const GOV_ACTIVITY_FIELDS = new GOV_ACTIVITY_FIELDS$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FIELD_VALUE$Type extends MessageType<FIELD_VALUE> {
    constructor() {
        super("govcollector.FIELD_VALUE", [
            { no: 1, name: "AS_NUMBER", kind: "scalar", localName: "AS_NUMBER", jsonName: "ASNUMBER", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 2, name: "AS_STRING", kind: "scalar", localName: "AS_STRING", jsonName: "ASSTRING", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "AS_DATE", kind: "message", localName: "AS_DATE", jsonName: "ASDATE", T: () => MasDateTime },
            { no: 4, name: "AS_BOOLEAN", kind: "scalar", localName: "AS_BOOLEAN", jsonName: "ASBOOLEAN", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 5, name: "AS_TABLE", kind: "message", localName: "AS_TABLE", jsonName: "ASTABLE", T: () => ALL_TABLE_VALUES }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.FIELD_VALUE
 */
export const FIELD_VALUE = new FIELD_VALUE$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DataTypes$Type extends MessageType<DataTypes> {
    constructor() {
        super("govcollector.DataTypes", [
            { no: 1, name: "CODE", kind: "scalar", localName: "CODE", jsonName: "CODE", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "DESCRIPTION", kind: "scalar", localName: "DESCRIPTION", jsonName: "DESCRIPTION", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.DataTypes
 */
export const DataTypes = new DataTypes$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AllDataTypes$Type extends MessageType<AllDataTypes> {
    constructor() {
        super("govcollector.AllDataTypes", [
            { no: 1, name: "DataTypes", kind: "message", localName: "DataTypes", jsonName: "DataTypes", repeat: 1 /*RepeatType.PACKED*/, T: () => DataTypes }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.AllDataTypes
 */
export const AllDataTypes = new AllDataTypes$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TABLE_ROW_VALUE$Type extends MessageType<TABLE_ROW_VALUE> {
    constructor() {
        super("govcollector.TABLE_ROW_VALUE", [
            { no: 1, name: "TABLE_ROW", kind: "map", localName: "TABLE_ROW", jsonName: "TABLEROW", K: 5 /*ScalarType.INT32*/, V: { kind: "message", T: () => FIELD_VALUE } }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.TABLE_ROW_VALUE
 */
export const TABLE_ROW_VALUE = new TABLE_ROW_VALUE$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ALL_TABLE_VALUES$Type extends MessageType<ALL_TABLE_VALUES> {
    constructor() {
        super("govcollector.ALL_TABLE_VALUES", [
            { no: 1, name: "TABLE_ID", kind: "scalar", localName: "TABLE_ID", jsonName: "TABLEID", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "TABLE_ROW_VALUE", kind: "message", localName: "TABLE_ROW_VALUE", jsonName: "TABLEROWVALUE", repeat: 1 /*RepeatType.PACKED*/, T: () => TABLE_ROW_VALUE }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.ALL_TABLE_VALUES
 */
export const ALL_TABLE_VALUES = new ALL_TABLE_VALUES$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Lookup$Type extends MessageType<Lookup> {
    constructor() {
        super("govcollector.Lookup", [
            { no: 1, name: "CODE", kind: "scalar", localName: "CODE", jsonName: "CODE", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "DESCRIPTION", kind: "scalar", localName: "DESCRIPTION", jsonName: "DESCRIPTION", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.Lookup
 */
export const Lookup = new Lookup$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AllLookup$Type extends MessageType<AllLookup> {
    constructor() {
        super("govcollector.AllLookup", [
            { no: 1, name: "Lookup", kind: "message", localName: "Lookup", jsonName: "Lookup", repeat: 1 /*RepeatType.PACKED*/, T: () => Lookup }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.AllLookup
 */
export const AllLookup = new AllLookup$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GOV_LU_DATA_TYPE$Type extends MessageType<GOV_LU_DATA_TYPE> {
    constructor() {
        super("govcollector.GOV_LU_DATA_TYPE", [
            { no: 1, name: "ID", kind: "scalar", localName: "ID", jsonName: "ID", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "DESCRIPTION", kind: "scalar", localName: "DESCRIPTION", jsonName: "DESCRIPTION", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.GOV_LU_DATA_TYPE
 */
export const GOV_LU_DATA_TYPE = new GOV_LU_DATA_TYPE$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MessageResp$Type extends MessageType<MessageResp> {
    constructor() {
        super("govcollector.MessageResp", [
            { no: 1, name: "Msg", kind: "scalar", localName: "Msg", jsonName: "Msg", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.MessageResp
 */
export const MessageResp = new MessageResp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GOV_MODULE$Type extends MessageType<GOV_MODULE> {
    constructor() {
        super("govcollector.GOV_MODULE", [
            { no: 1, name: "ID", kind: "scalar", localName: "ID", jsonName: "ID", T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "MODULE_DESC", kind: "scalar", localName: "MODULE_DESC", jsonName: "MODULEDESC", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.GOV_MODULE
 */
export const GOV_MODULE = new GOV_MODULE$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AllModules$Type extends MessageType<AllModules> {
    constructor() {
        super("govcollector.AllModules", [
            { no: 1, name: "GOV_MODULE", kind: "message", localName: "GOV_MODULE", jsonName: "GOVMODULE", repeat: 1 /*RepeatType.PACKED*/, T: () => GOV_MODULE }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.AllModules
 */
export const AllModules = new AllModules$Type();
// @generated message type with reflection information, may provide speed optimized methods
class APP_EXTERNAL_ACTIVITY$Type extends MessageType<APP_EXTERNAL_ACTIVITY> {
    constructor() {
        super("govcollector.APP_EXTERNAL_ACTIVITY", [
            { no: 1, name: "BPM_ID", kind: "scalar", localName: "BPM_ID", jsonName: "BPMID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "ACTIVITY_NAME", kind: "scalar", localName: "ACTIVITY_NAME", jsonName: "ACTIVITYNAME", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "BPM_EXTERNAL_MODULE_ID", kind: "scalar", localName: "BPM_EXTERNAL_MODULE_ID", jsonName: "BPMEXTERNALMODULEID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "IP", kind: "scalar", localName: "IP", jsonName: "IP", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "PORT", kind: "scalar", localName: "PORT", jsonName: "PORT", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "REQUEST", kind: "message", localName: "REQUEST", jsonName: "REQUEST", repeat: 1 /*RepeatType.PACKED*/, T: () => APP_EXTERNAL_FIELD },
            { no: 7, name: "RESPONSE", kind: "message", localName: "RESPONSE", jsonName: "RESPONSE", repeat: 1 /*RepeatType.PACKED*/, T: () => APP_EXTERNAL_FIELD },
            { no: 8, name: "FEES", kind: "message", localName: "FEES", jsonName: "FEES", repeat: 1 /*RepeatType.PACKED*/, T: () => EXTERNAL_FEES },
            { no: 9, name: "WITH_FORM", kind: "scalar", localName: "WITH_FORM", jsonName: "WITHFORM", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 10, name: "FORM_CONFIG", kind: "scalar", localName: "FORM_CONFIG", jsonName: "FORMCONFIG", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "IS_PAYMENT", kind: "scalar", localName: "IS_PAYMENT", jsonName: "ISPAYMENT", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 12, name: "PACKAGE_NAME", kind: "scalar", localName: "PACKAGE_NAME", jsonName: "PACKAGENAME", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "SERVICE_NAME", kind: "scalar", localName: "SERVICE_NAME", jsonName: "SERVICENAME", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 14, name: "DESCRIPTION", kind: "scalar", localName: "DESCRIPTION", jsonName: "DESCRIPTION", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 15, name: "IS_DUMMY", kind: "scalar", localName: "IS_DUMMY", jsonName: "ISDUMMY", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 16, name: "DESCRIPTION_EN", kind: "scalar", localName: "DESCRIPTION_EN", jsonName: "DESCRIPTIONEN", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 17, name: "BPM_FORM", kind: "scalar", localName: "BPM_FORM", jsonName: "BPMFORM", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 18, name: "IS_ASYNC", kind: "scalar", localName: "IS_ASYNC", jsonName: "ISASYNC", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 19, name: "ACT_OPTIONS", kind: "map", localName: "ACT_OPTIONS", jsonName: "ACTOPTIONS", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } },
            { no: 20, name: "FORM_NAME", kind: "scalar", localName: "FORM_NAME", jsonName: "FORMNAME", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 21, name: "TRANSACTION_ID", kind: "scalar", localName: "TRANSACTION_ID", jsonName: "TRANSACTIONID", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 22, name: "PAGES_NAMES", kind: "scalar", localName: "PAGES_NAMES", jsonName: "PAGESNAMES", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 23, name: "WITH_REFRESH", kind: "scalar", localName: "WITH_REFRESH", jsonName: "WITHREFRESH", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 24, name: "URL", kind: "scalar", localName: "URL", jsonName: "URL", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 25, name: "FROM_ACTIVITY", kind: "scalar", localName: "FROM_ACTIVITY", jsonName: "FROMACTIVITY", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 26, name: "ACTION_ID", kind: "scalar", localName: "ACTION_ID", jsonName: "ACTIONID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 27, name: "TRACE", kind: "message", localName: "TRACE", jsonName: "TRACE", T: () => APP_TRACER }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.APP_EXTERNAL_ACTIVITY
 */
export const APP_EXTERNAL_ACTIVITY = new APP_EXTERNAL_ACTIVITY$Type();
// @generated message type with reflection information, may provide speed optimized methods
class APP_EXTERNAL_FIELD$Type extends MessageType<APP_EXTERNAL_FIELD> {
    constructor() {
        super("govcollector.APP_EXTERNAL_FIELD", [
            { no: 1, name: "BPM_ID", kind: "scalar", localName: "BPM_ID", jsonName: "BPMID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "NAME", kind: "scalar", localName: "NAME", jsonName: "NAME", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "TITLE", kind: "scalar", localName: "TITLE", jsonName: "TITLE", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "DATA_TYPE", kind: "enum", localName: "DATA_TYPE", jsonName: "DATATYPE", opt: true, T: () => ["govcollector.DATATYPE", DATATYPE] },
            { no: 5, name: "KIND", kind: "enum", localName: "KIND", jsonName: "KIND", opt: true, T: () => ["govcollector.FIELDKIND", FIELDKIND] },
            { no: 6, name: "EXTERNAL_MODULE_ID", kind: "scalar", localName: "EXTERNAL_MODULE_ID", jsonName: "EXTERNALMODULEID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "IS_REQUIRED", kind: "scalar", localName: "IS_REQUIRED", jsonName: "ISREQUIRED", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 8, name: "FIELD_VALUES", kind: "message", localName: "FIELD_VALUES", jsonName: "FIELDVALUES", repeat: 1 /*RepeatType.PACKED*/, T: () => FIELD_VALUE },
            { no: 9, name: "EXTERNAL_PARENT_FIELDID", kind: "scalar", localName: "EXTERNAL_PARENT_FIELDID", jsonName: "EXTERNALPARENTFIELDID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 10, name: "EXTERNAL_PARENT_FIELD_NAME", kind: "scalar", localName: "EXTERNAL_PARENT_FIELD_NAME", jsonName: "EXTERNALPARENTFIELDNAME", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "IS_SYSTEM", kind: "scalar", localName: "IS_SYSTEM", jsonName: "ISSYSTEM", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 12, name: "SYSTEM_COLUMN", kind: "scalar", localName: "SYSTEM_COLUMN", jsonName: "SYSTEMCOLUMN", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "MAP_FIELD_ID", kind: "scalar", localName: "MAP_FIELD_ID", jsonName: "MAPFIELDID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 14, name: "MAP_IS_EXTERNAL", kind: "scalar", localName: "MAP_IS_EXTERNAL", jsonName: "MAPISEXTERNAL", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 15, name: "MAP_MODULE_ID", kind: "scalar", localName: "MAP_MODULE_ID", jsonName: "MAPMODULEID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 16, name: "COLUMN_FIELDS", kind: "map", localName: "COLUMN_FIELDS", jsonName: "COLUMNFIELDS", K: 5 /*ScalarType.INT32*/, V: { kind: "scalar", T: 8 /*ScalarType.BOOL*/ } },
            { no: 17, name: "COLUMN_FIELDS_NAMES", kind: "message", localName: "COLUMN_FIELDS_NAMES", jsonName: "COLUMNFIELDSNAMES", repeat: 1 /*RepeatType.PACKED*/, T: () => APP_EXTERNAL_FIELD },
            { no: 18, name: "TITLE_EN", kind: "scalar", localName: "TITLE_EN", jsonName: "TITLEEN", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 19, name: "TITLE_LANG", kind: "scalar", localName: "TITLE_LANG", jsonName: "TITLELANG", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.APP_EXTERNAL_FIELD
 */
export const APP_EXTERNAL_FIELD = new APP_EXTERNAL_FIELD$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EXTERNAL_FEES$Type extends MessageType<EXTERNAL_FEES> {
    constructor() {
        super("govcollector.EXTERNAL_FEES", [
            { no: 1, name: "CODE", kind: "scalar", localName: "CODE", jsonName: "CODE", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "FEES_NAME", kind: "scalar", localName: "FEES_NAME", jsonName: "FEESNAME", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "FEES_AMOUNT", kind: "scalar", localName: "FEES_AMOUNT", jsonName: "FEESAMOUNT", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 4, name: "STAMP_DATE_UNX", kind: "scalar", localName: "STAMP_DATE_UNX", jsonName: "STAMPDATEUNX", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 5, name: "STAMP_DATE", kind: "message", localName: "STAMP_DATE", jsonName: "STAMPDATE", T: () => MasDateTime },
            { no: 6, name: "FEES_ORIGINAL_AMOUNT", kind: "scalar", localName: "FEES_ORIGINAL_AMOUNT", jsonName: "FEESORIGINALAMOUNT", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 7, name: "FEES_VAT_AMOUNT", kind: "scalar", localName: "FEES_VAT_AMOUNT", jsonName: "FEESVATAMOUNT", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 8, name: "FEES_ADMIN_AMOUNT", kind: "scalar", localName: "FEES_ADMIN_AMOUNT", jsonName: "FEESADMINAMOUNT", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 9, name: "FEES_ADMIN_VAT_AMOUNT", kind: "scalar", localName: "FEES_ADMIN_VAT_AMOUNT", jsonName: "FEESADMINVATAMOUNT", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 10, name: "IS_CANCELLED", kind: "scalar", localName: "IS_CANCELLED", jsonName: "ISCANCELLED", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 11, name: "ACTION_ID", kind: "scalar", localName: "ACTION_ID", jsonName: "ACTIONID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 12, name: "PARENT_FEE_NAME", kind: "scalar", localName: "PARENT_FEE_NAME", jsonName: "PARENTFEENAME", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "PARENT_FEE_NAME_EN", kind: "scalar", localName: "PARENT_FEE_NAME_EN", jsonName: "PARENTFEENAMEEN", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 14, name: "FEES_BEFORE_INSTALLMENT", kind: "scalar", localName: "FEES_BEFORE_INSTALLMENT", jsonName: "FEESBEFOREINSTALLMENT", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 15, name: "INSTALLMENT_AMOUNT", kind: "scalar", localName: "INSTALLMENT_AMOUNT", jsonName: "INSTALLMENTAMOUNT", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 16, name: "POST_PAID_AMOUNT", kind: "scalar", localName: "POST_PAID_AMOUNT", jsonName: "POSTPAIDAMOUNT", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 17, name: "FEE_TYPE_ID", kind: "scalar", localName: "FEE_TYPE_ID", jsonName: "FEETYPEID", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 18, name: "ACTIVITY_ID", kind: "scalar", localName: "ACTIVITY_ID", jsonName: "ACTIVITYID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 19, name: "ACTIVITY_NAME", kind: "scalar", localName: "ACTIVITY_NAME", jsonName: "ACTIVITYNAME", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 33, name: "QUANTITY_UNIT", kind: "scalar", localName: "QUANTITY_UNIT", jsonName: "QUANTITYUNIT", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 34, name: "UNIT", kind: "scalar", localName: "UNIT", jsonName: "UNIT", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 35, name: "EXT_DOCUMENT_NO", kind: "scalar", localName: "EXT_DOCUMENT_NO", jsonName: "EXTDOCUMENTNO", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 36, name: "ORDER_DATE", kind: "message", localName: "ORDER_DATE", jsonName: "ORDERDATE", T: () => MasDateTime },
            { no: 37, name: "META_A", kind: "scalar", localName: "META_A", jsonName: "METAA", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 38, name: "META_B", kind: "scalar", localName: "META_B", jsonName: "METAB", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 39, name: "FEE_TYPE_NAME", kind: "scalar", localName: "FEE_TYPE_NAME", jsonName: "FEETYPENAME", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.EXTERNAL_FEES
 */
export const EXTERNAL_FEES = new EXTERNAL_FEES$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GOV_APPLICATIONS$Type extends MessageType<GOV_APPLICATIONS> {
    constructor() {
        super("govcollector.GOV_APPLICATIONS", [
            { no: 1, name: "ID", kind: "scalar", localName: "ID", jsonName: "ID", T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "ACT_ID", kind: "scalar", localName: "ACT_ID", jsonName: "ACTID", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "STAMP_USER", kind: "scalar", localName: "STAMP_USER", jsonName: "STAMPUSER", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "STAMP_DATE", kind: "message", localName: "STAMP_DATE", jsonName: "STAMPDATE", T: () => MasDateTime },
            { no: 5, name: "CUSTKEY", kind: "scalar", localName: "CUSTKEY", jsonName: "CUSTKEY", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "IS_POSTED", kind: "scalar", localName: "IS_POSTED", jsonName: "ISPOSTED", T: 8 /*ScalarType.BOOL*/ },
            { no: 7, name: "IS_CANCELLED", kind: "scalar", localName: "IS_CANCELLED", jsonName: "ISCANCELLED", T: 8 /*ScalarType.BOOL*/ },
            { no: 8, name: "BBM_FORM", kind: "scalar", localName: "BBM_FORM", jsonName: "BBMFORM", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "CYCLE_ID", kind: "scalar", localName: "CYCLE_ID", jsonName: "CYCLEID", opt: true, T: 3 /*ScalarType.INT64*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.GOV_APPLICATIONS
 */
export const GOV_APPLICATIONS = new GOV_APPLICATIONS$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ArrEXTERNAL_FEES$Type extends MessageType<ArrEXTERNAL_FEES> {
    constructor() {
        super("govcollector.ArrEXTERNAL_FEES", [
            { no: 1, name: "EXTERNAL_FEES", kind: "message", localName: "EXTERNAL_FEES", jsonName: "EXTERNALFEES", repeat: 1 /*RepeatType.PACKED*/, T: () => EXTERNAL_FEES },
            { no: 2, name: "TRACE", kind: "message", localName: "TRACE", jsonName: "TRACE", T: () => APP_TRACER }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.ArrEXTERNAL_FEES
 */
export const ArrEXTERNAL_FEES = new ArrEXTERNAL_FEES$Type();
// @generated message type with reflection information, may provide speed optimized methods
class APP_TRACER$Type extends MessageType<APP_TRACER> {
    constructor() {
        super("govcollector.APP_TRACER", [
            { no: 1, name: "FORM_NO", kind: "scalar", localName: "FORM_NO", jsonName: "FORMNO", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "APPLICATION_TYPE_ID", kind: "scalar", localName: "APPLICATION_TYPE_ID", jsonName: "APPLICATIONTYPEID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "COMPANY_ID", kind: "scalar", localName: "COMPANY_ID", jsonName: "COMPANYID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "ACTIVITY_ID", kind: "scalar", localName: "ACTIVITY_ID", jsonName: "ACTIVITYID", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 5, name: "ACTIVITY_PAID", kind: "scalar", localName: "ACTIVITY_PAID", jsonName: "ACTIVITYPAID", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 6, name: "ACTION_ID", kind: "scalar", localName: "ACTION_ID", jsonName: "ACTIONID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "ACTION_STAMP_DATE_UNX", kind: "scalar", localName: "ACTION_STAMP_DATE_UNX", jsonName: "ACTIONSTAMPDATEUNX", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 8, name: "REFRENCE_PAY", kind: "scalar", localName: "REFRENCE_PAY", jsonName: "REFRENCEPAY", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 9, name: "REQUEST_TYPE", kind: "enum", localName: "REQUEST_TYPE", jsonName: "REQUESTTYPE", opt: true, T: () => ["govcollector.REQUEST_MESSAGE_TYPE", REQUEST_MESSAGE_TYPE] },
            { no: 10, name: "AMOUNT", kind: "scalar", localName: "AMOUNT", jsonName: "AMOUNT", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 11, name: "REQUEST_RESPONSE", kind: "scalar", localName: "REQUEST_RESPONSE", jsonName: "REQUESTRESPONSE", opt: true, T: 12 /*ScalarType.BYTES*/ },
            { no: 12, name: "COUNT_REPEATED", kind: "scalar", localName: "COUNT_REPEATED", jsonName: "COUNTREPEATED", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 13, name: "FIRST_TIME", kind: "message", localName: "FIRST_TIME", jsonName: "FIRSTTIME", T: () => MasDateTime },
            { no: 14, name: "LAST_TIME", kind: "message", localName: "LAST_TIME", jsonName: "LASTTIME", T: () => MasDateTime },
            { no: 15, name: "THIS_REQUEST", kind: "scalar", localName: "THIS_REQUEST", jsonName: "THISREQUEST", opt: true, T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.APP_TRACER
 */
export const APP_TRACER = new APP_TRACER$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GOV_RECIEPT$Type extends MessageType<GOV_RECIEPT> {
    constructor() {
        super("govcollector.GOV_RECIEPT", [
            { no: 2, name: "FEE_ID", kind: "scalar", localName: "FEE_ID", jsonName: "FEEID", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 3, name: "AMOUNT", kind: "scalar", localName: "AMOUNT", jsonName: "AMOUNT", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 4, name: "STAMP_USER", kind: "scalar", localName: "STAMP_USER", jsonName: "STAMPUSER", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "STAMP_DATE", kind: "message", localName: "STAMP_DATE", jsonName: "STAMPDATE", T: () => MasDateTime },
            { no: 6, name: "IS_CANCELLED", kind: "scalar", localName: "IS_CANCELLED", jsonName: "ISCANCELLED", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 7, name: "CANCELLED_USER", kind: "scalar", localName: "CANCELLED_USER", jsonName: "CANCELLEDUSER", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "CANCELLED_DATE", kind: "message", localName: "CANCELLED_DATE", jsonName: "CANCELLEDDATE", T: () => MasDateTime },
            { no: 9, name: "APP_ID", kind: "scalar", localName: "APP_ID", jsonName: "APPID", opt: true, T: 3 /*ScalarType.INT64*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.GOV_RECIEPT
 */
export const GOV_RECIEPT = new GOV_RECIEPT$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GOV_FEES$Type extends MessageType<GOV_FEES> {
    constructor() {
        super("govcollector.GOV_FEES", [
            { no: 1, name: "PAYMENT_NO", kind: "scalar", localName: "PAYMENT_NO", jsonName: "PAYMENTNO", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "APP_ID", kind: "scalar", localName: "APP_ID", jsonName: "APPID", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 3, name: "AMOUNT", kind: "scalar", localName: "AMOUNT", jsonName: "AMOUNT", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 4, name: "STAMP_DATE", kind: "message", localName: "STAMP_DATE", jsonName: "STAMPDATE", T: () => MasDateTime },
            { no: 5, name: "IS_CANCELLED", kind: "scalar", localName: "IS_CANCELLED", jsonName: "ISCANCELLED", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 6, name: "STAMP_DATE_UNX", kind: "scalar", localName: "STAMP_DATE_UNX", jsonName: "STAMPDATEUNX", opt: true, T: 3 /*ScalarType.INT64*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.GOV_FEES
 */
export const GOV_FEES = new GOV_FEES$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CancelPaymentActivity$Type extends MessageType<CancelPaymentActivity> {
    constructor() {
        super("govcollector.CancelPaymentActivity", [
            { no: 1, name: "Activity", kind: "message", localName: "Activity", jsonName: "Activity", T: () => APP_EXTERNAL_ACTIVITY },
            { no: 2, name: "Cancel_Reason", kind: "scalar", localName: "Cancel_Reason", jsonName: "CancelReason", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.CancelPaymentActivity
 */
export const CancelPaymentActivity = new CancelPaymentActivity$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CANCEL_GOV_APP$Type extends MessageType<CANCEL_GOV_APP> {
    constructor() {
        super("govcollector.CANCEL_GOV_APP", [
            { no: 1, name: "CANCEL_REASON", kind: "scalar", localName: "CANCEL_REASON", jsonName: "CANCELREASON", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "CANCEL_USER", kind: "scalar", localName: "CANCEL_USER", jsonName: "CANCELUSER", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "APP_ID", kind: "scalar", localName: "APP_ID", jsonName: "APPID", opt: true, T: 3 /*ScalarType.INT64*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.CANCEL_GOV_APP
 */
export const CANCEL_GOV_APP = new CANCEL_GOV_APP$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LookupValues$Type extends MessageType<LookupValues> {
    constructor() {
        super("govcollector.LookupValues", [
            { no: 1, name: "BPM_EXTERNAL_MODULE_ID", kind: "scalar", localName: "BPM_EXTERNAL_MODULE_ID", jsonName: "BPMEXTERNALMODULEID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "APP_TYPE_ID", kind: "scalar", localName: "APP_TYPE_ID", jsonName: "APPTYPEID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "LookupVals", kind: "message", localName: "LookupVals", jsonName: "LookupVals", repeat: 1 /*RepeatType.PACKED*/, T: () => LookupVals }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.LookupValues
 */
export const LookupValues = new LookupValues$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LookupVals$Type extends MessageType<LookupVals> {
    constructor() {
        super("govcollector.LookupVals", [
            { no: 1, name: "FIELD_ID", kind: "scalar", localName: "FIELD_ID", jsonName: "FIELDID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "CODE", kind: "scalar", localName: "CODE", jsonName: "CODE", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "Description", kind: "scalar", localName: "Description", jsonName: "Description", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.LookupVals
 */
export const LookupVals = new LookupVals$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LookupDatasource$Type extends MessageType<LookupDatasource> {
    constructor() {
        super("govcollector.LookupDatasource", [
            { no: 1, name: "BPM_EXTERNAL_MODULE_ID", kind: "scalar", localName: "BPM_EXTERNAL_MODULE_ID", jsonName: "BPMEXTERNALMODULEID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "DATA_SOURCSES_VALUES", kind: "message", localName: "DATA_SOURCSES_VALUES", jsonName: "DATASOURCSESVALUES", repeat: 1 /*RepeatType.PACKED*/, T: () => DATA_SOURCSES_VALUES }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.LookupDatasource
 */
export const LookupDatasource = new LookupDatasource$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DATA_SOURCSES_VALUES$Type extends MessageType<DATA_SOURCSES_VALUES> {
    constructor() {
        super("govcollector.DATA_SOURCSES_VALUES", [
            { no: 1, name: "FIELD_ID", kind: "scalar", localName: "FIELD_ID", jsonName: "FIELDID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "FieldDatasource", kind: "message", localName: "FieldDatasource", jsonName: "FieldDatasource", repeat: 1 /*RepeatType.PACKED*/, T: () => FieldDatasource },
            { no: 3, name: "PARENT_FIELD_ID", kind: "scalar", localName: "PARENT_FIELD_ID", jsonName: "PARENTFIELDID", opt: true, T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.DATA_SOURCSES_VALUES
 */
export const DATA_SOURCSES_VALUES = new DATA_SOURCSES_VALUES$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FieldDatasource$Type extends MessageType<FieldDatasource> {
    constructor() {
        super("govcollector.FieldDatasource", [
            { no: 2, name: "CODE", kind: "scalar", localName: "CODE", jsonName: "CODE", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "FIELD_VALUE", kind: "message", localName: "FIELD_VALUE", jsonName: "FIELDVALUE", T: () => FIELD_VALUE },
            { no: 4, name: "PARENT_CODE", kind: "scalar", localName: "PARENT_CODE", jsonName: "PARENTCODE", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "PARENT_FIELD_ID", kind: "scalar", localName: "PARENT_FIELD_ID", jsonName: "PARENTFIELDID", opt: true, T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.FieldDatasource
 */
export const FieldDatasource = new FieldDatasource$Type();
// @generated message type with reflection information, may provide speed optimized methods
class APP_FEES$Type extends MessageType<APP_FEES> {
    constructor() {
        super("govcollector.APP_FEES", [
            { no: 1, name: "GOV_FEES", kind: "message", localName: "GOV_FEES", jsonName: "GOVFEES", repeat: 1 /*RepeatType.PACKED*/, T: () => GOV_FEES }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.APP_FEES
 */
export const APP_FEES = new APP_FEES$Type();
// @generated message type with reflection information, may provide speed optimized methods
class APP_TRACER_REQUEST_RESPONSE$Type extends MessageType<APP_TRACER_REQUEST_RESPONSE> {
    constructor() {
        super("govcollector.APP_TRACER_REQUEST_RESPONSE", [
            { no: 1, name: "FORM_NO", kind: "scalar", localName: "FORM_NO", jsonName: "FORMNO", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "APPLICATION_TYPE_ID", kind: "scalar", localName: "APPLICATION_TYPE_ID", jsonName: "APPLICATIONTYPEID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "COMPANY_ID", kind: "scalar", localName: "COMPANY_ID", jsonName: "COMPANYID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "ACTIVITY_ID", kind: "scalar", localName: "ACTIVITY_ID", jsonName: "ACTIVITYID", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 5, name: "ACTIVITY_PAID", kind: "scalar", localName: "ACTIVITY_PAID", jsonName: "ACTIVITYPAID", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 6, name: "ACTION_ID", kind: "scalar", localName: "ACTION_ID", jsonName: "ACTIONID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "ACTION_STAMP_DATE_UNX", kind: "scalar", localName: "ACTION_STAMP_DATE_UNX", jsonName: "ACTIONSTAMPDATEUNX", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 8, name: "REFRENCE_PAY", kind: "scalar", localName: "REFRENCE_PAY", jsonName: "REFRENCEPAY", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 9, name: "TRACE_REQUSET", kind: "scalar", localName: "TRACE_REQUSET", jsonName: "TRACEREQUSET", opt: true, T: 12 /*ScalarType.BYTES*/ },
            { no: 10, name: "TRACE_RESPONSE", kind: "scalar", localName: "TRACE_RESPONSE", jsonName: "TRACERESPONSE", opt: true, T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message govcollector.APP_TRACER_REQUEST_RESPONSE
 */
export const APP_TRACER_REQUEST_RESPONSE = new APP_TRACER_REQUEST_RESPONSE$Type();
