// @generated by protobuf-ts 2.9.4 with parameter use_proto_field_name,add_pb_suffix,force_optimize_code_size,ts_nocheck,long_type_string
// @generated from protobuf file "bpmreqedams.proto" (package "edams", syntax proto3)
// tslint:disable
// @ts-nocheck
import { MessageType } from "@protobuf-ts/runtime";
import { MasDateTime } from "./date_pb";
/**
 * @generated from protobuf message edams.BILLING_ACTIVITIES
 */
export interface BILLING_ACTIVITIES {
    /**
     * @generated from protobuf field: optional int32 ID = 1 [json_name = "ID"];
     */
    ID?: number; // @gotags: gorm:"primaryKey;autoIncrement:false;not null"
    /**
     * @generated from protobuf field: optional string ACT_NAME = 2 [json_name = "ACTNAME"];
     */
    ACT_NAME?: string; // @gotags: gorm:"size:255;not null;uniqueIndex"
    /**
     * @generated from protobuf field: optional string DESCRIPTION = 3 [json_name = "DESCRIPTION"];
     */
    DESCRIPTION?: string; // @gotags: gorm:"size:255"
    /**
     * @generated from protobuf field: optional string DESCRIPTION_EN = 4 [json_name = "DESCRIPTIONEN"];
     */
    DESCRIPTION_EN?: string;
    /**
     * @generated from protobuf field: optional bool WITH_FEES = 5 [json_name = "WITHFEES"];
     */
    WITH_FEES?: boolean; // @gotags: gorm:"not null"
    /**
     * @generated from protobuf field: optional bool CAN_MAKE_MORE_APP = 6 [json_name = "CANMAKEMOREAPP"];
     */
    CAN_MAKE_MORE_APP?: boolean;
    /**
     * @generated from protobuf field: repeated edams.BILLING_LU_FIELDS BILLING_LU_FIELDS = 7 [json_name = "BILLINGLUFIELDS"];
     */
    BILLING_LU_FIELDS: BILLING_LU_FIELDS[]; // @gotags: gorm:"-"
    /**
     * @generated from protobuf field: optional int32 CLONE_ID = 8 [json_name = "CLONEID"];
     */
    CLONE_ID?: number;
}
/**
 * @generated from protobuf message edams.ArrBILLING_ACTIVITIES
 */
export interface ArrBILLING_ACTIVITIES {
    /**
     * @generated from protobuf field: repeated edams.BILLING_ACTIVITIES BILLING_ACTIVITIES = 1 [json_name = "BILLINGACTIVITIES"];
     */
    BILLING_ACTIVITIES: BILLING_ACTIVITIES[];
}
/**
 * @generated from protobuf message edams.BILLING_LU_FIELDS
 */
export interface BILLING_LU_FIELDS {
    /**
     * @generated from protobuf field: optional int64 ID = 1 [json_name = "ID"];
     */
    ID?: string; // @gotags: gorm:"primaryKey;autoIncrement:true"
    /**
     * @generated from protobuf field: optional string NAME = 2 [json_name = "NAME"];
     */
    NAME?: string; // @gotags: gorm:"size:255;not null;uniqueIndex"
    /**
     * @generated from protobuf field: optional edams.DATATYPE DATA_TYPE = 3 [json_name = "DATATYPE"];
     */
    DATA_TYPE?: DATATYPE; // @gotags: gorm:"not null"
    /**
     * @generated from protobuf field: optional string DESCRIPTION = 4 [json_name = "DESCRIPTION"];
     */
    DESCRIPTION?: string;
    /**
     * @generated from protobuf field: optional string DESCRIPTION_EN = 5 [json_name = "DESCRIPTIONEN"];
     */
    DESCRIPTION_EN?: string;
    /**
     * @generated from protobuf field: optional string PARENT_NAME = 6 [json_name = "PARENTNAME"];
     */
    PARENT_NAME?: string; // @gotags: gorm:"size:255"
    /**
     * @generated from protobuf field: optional bool IS_SYSTEM = 7 [json_name = "ISSYSTEM"];
     */
    IS_SYSTEM?: boolean;
}
/**
 * @generated from protobuf message edams.BILLING_FIELDS
 */
export interface BILLING_FIELDS {
    /**
     * @generated from protobuf field: optional int64 FIELD_ID = 1 [json_name = "FIELDID"];
     */
    FIELD_ID?: string; // @gotags: gorm:"primaryKey;autoIncrement:false;not null"
    /**
     * @generated from protobuf field: optional int64 APP_ID = 2 [json_name = "APPID"];
     */
    APP_ID?: string; // @gotags: gorm:"primaryKey;autoIncrement:false;not null"
    /**
     * @generated from protobuf field: optional double AS_NUMBER = 3 [json_name = "ASNUMBER"];
     */
    AS_NUMBER?: number;
    /**
     * @generated from protobuf field: optional string AS_STRING = 4 [json_name = "ASSTRING"];
     */
    AS_STRING?: string; // @gotags: gorm:"size:255"
    /**
     * @generated from protobuf field: optional central.types.MasDateTime AS_DATE = 5 [json_name = "ASDATE"];
     */
    AS_DATE?: MasDateTime;
    /**
     * @generated from protobuf field: optional bool AS_BOOLEAN = 6 [json_name = "ASBOOLEAN"];
     */
    AS_BOOLEAN?: boolean;
    /**
     * @generated from protobuf field: optional string AS_BASE64 = 7 [json_name = "ASBASE64"];
     */
    AS_BASE64?: string;
    /**
     * @generated from protobuf field: optional int64 AS_TABLE = 8 [json_name = "ASTABLE"];
     */
    AS_TABLE?: string;
    /**
     * @generated from protobuf field: optional edams.ALL_TABLE_VALUES TABLE_VALUES = 9 [json_name = "TABLEVALUES"];
     */
    TABLE_VALUES?: ALL_TABLE_VALUES; // @gotags: gorm:"-"
}
/**
 * @generated from protobuf message edams.BILLING_TABLE_VALUES
 */
export interface BILLING_TABLE_VALUES {
    /**
     * @generated from protobuf field: optional int64 TABLE_ID = 1 [json_name = "TABLEID"];
     */
    TABLE_ID?: string; // @gotags: gorm:"primaryKey;autoIncrement:false"
    /**
     * @generated from protobuf field: optional int32 FIELD_ID = 2 [json_name = "FIELDID"];
     */
    FIELD_ID?: number; // @gotags: gorm:"primaryKey;autoIncrement:false"
    /**
     * @generated from protobuf field: optional int32 ROW_NUMBER = 3 [json_name = "ROWNUMBER"];
     */
    ROW_NUMBER?: number; // @gotags: gorm:"primaryKey;autoIncrement:false"
    /**
     * @generated from protobuf field: optional double AS_NUMBER = 4 [json_name = "ASNUMBER"];
     */
    AS_NUMBER?: number;
    /**
     * @generated from protobuf field: optional string AS_STRING = 5 [json_name = "ASSTRING"];
     */
    AS_STRING?: string;
    /**
     * @generated from protobuf field: optional central.types.MasDateTime AS_DATE = 6 [json_name = "ASDATE"];
     */
    AS_DATE?: MasDateTime;
    /**
     * @generated from protobuf field: optional bool AS_BOOLEAN = 7 [json_name = "ASBOOLEAN"];
     */
    AS_BOOLEAN?: boolean;
    /**
     * @generated from protobuf field: optional int64 AS_TABLE = 8 [json_name = "ASTABLE"];
     */
    AS_TABLE?: string;
}
/**
 * @generated from protobuf message edams.BILLING_ACTIVITY_FIELDS
 */
export interface BILLING_ACTIVITY_FIELDS {
    /**
     * @generated from protobuf field: optional int64 ACT_ID = 1 [json_name = "ACTID"];
     */
    ACT_ID?: string; // @gotags: gorm:"primaryKey;autoIncrement:false;not null"
    /**
     * @generated from protobuf field: optional int64 FIELD_ID = 2 [json_name = "FIELDID"];
     */
    FIELD_ID?: string; // @gotags: gorm:"primaryKey;autoIncrement:false;not null"
    /**
     * @generated from protobuf field: optional bool IS_REQUIRED = 3 [json_name = "ISREQUIRED"];
     */
    IS_REQUIRED?: boolean; // @gotags: gorm:"not null"
    /**
     * @generated from protobuf field: optional string FIELD_NAME = 4 [json_name = "FIELDNAME"];
     */
    FIELD_NAME?: string; // @gotags: gorm:"-"
}
/**
 * @generated from protobuf message edams.FIELD_VALUE
 */
export interface FIELD_VALUE {
    /**
     * @generated from protobuf field: optional double AS_NUMBER = 1 [json_name = "ASNUMBER"];
     */
    AS_NUMBER?: number; // @gotags: gorm:"-"
    /**
     * @generated from protobuf field: optional string AS_STRING = 2 [json_name = "ASSTRING"];
     */
    AS_STRING?: string; // @gotags: gorm:"-"
    /**
     * @generated from protobuf field: optional central.types.MasDateTime AS_DATE = 3 [json_name = "ASDATE"];
     */
    AS_DATE?: MasDateTime; // @gotags: gorm:"-"
    /**
     * @generated from protobuf field: optional bool AS_BOOLEAN = 4 [json_name = "ASBOOLEAN"];
     */
    AS_BOOLEAN?: boolean; // @gotags: gorm:"-"
    /**
     * @generated from protobuf field: optional edams.ALL_TABLE_VALUES AS_TABLE = 5 [json_name = "ASTABLE"];
     */
    AS_TABLE?: ALL_TABLE_VALUES; // @gotags: gorm:"-"
}
/**
 * @generated from protobuf message edams.TABLE_ROW_VALUE
 */
export interface TABLE_ROW_VALUE {
    /**
     * @generated from protobuf field: map<int32, edams.FIELD_VALUE> TABLE_ROW = 1 [json_name = "TABLEROW"];
     */
    TABLE_ROW: {
        [key: number]: FIELD_VALUE;
    };
}
/**
 * @generated from protobuf message edams.ALL_TABLE_VALUES
 */
export interface ALL_TABLE_VALUES {
    /**
     * @generated from protobuf field: optional int64 TABLE_ID = 1 [json_name = "TABLEID"];
     */
    TABLE_ID?: string;
    /**
     * @generated from protobuf field: repeated edams.TABLE_ROW_VALUE TABLE_ROW_VALUE = 2 [json_name = "TABLEROWVALUE"];
     */
    TABLE_ROW_VALUE: TABLE_ROW_VALUE[];
}
/**
 * @generated from protobuf message edams.BILLING_LU_DATA_TYPE
 */
export interface BILLING_LU_DATA_TYPE {
    /**
     * @generated from protobuf field: int32 ID = 1 [json_name = "ID"];
     */
    ID: number; // @gotags: gorm:"primaryKey;autoIncrement:false;not null"
    /**
     * @generated from protobuf field: string DESCRIPTION = 2 [json_name = "DESCRIPTION"];
     */
    DESCRIPTION: string; // @gotags: gorm:"not null"
}
/**
 * @generated from protobuf message edams.MessageResp
 */
export interface MessageResp {
    /**
     * @generated from protobuf field: string Msg = 1 [json_name = "Msg"];
     */
    Msg: string;
}
/**
 * @generated from protobuf message edams.BILLING_MODULE
 */
export interface BILLING_MODULE {
    /**
     * @generated from protobuf field: int64 ID = 1 [json_name = "ID"];
     */
    ID: string; // @gotags: gorm:"primaryKey;autoIncrement:false;not null"
    /**
     * @generated from protobuf field: string MODULE_DESC = 2 [json_name = "MODULEDESC"];
     */
    MODULE_DESC: string;
}
/**
 * @generated from protobuf message edams.AllModules
 */
export interface AllModules {
    /**
     * @generated from protobuf field: repeated edams.BILLING_MODULE BILLING_MODULE = 1 [json_name = "BILLINGMODULE"];
     */
    BILLING_MODULE: BILLING_MODULE[];
}
/**
 * @generated from protobuf message edams.APP_EXTERNAL_ACTIVITY
 */
export interface APP_EXTERNAL_ACTIVITY {
    /**
     * @generated from protobuf field: optional int32 BPM_ID = 1 [json_name = "BPMID"];
     */
    BPM_ID?: number;
    /**
     * @generated from protobuf field: optional string ACTIVITY_NAME = 2 [json_name = "ACTIVITYNAME"];
     */
    ACTIVITY_NAME?: string;
    /**
     * @generated from protobuf field: optional int32 BPM_EXTERNAL_MODULE_ID = 3 [json_name = "BPMEXTERNALMODULEID"];
     */
    BPM_EXTERNAL_MODULE_ID?: number;
    /**
     * @generated from protobuf field: optional string IP = 4 [json_name = "IP"];
     */
    IP?: string;
    /**
     * @generated from protobuf field: optional int32 PORT = 5 [json_name = "PORT"];
     */
    PORT?: number;
    /**
     * @generated from protobuf field: repeated edams.APP_EXTERNAL_FIELD REQUEST = 6 [json_name = "REQUEST"];
     */
    REQUEST: APP_EXTERNAL_FIELD[];
    /**
     * @generated from protobuf field: repeated edams.APP_EXTERNAL_FIELD RESPONSE = 7 [json_name = "RESPONSE"];
     */
    RESPONSE: APP_EXTERNAL_FIELD[];
    /**
     * @generated from protobuf field: repeated edams.EXTERNAL_FEES FEES = 8 [json_name = "FEES"];
     */
    FEES: EXTERNAL_FEES[];
    /**
     * @generated from protobuf field: optional bool WITH_FORM = 9 [json_name = "WITHFORM"];
     */
    WITH_FORM?: boolean;
    /**
     * @generated from protobuf field: optional string FORM_CONFIG = 10 [json_name = "FORMCONFIG"];
     */
    FORM_CONFIG?: string;
    /**
     * @generated from protobuf field: optional bool IS_PAYMENT = 11 [json_name = "ISPAYMENT"];
     */
    IS_PAYMENT?: boolean;
    /**
     * @generated from protobuf field: optional string PACKAGE_NAME = 12 [json_name = "PACKAGENAME"];
     */
    PACKAGE_NAME?: string;
    /**
     * @generated from protobuf field: optional string SERVICE_NAME = 13 [json_name = "SERVICENAME"];
     */
    SERVICE_NAME?: string;
    /**
     * @generated from protobuf field: optional string DESCRIPTION = 14 [json_name = "DESCRIPTION"];
     */
    DESCRIPTION?: string;
    /**
     * @generated from protobuf field: optional bool IS_DUMMY = 15 [json_name = "ISDUMMY"];
     */
    IS_DUMMY?: boolean;
    /**
     * @generated from protobuf field: optional string DESCRIPTION_EN = 16 [json_name = "DESCRIPTIONEN"];
     */
    DESCRIPTION_EN?: string;
    /**
     * @generated from protobuf field: optional string BPM_FORM = 17 [json_name = "BPMFORM"];
     */
    BPM_FORM?: string;
}
/**
 * @generated from protobuf message edams.APP_EXTERNAL_FIELD
 */
export interface APP_EXTERNAL_FIELD {
    /**
     * @generated from protobuf field: optional int32 BPM_ID = 1 [json_name = "BPMID"];
     */
    BPM_ID?: number;
    /**
     * @generated from protobuf field: optional string NAME = 2 [json_name = "NAME"];
     */
    NAME?: string;
    /**
     * @generated from protobuf field: optional string TITLE = 3 [json_name = "TITLE"];
     */
    TITLE?: string;
    /**
     * @generated from protobuf field: optional edams.DATATYPE DATA_TYPE = 4 [json_name = "DATATYPE"];
     */
    DATA_TYPE?: DATATYPE;
    /**
     * @generated from protobuf field: optional edams.FIELDKIND KIND = 5 [json_name = "KIND"];
     */
    KIND?: FIELDKIND;
    /**
     * @generated from protobuf field: optional int32 EXTERNAL_MODULE_ID = 6 [json_name = "EXTERNALMODULEID"];
     */
    EXTERNAL_MODULE_ID?: number;
    /**
     * @generated from protobuf field: optional bool IS_REQUIRED = 7 [json_name = "ISREQUIRED"];
     */
    IS_REQUIRED?: boolean;
    /**
     * @generated from protobuf field: repeated edams.FIELD_VALUE FIELD_VALUES = 8 [json_name = "FIELDVALUES"];
     */
    FIELD_VALUES: FIELD_VALUE[];
    /**
     * @generated from protobuf field: optional int32 EXTERNAL_PARENT_FIELDID = 9 [json_name = "EXTERNALPARENTFIELDID"];
     */
    EXTERNAL_PARENT_FIELDID?: number;
    /**
     * @generated from protobuf field: optional string EXTERNAL_PARENT_FIELD_NAME = 10 [json_name = "EXTERNALPARENTFIELDNAME"];
     */
    EXTERNAL_PARENT_FIELD_NAME?: string;
    /**
     * @generated from protobuf field: optional bool IS_SYSTEM = 11 [json_name = "ISSYSTEM"];
     */
    IS_SYSTEM?: boolean;
    /**
     * @generated from protobuf field: optional string SYSTEM_COLUMN = 12 [json_name = "SYSTEMCOLUMN"];
     */
    SYSTEM_COLUMN?: string;
    /**
     * @generated from protobuf field: optional int32 MAP_FIELD_ID = 13 [json_name = "MAPFIELDID"];
     */
    MAP_FIELD_ID?: number; // @gotags: gorm:"-"
    /**
     * @generated from protobuf field: optional bool MAP_IS_EXTERNAL = 14 [json_name = "MAPISEXTERNAL"];
     */
    MAP_IS_EXTERNAL?: boolean; // @gotags: gorm:"-"
    /**
     * @generated from protobuf field: optional int32 MAP_MODULE_ID = 15 [json_name = "MAPMODULEID"];
     */
    MAP_MODULE_ID?: number; // @gotags: gorm:"-"
    /**
     * @generated from protobuf field: map<int32, bool> COLUMN_FIELDS = 16 [json_name = "COLUMNFIELDS"];
     */
    COLUMN_FIELDS: {
        [key: number]: boolean;
    }; // @gotags: gorm:"-"
    /**
     * @generated from protobuf field: repeated edams.APP_EXTERNAL_FIELD COLUMN_FIELDS_NAMES = 17 [json_name = "COLUMNFIELDSNAMES"];
     */
    COLUMN_FIELDS_NAMES: APP_EXTERNAL_FIELD[]; // @gotags: gorm:"-"
    /**
     * @generated from protobuf field: optional string TITLE_EN = 18 [json_name = "TITLEEN"];
     */
    TITLE_EN?: string;
    /**
     * @generated from protobuf field: optional string TITLE_LANG = 19 [json_name = "TITLELANG"];
     */
    TITLE_LANG?: string; // @gotags: gorm:"-"
}
/**
 * @generated from protobuf message edams.EXTERNAL_FEES
 */
export interface EXTERNAL_FEES {
    /**
     * @generated from protobuf field: optional int64 CODE = 1 [json_name = "CODE"];
     */
    CODE?: string;
    /**
     * @generated from protobuf field: optional string FEES_NAME = 2 [json_name = "FEESNAME"];
     */
    FEES_NAME?: string;
    /**
     * @generated from protobuf field: optional double FEES_AMOUNT = 3 [json_name = "FEESAMOUNT"];
     */
    FEES_AMOUNT?: number;
    /**
     * @generated from protobuf field: optional int64 STAMP_DATE_UNX = 4 [json_name = "STAMPDATEUNX"];
     */
    STAMP_DATE_UNX?: string;
    /**
     * @generated from protobuf field: optional central.types.MasDateTime STAMP_DATE = 5 [json_name = "STAMPDATE"];
     */
    STAMP_DATE?: MasDateTime;
    /**
     * @generated from protobuf field: optional double FEES_ORIGINAL_AMOUNT = 6 [json_name = "FEESORIGINALAMOUNT"];
     */
    FEES_ORIGINAL_AMOUNT?: number;
    /**
     * @generated from protobuf field: optional double FEES_VAT_AMOUNT = 7 [json_name = "FEESVATAMOUNT"];
     */
    FEES_VAT_AMOUNT?: number;
    /**
     * @generated from protobuf field: optional double FEES_ADMIN_AMOUNT = 8 [json_name = "FEESADMINAMOUNT"];
     */
    FEES_ADMIN_AMOUNT?: number;
    /**
     * @generated from protobuf field: optional double FEES_ADMIN_VAT_AMOUNT = 9 [json_name = "FEESADMINVATAMOUNT"];
     */
    FEES_ADMIN_VAT_AMOUNT?: number;
    /**
     * @generated from protobuf field: optional bool IS_CANCELLED = 10 [json_name = "ISCANCELLED"];
     */
    IS_CANCELLED?: boolean;
    /**
     * @generated from protobuf field: optional int32 ACTION_ID = 11 [json_name = "ACTIONID"];
     */
    ACTION_ID?: number;
    /**
     * @generated from protobuf field: optional string PARENT_FEE_NAME = 12 [json_name = "PARENTFEENAME"];
     */
    PARENT_FEE_NAME?: string;
    /**
     * @generated from protobuf field: optional string PARENT_FEE_NAME_EN = 13 [json_name = "PARENTFEENAMEEN"];
     */
    PARENT_FEE_NAME_EN?: string;
    /**
     * @generated from protobuf field: optional double FEES_BEFORE_INSTALLMENT = 14 [json_name = "FEESBEFOREINSTALLMENT"];
     */
    FEES_BEFORE_INSTALLMENT?: number;
    /**
     * @generated from protobuf field: optional double INSTALLMENT_AMOUNT = 15 [json_name = "INSTALLMENTAMOUNT"];
     */
    INSTALLMENT_AMOUNT?: number;
    /**
     * @generated from protobuf field: optional double POST_PAID_AMOUNT = 16 [json_name = "POSTPAIDAMOUNT"];
     */
    POST_PAID_AMOUNT?: number;
    /**
     * @generated from protobuf field: optional int64 FEE_TYPE_ID = 17 [json_name = "FEETYPEID"];
     */
    FEE_TYPE_ID?: string;
    /**
     * @generated from protobuf field: optional int32 ACTIVITY_ID = 18 [json_name = "ACTIVITYID"];
     */
    ACTIVITY_ID?: number;
    /**
     * @generated from protobuf field: optional string ACTIVITY_NAME = 19 [json_name = "ACTIVITYNAME"];
     */
    ACTIVITY_NAME?: string;
    /**
     * @generated from protobuf field: optional double QUANTITY_UNIT = 33 [json_name = "QUANTITYUNIT"];
     */
    QUANTITY_UNIT?: number;
    /**
     * @generated from protobuf field: optional string UNIT = 34 [json_name = "UNIT"];
     */
    UNIT?: string;
    /**
     * @generated from protobuf field: optional string EXT_DOCUMENT_NO = 35 [json_name = "EXTDOCUMENTNO"];
     */
    EXT_DOCUMENT_NO?: string;
    /**
     * @generated from protobuf field: optional central.types.MasDateTime ORDER_DATE = 36 [json_name = "ORDERDATE"];
     */
    ORDER_DATE?: MasDateTime;
    /**
     * @generated from protobuf field: optional string META_A = 37 [json_name = "METAA"];
     */
    META_A?: string;
    /**
     * @generated from protobuf field: optional string META_B = 38 [json_name = "METAB"];
     */
    META_B?: string;
    /**
     * @generated from protobuf field: optional string FEE_TYPE_NAME = 39 [json_name = "FEETYPENAME"];
     */
    FEE_TYPE_NAME?: string;
}
/**
 * @generated from protobuf message edams.BILLING_APPLICATIONS
 */
export interface BILLING_APPLICATIONS {
    /**
     * @generated from protobuf field: int64 ID = 1 [json_name = "ID"];
     */
    ID: string; // @gotags: gorm:"primaryKey;autoIncrement:true"
    /**
     * @generated from protobuf field: int32 ACT_ID = 2 [json_name = "ACTID"];
     */
    ACT_ID: number; // @gotags: gorm:"not null"
    /**
     * @generated from protobuf field: string STAMP_USER = 3 [json_name = "STAMPUSER"];
     */
    STAMP_USER: string; // @gotags: gorm:"not null"
    /**
     * @generated from protobuf field: central.types.MasDateTime STAMP_DATE = 4 [json_name = "STAMPDATE"];
     */
    STAMP_DATE?: MasDateTime; // @gotags: gorm:"not null"
    /**
     * @generated from protobuf field: optional string CUSTKEYS = 5 [json_name = "CUSTKEYS"];
     */
    CUSTKEYS?: string;
    /**
     * @generated from protobuf field: bool IS_POSTED = 6 [json_name = "ISPOSTED"];
     */
    IS_POSTED: boolean; // @gotags: gorm:"not null"
    /**
     * @generated from protobuf field: bool IS_CANCELLED = 7 [json_name = "ISCANCELLED"];
     */
    IS_CANCELLED: boolean; // @gotags: gorm:"not null"
    /**
     * @generated from protobuf field: optional string BBM_FORM = 8 [json_name = "BBMFORM"];
     */
    BBM_FORM?: string; // @gotags: gorm:"not null"
    /**
     * @generated from protobuf field: optional int64 CYCLE_ID = 9 [json_name = "CYCLEID"];
     */
    CYCLE_ID?: string;
}
/**
 * @generated from protobuf enum edams.DATATYPE
 */
export enum DATATYPE {
    /**
     * @generated from protobuf enum value: INT = 0;
     */
    INT = 0,
    /**
     * @generated from protobuf enum value: FLOAT = 1;
     */
    FLOAT = 1,
    /**
     * @generated from protobuf enum value: STRING = 2;
     */
    STRING = 2,
    /**
     * @generated from protobuf enum value: BOOL = 3;
     */
    BOOL = 3,
    /**
     * @generated from protobuf enum value: DATE = 4;
     */
    DATE = 4,
    /**
     * @generated from protobuf enum value: DATETIME = 5;
     */
    DATETIME = 5,
    /**
     * USED for byte arrays as images
     *
     * @generated from protobuf enum value: BASE64 = 6;
     */
    BASE64 = 6,
    /**
     * @generated from protobuf enum value: LIST = 7;
     */
    LIST = 7,
    /**
     * @generated from protobuf enum value: OUT_LIST = 8;
     */
    OUT_LIST = 8,
    /**
     * @generated from protobuf enum value: Pdf = 9;
     */
    Pdf = 9,
    /**
     * @generated from protobuf enum value: TABLE = 10;
     */
    TABLE = 10
}
/**
 * @generated from protobuf enum edams.FIELDKIND
 */
export enum FIELDKIND {
    /**
     * @generated from protobuf enum value: TEL = 0;
     */
    TEL = 0,
    /**
     * @generated from protobuf enum value: EMAIL = 2;
     */
    EMAIL = 2,
    /**
     * @generated from protobuf enum value: ID = 3;
     */
    ID = 3,
    /**
     * @generated from protobuf enum value: ADDRESS = 4;
     */
    ADDRESS = 4,
    /**
     * @generated from protobuf enum value: CHECK_LIST = 5;
     */
    CHECK_LIST = 5,
    /**
     * @generated from protobuf enum value: LABEL = 6;
     */
    LABEL = 6,
    /**
     * @generated from protobuf enum value: PARAGRAPH = 7;
     */
    PARAGRAPH = 7
}
// @generated message type with reflection information, may provide speed optimized methods
class BILLING_ACTIVITIES$Type extends MessageType<BILLING_ACTIVITIES> {
    constructor() {
        super("edams.BILLING_ACTIVITIES", [
            { no: 1, name: "ID", kind: "scalar", localName: "ID", jsonName: "ID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "ACT_NAME", kind: "scalar", localName: "ACT_NAME", jsonName: "ACTNAME", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "DESCRIPTION", kind: "scalar", localName: "DESCRIPTION", jsonName: "DESCRIPTION", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "DESCRIPTION_EN", kind: "scalar", localName: "DESCRIPTION_EN", jsonName: "DESCRIPTIONEN", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "WITH_FEES", kind: "scalar", localName: "WITH_FEES", jsonName: "WITHFEES", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 6, name: "CAN_MAKE_MORE_APP", kind: "scalar", localName: "CAN_MAKE_MORE_APP", jsonName: "CANMAKEMOREAPP", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 7, name: "BILLING_LU_FIELDS", kind: "message", localName: "BILLING_LU_FIELDS", jsonName: "BILLINGLUFIELDS", repeat: 1 /*RepeatType.PACKED*/, T: () => BILLING_LU_FIELDS },
            { no: 8, name: "CLONE_ID", kind: "scalar", localName: "CLONE_ID", jsonName: "CLONEID", opt: true, T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message edams.BILLING_ACTIVITIES
 */
export const BILLING_ACTIVITIES = new BILLING_ACTIVITIES$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ArrBILLING_ACTIVITIES$Type extends MessageType<ArrBILLING_ACTIVITIES> {
    constructor() {
        super("edams.ArrBILLING_ACTIVITIES", [
            { no: 1, name: "BILLING_ACTIVITIES", kind: "message", localName: "BILLING_ACTIVITIES", jsonName: "BILLINGACTIVITIES", repeat: 1 /*RepeatType.PACKED*/, T: () => BILLING_ACTIVITIES }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message edams.ArrBILLING_ACTIVITIES
 */
export const ArrBILLING_ACTIVITIES = new ArrBILLING_ACTIVITIES$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BILLING_LU_FIELDS$Type extends MessageType<BILLING_LU_FIELDS> {
    constructor() {
        super("edams.BILLING_LU_FIELDS", [
            { no: 1, name: "ID", kind: "scalar", localName: "ID", jsonName: "ID", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "NAME", kind: "scalar", localName: "NAME", jsonName: "NAME", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "DATA_TYPE", kind: "enum", localName: "DATA_TYPE", jsonName: "DATATYPE", opt: true, T: () => ["edams.DATATYPE", DATATYPE] },
            { no: 4, name: "DESCRIPTION", kind: "scalar", localName: "DESCRIPTION", jsonName: "DESCRIPTION", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "DESCRIPTION_EN", kind: "scalar", localName: "DESCRIPTION_EN", jsonName: "DESCRIPTIONEN", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "PARENT_NAME", kind: "scalar", localName: "PARENT_NAME", jsonName: "PARENTNAME", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "IS_SYSTEM", kind: "scalar", localName: "IS_SYSTEM", jsonName: "ISSYSTEM", opt: true, T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message edams.BILLING_LU_FIELDS
 */
export const BILLING_LU_FIELDS = new BILLING_LU_FIELDS$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BILLING_FIELDS$Type extends MessageType<BILLING_FIELDS> {
    constructor() {
        super("edams.BILLING_FIELDS", [
            { no: 1, name: "FIELD_ID", kind: "scalar", localName: "FIELD_ID", jsonName: "FIELDID", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "APP_ID", kind: "scalar", localName: "APP_ID", jsonName: "APPID", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 3, name: "AS_NUMBER", kind: "scalar", localName: "AS_NUMBER", jsonName: "ASNUMBER", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 4, name: "AS_STRING", kind: "scalar", localName: "AS_STRING", jsonName: "ASSTRING", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "AS_DATE", kind: "message", localName: "AS_DATE", jsonName: "ASDATE", T: () => MasDateTime },
            { no: 6, name: "AS_BOOLEAN", kind: "scalar", localName: "AS_BOOLEAN", jsonName: "ASBOOLEAN", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 7, name: "AS_BASE64", kind: "scalar", localName: "AS_BASE64", jsonName: "ASBASE64", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "AS_TABLE", kind: "scalar", localName: "AS_TABLE", jsonName: "ASTABLE", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 9, name: "TABLE_VALUES", kind: "message", localName: "TABLE_VALUES", jsonName: "TABLEVALUES", T: () => ALL_TABLE_VALUES }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message edams.BILLING_FIELDS
 */
export const BILLING_FIELDS = new BILLING_FIELDS$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BILLING_TABLE_VALUES$Type extends MessageType<BILLING_TABLE_VALUES> {
    constructor() {
        super("edams.BILLING_TABLE_VALUES", [
            { no: 1, name: "TABLE_ID", kind: "scalar", localName: "TABLE_ID", jsonName: "TABLEID", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "FIELD_ID", kind: "scalar", localName: "FIELD_ID", jsonName: "FIELDID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "ROW_NUMBER", kind: "scalar", localName: "ROW_NUMBER", jsonName: "ROWNUMBER", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "AS_NUMBER", kind: "scalar", localName: "AS_NUMBER", jsonName: "ASNUMBER", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 5, name: "AS_STRING", kind: "scalar", localName: "AS_STRING", jsonName: "ASSTRING", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "AS_DATE", kind: "message", localName: "AS_DATE", jsonName: "ASDATE", T: () => MasDateTime },
            { no: 7, name: "AS_BOOLEAN", kind: "scalar", localName: "AS_BOOLEAN", jsonName: "ASBOOLEAN", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 8, name: "AS_TABLE", kind: "scalar", localName: "AS_TABLE", jsonName: "ASTABLE", opt: true, T: 3 /*ScalarType.INT64*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message edams.BILLING_TABLE_VALUES
 */
export const BILLING_TABLE_VALUES = new BILLING_TABLE_VALUES$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BILLING_ACTIVITY_FIELDS$Type extends MessageType<BILLING_ACTIVITY_FIELDS> {
    constructor() {
        super("edams.BILLING_ACTIVITY_FIELDS", [
            { no: 1, name: "ACT_ID", kind: "scalar", localName: "ACT_ID", jsonName: "ACTID", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "FIELD_ID", kind: "scalar", localName: "FIELD_ID", jsonName: "FIELDID", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 3, name: "IS_REQUIRED", kind: "scalar", localName: "IS_REQUIRED", jsonName: "ISREQUIRED", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "FIELD_NAME", kind: "scalar", localName: "FIELD_NAME", jsonName: "FIELDNAME", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message edams.BILLING_ACTIVITY_FIELDS
 */
export const BILLING_ACTIVITY_FIELDS = new BILLING_ACTIVITY_FIELDS$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FIELD_VALUE$Type extends MessageType<FIELD_VALUE> {
    constructor() {
        super("edams.FIELD_VALUE", [
            { no: 1, name: "AS_NUMBER", kind: "scalar", localName: "AS_NUMBER", jsonName: "ASNUMBER", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 2, name: "AS_STRING", kind: "scalar", localName: "AS_STRING", jsonName: "ASSTRING", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "AS_DATE", kind: "message", localName: "AS_DATE", jsonName: "ASDATE", T: () => MasDateTime },
            { no: 4, name: "AS_BOOLEAN", kind: "scalar", localName: "AS_BOOLEAN", jsonName: "ASBOOLEAN", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 5, name: "AS_TABLE", kind: "message", localName: "AS_TABLE", jsonName: "ASTABLE", T: () => ALL_TABLE_VALUES }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message edams.FIELD_VALUE
 */
export const FIELD_VALUE = new FIELD_VALUE$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TABLE_ROW_VALUE$Type extends MessageType<TABLE_ROW_VALUE> {
    constructor() {
        super("edams.TABLE_ROW_VALUE", [
            { no: 1, name: "TABLE_ROW", kind: "map", localName: "TABLE_ROW", jsonName: "TABLEROW", K: 5 /*ScalarType.INT32*/, V: { kind: "message", T: () => FIELD_VALUE } }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message edams.TABLE_ROW_VALUE
 */
export const TABLE_ROW_VALUE = new TABLE_ROW_VALUE$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ALL_TABLE_VALUES$Type extends MessageType<ALL_TABLE_VALUES> {
    constructor() {
        super("edams.ALL_TABLE_VALUES", [
            { no: 1, name: "TABLE_ID", kind: "scalar", localName: "TABLE_ID", jsonName: "TABLEID", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "TABLE_ROW_VALUE", kind: "message", localName: "TABLE_ROW_VALUE", jsonName: "TABLEROWVALUE", repeat: 1 /*RepeatType.PACKED*/, T: () => TABLE_ROW_VALUE }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message edams.ALL_TABLE_VALUES
 */
export const ALL_TABLE_VALUES = new ALL_TABLE_VALUES$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BILLING_LU_DATA_TYPE$Type extends MessageType<BILLING_LU_DATA_TYPE> {
    constructor() {
        super("edams.BILLING_LU_DATA_TYPE", [
            { no: 1, name: "ID", kind: "scalar", localName: "ID", jsonName: "ID", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "DESCRIPTION", kind: "scalar", localName: "DESCRIPTION", jsonName: "DESCRIPTION", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message edams.BILLING_LU_DATA_TYPE
 */
export const BILLING_LU_DATA_TYPE = new BILLING_LU_DATA_TYPE$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MessageResp$Type extends MessageType<MessageResp> {
    constructor() {
        super("edams.MessageResp", [
            { no: 1, name: "Msg", kind: "scalar", localName: "Msg", jsonName: "Msg", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message edams.MessageResp
 */
export const MessageResp = new MessageResp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BILLING_MODULE$Type extends MessageType<BILLING_MODULE> {
    constructor() {
        super("edams.BILLING_MODULE", [
            { no: 1, name: "ID", kind: "scalar", localName: "ID", jsonName: "ID", T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "MODULE_DESC", kind: "scalar", localName: "MODULE_DESC", jsonName: "MODULEDESC", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message edams.BILLING_MODULE
 */
export const BILLING_MODULE = new BILLING_MODULE$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AllModules$Type extends MessageType<AllModules> {
    constructor() {
        super("edams.AllModules", [
            { no: 1, name: "BILLING_MODULE", kind: "message", localName: "BILLING_MODULE", jsonName: "BILLINGMODULE", repeat: 1 /*RepeatType.PACKED*/, T: () => BILLING_MODULE }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message edams.AllModules
 */
export const AllModules = new AllModules$Type();
// @generated message type with reflection information, may provide speed optimized methods
class APP_EXTERNAL_ACTIVITY$Type extends MessageType<APP_EXTERNAL_ACTIVITY> {
    constructor() {
        super("edams.APP_EXTERNAL_ACTIVITY", [
            { no: 1, name: "BPM_ID", kind: "scalar", localName: "BPM_ID", jsonName: "BPMID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "ACTIVITY_NAME", kind: "scalar", localName: "ACTIVITY_NAME", jsonName: "ACTIVITYNAME", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "BPM_EXTERNAL_MODULE_ID", kind: "scalar", localName: "BPM_EXTERNAL_MODULE_ID", jsonName: "BPMEXTERNALMODULEID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "IP", kind: "scalar", localName: "IP", jsonName: "IP", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "PORT", kind: "scalar", localName: "PORT", jsonName: "PORT", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "REQUEST", kind: "message", localName: "REQUEST", jsonName: "REQUEST", repeat: 1 /*RepeatType.PACKED*/, T: () => APP_EXTERNAL_FIELD },
            { no: 7, name: "RESPONSE", kind: "message", localName: "RESPONSE", jsonName: "RESPONSE", repeat: 1 /*RepeatType.PACKED*/, T: () => APP_EXTERNAL_FIELD },
            { no: 8, name: "FEES", kind: "message", localName: "FEES", jsonName: "FEES", repeat: 1 /*RepeatType.PACKED*/, T: () => EXTERNAL_FEES },
            { no: 9, name: "WITH_FORM", kind: "scalar", localName: "WITH_FORM", jsonName: "WITHFORM", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 10, name: "FORM_CONFIG", kind: "scalar", localName: "FORM_CONFIG", jsonName: "FORMCONFIG", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "IS_PAYMENT", kind: "scalar", localName: "IS_PAYMENT", jsonName: "ISPAYMENT", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 12, name: "PACKAGE_NAME", kind: "scalar", localName: "PACKAGE_NAME", jsonName: "PACKAGENAME", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "SERVICE_NAME", kind: "scalar", localName: "SERVICE_NAME", jsonName: "SERVICENAME", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 14, name: "DESCRIPTION", kind: "scalar", localName: "DESCRIPTION", jsonName: "DESCRIPTION", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 15, name: "IS_DUMMY", kind: "scalar", localName: "IS_DUMMY", jsonName: "ISDUMMY", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 16, name: "DESCRIPTION_EN", kind: "scalar", localName: "DESCRIPTION_EN", jsonName: "DESCRIPTIONEN", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 17, name: "BPM_FORM", kind: "scalar", localName: "BPM_FORM", jsonName: "BPMFORM", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message edams.APP_EXTERNAL_ACTIVITY
 */
export const APP_EXTERNAL_ACTIVITY = new APP_EXTERNAL_ACTIVITY$Type();
// @generated message type with reflection information, may provide speed optimized methods
class APP_EXTERNAL_FIELD$Type extends MessageType<APP_EXTERNAL_FIELD> {
    constructor() {
        super("edams.APP_EXTERNAL_FIELD", [
            { no: 1, name: "BPM_ID", kind: "scalar", localName: "BPM_ID", jsonName: "BPMID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "NAME", kind: "scalar", localName: "NAME", jsonName: "NAME", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "TITLE", kind: "scalar", localName: "TITLE", jsonName: "TITLE", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "DATA_TYPE", kind: "enum", localName: "DATA_TYPE", jsonName: "DATATYPE", opt: true, T: () => ["edams.DATATYPE", DATATYPE] },
            { no: 5, name: "KIND", kind: "enum", localName: "KIND", jsonName: "KIND", opt: true, T: () => ["edams.FIELDKIND", FIELDKIND] },
            { no: 6, name: "EXTERNAL_MODULE_ID", kind: "scalar", localName: "EXTERNAL_MODULE_ID", jsonName: "EXTERNALMODULEID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "IS_REQUIRED", kind: "scalar", localName: "IS_REQUIRED", jsonName: "ISREQUIRED", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 8, name: "FIELD_VALUES", kind: "message", localName: "FIELD_VALUES", jsonName: "FIELDVALUES", repeat: 1 /*RepeatType.PACKED*/, T: () => FIELD_VALUE },
            { no: 9, name: "EXTERNAL_PARENT_FIELDID", kind: "scalar", localName: "EXTERNAL_PARENT_FIELDID", jsonName: "EXTERNALPARENTFIELDID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 10, name: "EXTERNAL_PARENT_FIELD_NAME", kind: "scalar", localName: "EXTERNAL_PARENT_FIELD_NAME", jsonName: "EXTERNALPARENTFIELDNAME", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "IS_SYSTEM", kind: "scalar", localName: "IS_SYSTEM", jsonName: "ISSYSTEM", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 12, name: "SYSTEM_COLUMN", kind: "scalar", localName: "SYSTEM_COLUMN", jsonName: "SYSTEMCOLUMN", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "MAP_FIELD_ID", kind: "scalar", localName: "MAP_FIELD_ID", jsonName: "MAPFIELDID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 14, name: "MAP_IS_EXTERNAL", kind: "scalar", localName: "MAP_IS_EXTERNAL", jsonName: "MAPISEXTERNAL", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 15, name: "MAP_MODULE_ID", kind: "scalar", localName: "MAP_MODULE_ID", jsonName: "MAPMODULEID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 16, name: "COLUMN_FIELDS", kind: "map", localName: "COLUMN_FIELDS", jsonName: "COLUMNFIELDS", K: 5 /*ScalarType.INT32*/, V: { kind: "scalar", T: 8 /*ScalarType.BOOL*/ } },
            { no: 17, name: "COLUMN_FIELDS_NAMES", kind: "message", localName: "COLUMN_FIELDS_NAMES", jsonName: "COLUMNFIELDSNAMES", repeat: 1 /*RepeatType.PACKED*/, T: () => APP_EXTERNAL_FIELD },
            { no: 18, name: "TITLE_EN", kind: "scalar", localName: "TITLE_EN", jsonName: "TITLEEN", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 19, name: "TITLE_LANG", kind: "scalar", localName: "TITLE_LANG", jsonName: "TITLELANG", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message edams.APP_EXTERNAL_FIELD
 */
export const APP_EXTERNAL_FIELD = new APP_EXTERNAL_FIELD$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EXTERNAL_FEES$Type extends MessageType<EXTERNAL_FEES> {
    constructor() {
        super("edams.EXTERNAL_FEES", [
            { no: 1, name: "CODE", kind: "scalar", localName: "CODE", jsonName: "CODE", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "FEES_NAME", kind: "scalar", localName: "FEES_NAME", jsonName: "FEESNAME", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "FEES_AMOUNT", kind: "scalar", localName: "FEES_AMOUNT", jsonName: "FEESAMOUNT", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 4, name: "STAMP_DATE_UNX", kind: "scalar", localName: "STAMP_DATE_UNX", jsonName: "STAMPDATEUNX", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 5, name: "STAMP_DATE", kind: "message", localName: "STAMP_DATE", jsonName: "STAMPDATE", T: () => MasDateTime },
            { no: 6, name: "FEES_ORIGINAL_AMOUNT", kind: "scalar", localName: "FEES_ORIGINAL_AMOUNT", jsonName: "FEESORIGINALAMOUNT", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 7, name: "FEES_VAT_AMOUNT", kind: "scalar", localName: "FEES_VAT_AMOUNT", jsonName: "FEESVATAMOUNT", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 8, name: "FEES_ADMIN_AMOUNT", kind: "scalar", localName: "FEES_ADMIN_AMOUNT", jsonName: "FEESADMINAMOUNT", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 9, name: "FEES_ADMIN_VAT_AMOUNT", kind: "scalar", localName: "FEES_ADMIN_VAT_AMOUNT", jsonName: "FEESADMINVATAMOUNT", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 10, name: "IS_CANCELLED", kind: "scalar", localName: "IS_CANCELLED", jsonName: "ISCANCELLED", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 11, name: "ACTION_ID", kind: "scalar", localName: "ACTION_ID", jsonName: "ACTIONID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 12, name: "PARENT_FEE_NAME", kind: "scalar", localName: "PARENT_FEE_NAME", jsonName: "PARENTFEENAME", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "PARENT_FEE_NAME_EN", kind: "scalar", localName: "PARENT_FEE_NAME_EN", jsonName: "PARENTFEENAMEEN", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 14, name: "FEES_BEFORE_INSTALLMENT", kind: "scalar", localName: "FEES_BEFORE_INSTALLMENT", jsonName: "FEESBEFOREINSTALLMENT", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 15, name: "INSTALLMENT_AMOUNT", kind: "scalar", localName: "INSTALLMENT_AMOUNT", jsonName: "INSTALLMENTAMOUNT", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 16, name: "POST_PAID_AMOUNT", kind: "scalar", localName: "POST_PAID_AMOUNT", jsonName: "POSTPAIDAMOUNT", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 17, name: "FEE_TYPE_ID", kind: "scalar", localName: "FEE_TYPE_ID", jsonName: "FEETYPEID", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 18, name: "ACTIVITY_ID", kind: "scalar", localName: "ACTIVITY_ID", jsonName: "ACTIVITYID", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 19, name: "ACTIVITY_NAME", kind: "scalar", localName: "ACTIVITY_NAME", jsonName: "ACTIVITYNAME", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 33, name: "QUANTITY_UNIT", kind: "scalar", localName: "QUANTITY_UNIT", jsonName: "QUANTITYUNIT", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 34, name: "UNIT", kind: "scalar", localName: "UNIT", jsonName: "UNIT", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 35, name: "EXT_DOCUMENT_NO", kind: "scalar", localName: "EXT_DOCUMENT_NO", jsonName: "EXTDOCUMENTNO", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 36, name: "ORDER_DATE", kind: "message", localName: "ORDER_DATE", jsonName: "ORDERDATE", T: () => MasDateTime },
            { no: 37, name: "META_A", kind: "scalar", localName: "META_A", jsonName: "METAA", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 38, name: "META_B", kind: "scalar", localName: "META_B", jsonName: "METAB", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 39, name: "FEE_TYPE_NAME", kind: "scalar", localName: "FEE_TYPE_NAME", jsonName: "FEETYPENAME", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message edams.EXTERNAL_FEES
 */
export const EXTERNAL_FEES = new EXTERNAL_FEES$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BILLING_APPLICATIONS$Type extends MessageType<BILLING_APPLICATIONS> {
    constructor() {
        super("edams.BILLING_APPLICATIONS", [
            { no: 1, name: "ID", kind: "scalar", localName: "ID", jsonName: "ID", T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "ACT_ID", kind: "scalar", localName: "ACT_ID", jsonName: "ACTID", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "STAMP_USER", kind: "scalar", localName: "STAMP_USER", jsonName: "STAMPUSER", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "STAMP_DATE", kind: "message", localName: "STAMP_DATE", jsonName: "STAMPDATE", T: () => MasDateTime },
            { no: 5, name: "CUSTKEYS", kind: "scalar", localName: "CUSTKEYS", jsonName: "CUSTKEYS", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "IS_POSTED", kind: "scalar", localName: "IS_POSTED", jsonName: "ISPOSTED", T: 8 /*ScalarType.BOOL*/ },
            { no: 7, name: "IS_CANCELLED", kind: "scalar", localName: "IS_CANCELLED", jsonName: "ISCANCELLED", T: 8 /*ScalarType.BOOL*/ },
            { no: 8, name: "BBM_FORM", kind: "scalar", localName: "BBM_FORM", jsonName: "BBMFORM", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "CYCLE_ID", kind: "scalar", localName: "CYCLE_ID", jsonName: "CYCLEID", opt: true, T: 3 /*ScalarType.INT64*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message edams.BILLING_APPLICATIONS
 */
export const BILLING_APPLICATIONS = new BILLING_APPLICATIONS$Type();
