// @generated by protobuf-ts 2.9.4 with parameter use_proto_field_name,add_pb_suffix,force_optimize_code_size,ts_nocheck,long_type_string
// @generated from protobuf file "common.proto" (package "micromas", syntax proto3)
// tslint:disable
// @ts-nocheck
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message micromas.Empty
 */
export interface Empty {
}
/**
 * @generated from protobuf message micromas.VersionResponse
 */
export interface VersionResponse {
    /**
     * @generated from protobuf field: string version = 1;
     */
    version: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class Empty$Type extends MessageType<Empty> {
    constructor() {
        super("micromas.Empty", []);
    }
}
/**
 * @generated MessageType for protobuf message micromas.Empty
 */
export const Empty = new Empty$Type();
// @generated message type with reflection information, may provide speed optimized methods
class VersionResponse$Type extends MessageType<VersionResponse> {
    constructor() {
        super("micromas.VersionResponse", [
            { no: 1, name: "version", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message micromas.VersionResponse
 */
export const VersionResponse = new VersionResponse$Type();
