// @generated by protobuf-ts 2.9.4 with parameter use_proto_field_name,add_pb_suffix,force_optimize_code_size,ts_nocheck,long_type_string
// @generated from protobuf file "date.proto" (package "central.types", syntax proto2)
// tslint:disable
// @ts-nocheck
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message central.types.MasDate
 */
export interface MasDate {
    /**
     * Represents seconds of UTC time since Unix epoch
     * 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
     * 9999-12-31T23:59:59Z inclusive.
     * RFC3339     = "2006-01-02T15:04:05Z07:00"
     *
     * @generated from protobuf field: string datetime = 1;
     */
    datetime: string; // RFC3339
}
/**
 * @generated from protobuf message central.types.MasDateTime
 */
export interface MasDateTime {
    /**
     * Represents seconds of UTC time since Unix epoch
     * 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
     * 9999-12-31T23:59:59Z inclusive.
     * RFC3339     = "2006-01-02T15:04:05Z07:00"
     *
     * @generated from protobuf field: string datetime = 1;
     */
    datetime: string; // RFC3339
}
// @generated message type with reflection information, may provide speed optimized methods
class MasDate$Type extends MessageType<MasDate> {
    constructor() {
        super("central.types.MasDate", [
            { no: 1, name: "datetime", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message central.types.MasDate
 */
export const MasDate = new MasDate$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MasDateTime$Type extends MessageType<MasDateTime> {
    constructor() {
        super("central.types.MasDateTime", [
            { no: 1, name: "datetime", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message central.types.MasDateTime
 */
export const MasDateTime = new MasDateTime$Type();
