// @generated by protobuf-ts 2.11.1 with parameter use_proto_field_name,add_pb_suffix,force_optimize_code_size,ts_nocheck,long_type_string
// @generated from protobuf file "GoAuth.proto" (package "GoAuth", syntax proto2)
// tslint:disable
// @ts-nocheck
import { GoAuth } from "./GoAuth_pb";
import type { DEPARTMENTIID } from "./GoAuth_pb";
import type { USERDEPARTMENTSMESG } from "./GoAuth_pb";
import type { USERDEPARTMENTSRES } from "./GoAuth_pb";
import type { GETUSERDEPARTMENTSREQ } from "./GoAuth_pb";
import type { AllDEPARTMENTS } from "./GoAuth_pb";
import type { GETDEPARTMENTSFILTER } from "./GoAuth_pb";
import type { CLIENT_ID_REQ } from "./GoAuth_pb";
import type { MessageResponse } from "./GoAuth_pb";
import type { TAX_CLIENT_ID_REQ } from "./GoAuth_pb";
import type { ALL_TAX_CLIENT_IDS } from "./GoAuth_pb";
import type { UserArry } from "./GoAuth_pb";
import type { UserToProfileRq } from "./GoAuth_pb";
import type { DeleteProfileReq } from "./GoAuth_pb";
import type { ProfileId } from "./GoAuth_pb";
import type { All_PROFILES } from "./GoAuth_pb";
import type { ProfileResponse } from "./GoAuth_pb";
import type { AddProfilesRequest } from "./GoAuth_pb";
import type { GetAllADMINSResponse } from "./GoAuth_pb";
import type { GetAdminRequest } from "./GoAuth_pb";
import type { ADMINS } from "./GoAuth_pb";
import type { ResetAdminPassRequest } from "./GoAuth_pb";
import type { UpdateProfileRequest } from "./GoAuth_pb";
import type { AdminRegisterRequest } from "./GoAuth_pb";
import type { GetlientSCountsResponse } from "./GoAuth_pb";
import type { MicroUpdateRequest } from "./GoAuth_pb";
import type { Min_USER_STATIONS } from "./GoAuth_pb";
import type { AllDataResponse } from "./GoAuth_pb";
import type { AllDataRequest } from "./GoAuth_pb";
import type { CustRequest } from "./GoAuth_pb";
import type { ActivationRequest } from "./GoAuth_pb";
import type { CLIENTS } from "./GoAuth_pb";
import type { GetClientRequest } from "./GoAuth_pb";
import type { AddRelatedCustkeyRequest } from "./GoAuth_pb";
import type { CashierRequest } from "./GoAuth_pb";
import type { access_contraint_response } from "./GoAuth_pb";
import type { ResetPassRequest } from "./GoAuth_pb";
import type { USERS } from "./GoAuth_pb";
import type { GetUserByNameRequest } from "./GoAuth_pb";
import type { GetUserRequest } from "./GoAuth_pb";
import type { PassUserRequest } from "./GoAuth_pb";
import type { RegisterUserRequest } from "./GoAuth_pb";
import type { GetAllUserResponse } from "./GoAuth_pb";
import type { GetUserProfileResponse } from "./GoAuth_pb";
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { login } from "./GoAuth_pb";
import type { licenceResponse } from "./GoAuth_pb";
import type { GetCountsResponse } from "./GoAuth_pb";
import type { GetCountsRequest } from "./GoAuth_pb";
import type { GetAllSitesResponse } from "./GoAuth_pb";
import type { Emptymessage } from "./GoAuth_pb";
import type { ForgetRequest } from "./GoAuth_pb";
import type { ValRequest } from "./GoAuth_pb";
import type { RegisterRequest } from "./GoAuth_pb";
import type { SignInWithRequest } from "./GoAuth_pb";
import type { AdminSignInRequest } from "./GoAuth_pb";
import type { RegisterResponse } from "./GoAuth_pb";
import type { RELATED_ACOUNTS } from "./GoAuth_pb";
import type { SignInResponse } from "./GoAuth_pb";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { LoginResponse } from "./GoAuth_pb";
import type { LoginRequest } from "./GoAuth_pb";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service GoAuth.login
 */
export interface IloginClient {
    // SignIn

    /**
     * @generated from protobuf rpc: SignIn
     */
    signIn(input: LoginRequest, options?: RpcOptions): UnaryCall<LoginRequest, LoginResponse>;
    /**
     * @generated from protobuf rpc: SignInWithProfile
     */
    signInWithProfile(input: LoginRequest, options?: RpcOptions): UnaryCall<LoginRequest, SignInResponse>;
    /**
     * @generated from protobuf rpc: LinkeWith
     */
    linkeWith(input: RELATED_ACOUNTS, options?: RpcOptions): UnaryCall<RELATED_ACOUNTS, RegisterResponse>;
    /**
     * @generated from protobuf rpc: AdminSignIn
     */
    adminSignIn(input: AdminSignInRequest, options?: RpcOptions): UnaryCall<AdminSignInRequest, LoginResponse>;
    /**
     * @generated from protobuf rpc: SignInWith
     */
    signInWith(input: SignInWithRequest, options?: RpcOptions): UnaryCall<SignInWithRequest, LoginResponse>;
    // Register portal

    /**
     * @generated from protobuf rpc: Register
     */
    register(input: RegisterRequest, options?: RpcOptions): UnaryCall<RegisterRequest, RegisterResponse>;
    /**
     * @generated from protobuf rpc: validatecode
     */
    validatecode(input: ValRequest, options?: RpcOptions): UnaryCall<ValRequest, RegisterResponse>;
    // ForgetPass portal

    /**
     * @generated from protobuf rpc: ForgetPass
     */
    forgetPass(input: ForgetRequest, options?: RpcOptions): UnaryCall<ForgetRequest, RegisterResponse>;
    // backend

    /**
     * @generated from protobuf rpc: GetCrmAppSignInToken
     */
    getCrmAppSignInToken(input: Emptymessage, options?: RpcOptions): UnaryCall<Emptymessage, LoginResponse>;
    /**
     * @generated from protobuf rpc: GetNotifSignInToken
     */
    getNotifSignInToken(input: Emptymessage, options?: RpcOptions): UnaryCall<Emptymessage, LoginResponse>;
    // lookups

    /**
     * @generated from protobuf rpc: GetAllSites
     */
    getAllSites(input: Emptymessage, options?: RpcOptions): UnaryCall<Emptymessage, GetAllSitesResponse>;
    /**
     * @generated from protobuf rpc: GetCounts
     */
    getCounts(input: GetCountsRequest, options?: RpcOptions): UnaryCall<GetCountsRequest, GetCountsResponse>;
    /**
     * @generated from protobuf rpc: GetLicence
     */
    getLicence(input: Emptymessage, options?: RpcOptions): UnaryCall<Emptymessage, licenceResponse>;
}
/**
 * @generated from protobuf service GoAuth.login
 */
export class loginClient implements IloginClient, ServiceInfo {
    typeName = login.typeName;
    methods = login.methods;
    options = login.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    // SignIn

    /**
     * @generated from protobuf rpc: SignIn
     */
    signIn(input: LoginRequest, options?: RpcOptions): UnaryCall<LoginRequest, LoginResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<LoginRequest, LoginResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SignInWithProfile
     */
    signInWithProfile(input: LoginRequest, options?: RpcOptions): UnaryCall<LoginRequest, SignInResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<LoginRequest, SignInResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: LinkeWith
     */
    linkeWith(input: RELATED_ACOUNTS, options?: RpcOptions): UnaryCall<RELATED_ACOUNTS, RegisterResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<RELATED_ACOUNTS, RegisterResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AdminSignIn
     */
    adminSignIn(input: AdminSignInRequest, options?: RpcOptions): UnaryCall<AdminSignInRequest, LoginResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<AdminSignInRequest, LoginResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SignInWith
     */
    signInWith(input: SignInWithRequest, options?: RpcOptions): UnaryCall<SignInWithRequest, LoginResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<SignInWithRequest, LoginResponse>("unary", this._transport, method, opt, input);
    }
    // Register portal

    /**
     * @generated from protobuf rpc: Register
     */
    register(input: RegisterRequest, options?: RpcOptions): UnaryCall<RegisterRequest, RegisterResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegisterRequest, RegisterResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: validatecode
     */
    validatecode(input: ValRequest, options?: RpcOptions): UnaryCall<ValRequest, RegisterResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<ValRequest, RegisterResponse>("unary", this._transport, method, opt, input);
    }
    // ForgetPass portal

    /**
     * @generated from protobuf rpc: ForgetPass
     */
    forgetPass(input: ForgetRequest, options?: RpcOptions): UnaryCall<ForgetRequest, RegisterResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<ForgetRequest, RegisterResponse>("unary", this._transport, method, opt, input);
    }
    // backend

    /**
     * @generated from protobuf rpc: GetCrmAppSignInToken
     */
    getCrmAppSignInToken(input: Emptymessage, options?: RpcOptions): UnaryCall<Emptymessage, LoginResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<Emptymessage, LoginResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetNotifSignInToken
     */
    getNotifSignInToken(input: Emptymessage, options?: RpcOptions): UnaryCall<Emptymessage, LoginResponse> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<Emptymessage, LoginResponse>("unary", this._transport, method, opt, input);
    }
    // lookups

    /**
     * @generated from protobuf rpc: GetAllSites
     */
    getAllSites(input: Emptymessage, options?: RpcOptions): UnaryCall<Emptymessage, GetAllSitesResponse> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<Emptymessage, GetAllSitesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCounts
     */
    getCounts(input: GetCountsRequest, options?: RpcOptions): UnaryCall<GetCountsRequest, GetCountsResponse> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetCountsRequest, GetCountsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetLicence
     */
    getLicence(input: Emptymessage, options?: RpcOptions): UnaryCall<Emptymessage, licenceResponse> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return stackIntercept<Emptymessage, licenceResponse>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service GoAuth.GoAuth
 */
export interface IGoAuthClient {
    // User

    /**
     * @generated from protobuf rpc: GetUserProfile
     */
    getUserProfile(input: Emptymessage, options?: RpcOptions): UnaryCall<Emptymessage, GetUserProfileResponse>;
    /**
     * @generated from protobuf rpc: GetAllUser
     */
    getAllUser(input: Emptymessage, options?: RpcOptions): UnaryCall<Emptymessage, GetAllUserResponse>;
    /**
     * @generated from protobuf rpc: RegisterUser
     */
    registerUser(input: RegisterUserRequest, options?: RpcOptions): UnaryCall<RegisterUserRequest, RegisterResponse>;
    /**
     * @generated from protobuf rpc: UpdateUser
     */
    updateUser(input: RegisterUserRequest, options?: RpcOptions): UnaryCall<RegisterUserRequest, RegisterResponse>;
    /**
     * @generated from protobuf rpc: UpdateUserpass
     */
    updateUserpass(input: PassUserRequest, options?: RpcOptions): UnaryCall<PassUserRequest, RegisterResponse>;
    /**
     * @generated from protobuf rpc: GetUserbyid
     */
    getUserbyid(input: GetUserRequest, options?: RpcOptions): UnaryCall<GetUserRequest, GetUserProfileResponse>;
    /**
     * @generated from protobuf rpc: GetUserbyUserName
     */
    getUserbyUserName(input: GetUserByNameRequest, options?: RpcOptions): UnaryCall<GetUserByNameRequest, GetUserProfileResponse>;
    /**
     * @generated from protobuf rpc: DeleteUser
     */
    deleteUser(input: USERS, options?: RpcOptions): UnaryCall<USERS, RegisterResponse>;
    /**
     * @generated from protobuf rpc: ResetPass
     */
    resetPass(input: ResetPassRequest, options?: RpcOptions): UnaryCall<ResetPassRequest, RegisterResponse>;
    /**
     * @generated from protobuf rpc: GetUsetAccessContraint
     */
    getUsetAccessContraint(input: Emptymessage, options?: RpcOptions): UnaryCall<Emptymessage, access_contraint_response>;
    /**
     * @generated from protobuf rpc: GetUserByCashier
     */
    getUserByCashier(input: CashierRequest, options?: RpcOptions): UnaryCall<CashierRequest, GetUserProfileResponse>;
    // clint

    /**
     * @generated from protobuf rpc: AddRelatedCustkey
     */
    addRelatedCustkey(input: AddRelatedCustkeyRequest, options?: RpcOptions): UnaryCall<AddRelatedCustkeyRequest, RegisterResponse>;
    /**
     * @generated from protobuf rpc: UpdateProfile
     */
    updateProfile(input: RegisterRequest, options?: RpcOptions): UnaryCall<RegisterRequest, RegisterResponse>;
    /**
     * @generated from protobuf rpc: GetClientbyid
     */
    getClientbyid(input: GetClientRequest, options?: RpcOptions): UnaryCall<GetClientRequest, CLIENTS>;
    /**
     * @generated from protobuf rpc: Activation
     */
    activation(input: ActivationRequest, options?: RpcOptions): UnaryCall<ActivationRequest, RegisterResponse>;
    /**
     * @generated from protobuf rpc: ResendActivation
     */
    resendActivation(input: Emptymessage, options?: RpcOptions): UnaryCall<Emptymessage, RegisterResponse>;
    /**
     * @generated from protobuf rpc: GetClientProfile
     */
    getClientProfile(input: Emptymessage, options?: RpcOptions): UnaryCall<Emptymessage, CLIENTS>;
    /**
     * @generated from protobuf rpc: GetClientbyCustkey
     */
    getClientbyCustkey(input: CustRequest, options?: RpcOptions): UnaryCall<CustRequest, CLIENTS>;
    /**
     * @generated from protobuf rpc: GetAllData
     */
    getAllData(input: AllDataRequest, options?: RpcOptions): UnaryCall<AllDataRequest, AllDataResponse>;
    /**
     * @generated from protobuf rpc: RefreshToken
     */
    refreshToken(input: Emptymessage, options?: RpcOptions): UnaryCall<Emptymessage, RegisterResponse>;
    /**
     * @generated from protobuf rpc: RefreshTokenWithNewSt
     */
    refreshTokenWithNewSt(input: Min_USER_STATIONS, options?: RpcOptions): UnaryCall<Min_USER_STATIONS, RegisterResponse>;
    /**
     * @generated from protobuf rpc: MIcroUpdateClient
     */
    mIcroUpdateClient(input: MicroUpdateRequest, options?: RpcOptions): UnaryCall<MicroUpdateRequest, RegisterResponse>;
    /**
     * @generated from protobuf rpc: GetClientSCounts
     */
    getClientSCounts(input: Emptymessage, options?: RpcOptions): UnaryCall<Emptymessage, GetlientSCountsResponse>;
    // admin

    /**
     * @generated from protobuf rpc: AdminRegister
     */
    adminRegister(input: AdminRegisterRequest, options?: RpcOptions): UnaryCall<AdminRegisterRequest, RegisterResponse>;
    /**
     * @generated from protobuf rpc: AdminUpdateProfile
     */
    adminUpdateProfile(input: UpdateProfileRequest, options?: RpcOptions): UnaryCall<UpdateProfileRequest, RegisterResponse>;
    /**
     * @generated from protobuf rpc: UpdateAdminpass
     */
    updateAdminpass(input: PassUserRequest, options?: RpcOptions): UnaryCall<PassUserRequest, RegisterResponse>;
    /**
     * @generated from protobuf rpc: ResetAdminPass
     */
    resetAdminPass(input: ResetAdminPassRequest, options?: RpcOptions): UnaryCall<ResetAdminPassRequest, RegisterResponse>;
    /**
     * @generated from protobuf rpc: AdminGetProfile
     */
    adminGetProfile(input: Emptymessage, options?: RpcOptions): UnaryCall<Emptymessage, ADMINS>;
    /**
     * @generated from protobuf rpc: GetAdminbyid
     */
    getAdminbyid(input: GetAdminRequest, options?: RpcOptions): UnaryCall<GetAdminRequest, ADMINS>;
    /**
     * @generated from protobuf rpc: GetAllAdmin
     */
    getAllAdmin(input: Emptymessage, options?: RpcOptions): UnaryCall<Emptymessage, GetAllADMINSResponse>;
    /**
     * @generated from protobuf rpc: DeleteAdmin
     */
    deleteAdmin(input: GetAdminRequest, options?: RpcOptions): UnaryCall<GetAdminRequest, RegisterResponse>;
    /**
     * @generated from protobuf rpc: AddTesterByAdmin
     */
    addTesterByAdmin(input: GetClientRequest, options?: RpcOptions): UnaryCall<GetClientRequest, RegisterResponse>;
    // users management
    // PROFILES

    /**
     * @generated from protobuf rpc: EditProfile
     */
    editProfile(input: AddProfilesRequest, options?: RpcOptions): UnaryCall<AddProfilesRequest, ProfileResponse>;
    /**
     * @generated from protobuf rpc: GetAllProfiles
     */
    getAllProfiles(input: Emptymessage, options?: RpcOptions): UnaryCall<Emptymessage, All_PROFILES>;
    /**
     * @generated from protobuf rpc: GetProfile
     */
    getProfile(input: ProfileId, options?: RpcOptions): UnaryCall<ProfileId, All_PROFILES>;
    /**
     * @generated from protobuf rpc: DeleteProfile
     */
    deleteProfile(input: ProfileId, options?: RpcOptions): UnaryCall<ProfileId, ProfileResponse>;
    /**
     * @generated from protobuf rpc: DeleteLinkedProfile
     */
    deleteLinkedProfile(input: DeleteProfileReq, options?: RpcOptions): UnaryCall<DeleteProfileReq, ProfileResponse>;
    /**
     * @generated from protobuf rpc: UserToProfile
     */
    userToProfile(input: UserToProfileRq, options?: RpcOptions): UnaryCall<UserToProfileRq, ProfileResponse>;
    /**
     * @generated from protobuf rpc: GetUsersByProfile
     */
    getUsersByProfile(input: ProfileId, options?: RpcOptions): UnaryCall<ProfileId, UserArry>;
    /**
     * @generated from protobuf rpc: GetUsersProfiles
     */
    getUsersProfiles(input: GetUserRequest, options?: RpcOptions): UnaryCall<GetUserRequest, All_PROFILES>;
    /**
     * TAX CLIENT IDS
     *
     * @generated from protobuf rpc: GetAllTaxClientIds
     */
    getAllTaxClientIds(input: Emptymessage, options?: RpcOptions): UnaryCall<Emptymessage, ALL_TAX_CLIENT_IDS>;
    /**
     * @generated from protobuf rpc: EditTaxClientId
     */
    editTaxClientId(input: TAX_CLIENT_ID_REQ, options?: RpcOptions): UnaryCall<TAX_CLIENT_ID_REQ, MessageResponse>;
    /**
     * @generated from protobuf rpc: DeleteTaxClientId
     */
    deleteTaxClientId(input: CLIENT_ID_REQ, options?: RpcOptions): UnaryCall<CLIENT_ID_REQ, MessageResponse>;
    /**
     * USER DEPARTMENTS
     *
     * @generated from protobuf rpc: GetAllDepartments
     */
    getAllDepartments(input: GETDEPARTMENTSFILTER, options?: RpcOptions): UnaryCall<GETDEPARTMENTSFILTER, AllDEPARTMENTS>;
    /**
     * @generated from protobuf rpc: GetUserDepartments
     */
    getUserDepartments(input: GETUSERDEPARTMENTSREQ, options?: RpcOptions): UnaryCall<GETUSERDEPARTMENTSREQ, USERDEPARTMENTSRES>;
    /**
     * @generated from protobuf rpc: EditUserDepartments
     */
    editUserDepartments(input: USERDEPARTMENTSMESG, options?: RpcOptions): UnaryCall<USERDEPARTMENTSMESG, MessageResponse>;
    /**
     * @generated from protobuf rpc: DeleteUserDepartments
     */
    deleteUserDepartments(input: DEPARTMENTIID, options?: RpcOptions): UnaryCall<DEPARTMENTIID, MessageResponse>;
}
/**
 * @generated from protobuf service GoAuth.GoAuth
 */
export class GoAuthClient implements IGoAuthClient, ServiceInfo {
    typeName = GoAuth.typeName;
    methods = GoAuth.methods;
    options = GoAuth.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    // User

    /**
     * @generated from protobuf rpc: GetUserProfile
     */
    getUserProfile(input: Emptymessage, options?: RpcOptions): UnaryCall<Emptymessage, GetUserProfileResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<Emptymessage, GetUserProfileResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAllUser
     */
    getAllUser(input: Emptymessage, options?: RpcOptions): UnaryCall<Emptymessage, GetAllUserResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<Emptymessage, GetAllUserResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RegisterUser
     */
    registerUser(input: RegisterUserRequest, options?: RpcOptions): UnaryCall<RegisterUserRequest, RegisterResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegisterUserRequest, RegisterResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateUser
     */
    updateUser(input: RegisterUserRequest, options?: RpcOptions): UnaryCall<RegisterUserRequest, RegisterResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegisterUserRequest, RegisterResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateUserpass
     */
    updateUserpass(input: PassUserRequest, options?: RpcOptions): UnaryCall<PassUserRequest, RegisterResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<PassUserRequest, RegisterResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetUserbyid
     */
    getUserbyid(input: GetUserRequest, options?: RpcOptions): UnaryCall<GetUserRequest, GetUserProfileResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetUserRequest, GetUserProfileResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetUserbyUserName
     */
    getUserbyUserName(input: GetUserByNameRequest, options?: RpcOptions): UnaryCall<GetUserByNameRequest, GetUserProfileResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetUserByNameRequest, GetUserProfileResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteUser
     */
    deleteUser(input: USERS, options?: RpcOptions): UnaryCall<USERS, RegisterResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<USERS, RegisterResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ResetPass
     */
    resetPass(input: ResetPassRequest, options?: RpcOptions): UnaryCall<ResetPassRequest, RegisterResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<ResetPassRequest, RegisterResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetUsetAccessContraint
     */
    getUsetAccessContraint(input: Emptymessage, options?: RpcOptions): UnaryCall<Emptymessage, access_contraint_response> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<Emptymessage, access_contraint_response>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetUserByCashier
     */
    getUserByCashier(input: CashierRequest, options?: RpcOptions): UnaryCall<CashierRequest, GetUserProfileResponse> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<CashierRequest, GetUserProfileResponse>("unary", this._transport, method, opt, input);
    }
    // clint

    /**
     * @generated from protobuf rpc: AddRelatedCustkey
     */
    addRelatedCustkey(input: AddRelatedCustkeyRequest, options?: RpcOptions): UnaryCall<AddRelatedCustkeyRequest, RegisterResponse> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddRelatedCustkeyRequest, RegisterResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateProfile
     */
    updateProfile(input: RegisterRequest, options?: RpcOptions): UnaryCall<RegisterRequest, RegisterResponse> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegisterRequest, RegisterResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetClientbyid
     */
    getClientbyid(input: GetClientRequest, options?: RpcOptions): UnaryCall<GetClientRequest, CLIENTS> {
        const method = this.methods[13], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetClientRequest, CLIENTS>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Activation
     */
    activation(input: ActivationRequest, options?: RpcOptions): UnaryCall<ActivationRequest, RegisterResponse> {
        const method = this.methods[14], opt = this._transport.mergeOptions(options);
        return stackIntercept<ActivationRequest, RegisterResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ResendActivation
     */
    resendActivation(input: Emptymessage, options?: RpcOptions): UnaryCall<Emptymessage, RegisterResponse> {
        const method = this.methods[15], opt = this._transport.mergeOptions(options);
        return stackIntercept<Emptymessage, RegisterResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetClientProfile
     */
    getClientProfile(input: Emptymessage, options?: RpcOptions): UnaryCall<Emptymessage, CLIENTS> {
        const method = this.methods[16], opt = this._transport.mergeOptions(options);
        return stackIntercept<Emptymessage, CLIENTS>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetClientbyCustkey
     */
    getClientbyCustkey(input: CustRequest, options?: RpcOptions): UnaryCall<CustRequest, CLIENTS> {
        const method = this.methods[17], opt = this._transport.mergeOptions(options);
        return stackIntercept<CustRequest, CLIENTS>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAllData
     */
    getAllData(input: AllDataRequest, options?: RpcOptions): UnaryCall<AllDataRequest, AllDataResponse> {
        const method = this.methods[18], opt = this._transport.mergeOptions(options);
        return stackIntercept<AllDataRequest, AllDataResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RefreshToken
     */
    refreshToken(input: Emptymessage, options?: RpcOptions): UnaryCall<Emptymessage, RegisterResponse> {
        const method = this.methods[19], opt = this._transport.mergeOptions(options);
        return stackIntercept<Emptymessage, RegisterResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RefreshTokenWithNewSt
     */
    refreshTokenWithNewSt(input: Min_USER_STATIONS, options?: RpcOptions): UnaryCall<Min_USER_STATIONS, RegisterResponse> {
        const method = this.methods[20], opt = this._transport.mergeOptions(options);
        return stackIntercept<Min_USER_STATIONS, RegisterResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: MIcroUpdateClient
     */
    mIcroUpdateClient(input: MicroUpdateRequest, options?: RpcOptions): UnaryCall<MicroUpdateRequest, RegisterResponse> {
        const method = this.methods[21], opt = this._transport.mergeOptions(options);
        return stackIntercept<MicroUpdateRequest, RegisterResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetClientSCounts
     */
    getClientSCounts(input: Emptymessage, options?: RpcOptions): UnaryCall<Emptymessage, GetlientSCountsResponse> {
        const method = this.methods[22], opt = this._transport.mergeOptions(options);
        return stackIntercept<Emptymessage, GetlientSCountsResponse>("unary", this._transport, method, opt, input);
    }
    // admin

    /**
     * @generated from protobuf rpc: AdminRegister
     */
    adminRegister(input: AdminRegisterRequest, options?: RpcOptions): UnaryCall<AdminRegisterRequest, RegisterResponse> {
        const method = this.methods[23], opt = this._transport.mergeOptions(options);
        return stackIntercept<AdminRegisterRequest, RegisterResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AdminUpdateProfile
     */
    adminUpdateProfile(input: UpdateProfileRequest, options?: RpcOptions): UnaryCall<UpdateProfileRequest, RegisterResponse> {
        const method = this.methods[24], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateProfileRequest, RegisterResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateAdminpass
     */
    updateAdminpass(input: PassUserRequest, options?: RpcOptions): UnaryCall<PassUserRequest, RegisterResponse> {
        const method = this.methods[25], opt = this._transport.mergeOptions(options);
        return stackIntercept<PassUserRequest, RegisterResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ResetAdminPass
     */
    resetAdminPass(input: ResetAdminPassRequest, options?: RpcOptions): UnaryCall<ResetAdminPassRequest, RegisterResponse> {
        const method = this.methods[26], opt = this._transport.mergeOptions(options);
        return stackIntercept<ResetAdminPassRequest, RegisterResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AdminGetProfile
     */
    adminGetProfile(input: Emptymessage, options?: RpcOptions): UnaryCall<Emptymessage, ADMINS> {
        const method = this.methods[27], opt = this._transport.mergeOptions(options);
        return stackIntercept<Emptymessage, ADMINS>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAdminbyid
     */
    getAdminbyid(input: GetAdminRequest, options?: RpcOptions): UnaryCall<GetAdminRequest, ADMINS> {
        const method = this.methods[28], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAdminRequest, ADMINS>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAllAdmin
     */
    getAllAdmin(input: Emptymessage, options?: RpcOptions): UnaryCall<Emptymessage, GetAllADMINSResponse> {
        const method = this.methods[29], opt = this._transport.mergeOptions(options);
        return stackIntercept<Emptymessage, GetAllADMINSResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteAdmin
     */
    deleteAdmin(input: GetAdminRequest, options?: RpcOptions): UnaryCall<GetAdminRequest, RegisterResponse> {
        const method = this.methods[30], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAdminRequest, RegisterResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AddTesterByAdmin
     */
    addTesterByAdmin(input: GetClientRequest, options?: RpcOptions): UnaryCall<GetClientRequest, RegisterResponse> {
        const method = this.methods[31], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetClientRequest, RegisterResponse>("unary", this._transport, method, opt, input);
    }
    // users management
    // PROFILES

    /**
     * @generated from protobuf rpc: EditProfile
     */
    editProfile(input: AddProfilesRequest, options?: RpcOptions): UnaryCall<AddProfilesRequest, ProfileResponse> {
        const method = this.methods[32], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddProfilesRequest, ProfileResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAllProfiles
     */
    getAllProfiles(input: Emptymessage, options?: RpcOptions): UnaryCall<Emptymessage, All_PROFILES> {
        const method = this.methods[33], opt = this._transport.mergeOptions(options);
        return stackIntercept<Emptymessage, All_PROFILES>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetProfile
     */
    getProfile(input: ProfileId, options?: RpcOptions): UnaryCall<ProfileId, All_PROFILES> {
        const method = this.methods[34], opt = this._transport.mergeOptions(options);
        return stackIntercept<ProfileId, All_PROFILES>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteProfile
     */
    deleteProfile(input: ProfileId, options?: RpcOptions): UnaryCall<ProfileId, ProfileResponse> {
        const method = this.methods[35], opt = this._transport.mergeOptions(options);
        return stackIntercept<ProfileId, ProfileResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteLinkedProfile
     */
    deleteLinkedProfile(input: DeleteProfileReq, options?: RpcOptions): UnaryCall<DeleteProfileReq, ProfileResponse> {
        const method = this.methods[36], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteProfileReq, ProfileResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UserToProfile
     */
    userToProfile(input: UserToProfileRq, options?: RpcOptions): UnaryCall<UserToProfileRq, ProfileResponse> {
        const method = this.methods[37], opt = this._transport.mergeOptions(options);
        return stackIntercept<UserToProfileRq, ProfileResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetUsersByProfile
     */
    getUsersByProfile(input: ProfileId, options?: RpcOptions): UnaryCall<ProfileId, UserArry> {
        const method = this.methods[38], opt = this._transport.mergeOptions(options);
        return stackIntercept<ProfileId, UserArry>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetUsersProfiles
     */
    getUsersProfiles(input: GetUserRequest, options?: RpcOptions): UnaryCall<GetUserRequest, All_PROFILES> {
        const method = this.methods[39], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetUserRequest, All_PROFILES>("unary", this._transport, method, opt, input);
    }
    /**
     * TAX CLIENT IDS
     *
     * @generated from protobuf rpc: GetAllTaxClientIds
     */
    getAllTaxClientIds(input: Emptymessage, options?: RpcOptions): UnaryCall<Emptymessage, ALL_TAX_CLIENT_IDS> {
        const method = this.methods[40], opt = this._transport.mergeOptions(options);
        return stackIntercept<Emptymessage, ALL_TAX_CLIENT_IDS>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: EditTaxClientId
     */
    editTaxClientId(input: TAX_CLIENT_ID_REQ, options?: RpcOptions): UnaryCall<TAX_CLIENT_ID_REQ, MessageResponse> {
        const method = this.methods[41], opt = this._transport.mergeOptions(options);
        return stackIntercept<TAX_CLIENT_ID_REQ, MessageResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteTaxClientId
     */
    deleteTaxClientId(input: CLIENT_ID_REQ, options?: RpcOptions): UnaryCall<CLIENT_ID_REQ, MessageResponse> {
        const method = this.methods[42], opt = this._transport.mergeOptions(options);
        return stackIntercept<CLIENT_ID_REQ, MessageResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * USER DEPARTMENTS
     *
     * @generated from protobuf rpc: GetAllDepartments
     */
    getAllDepartments(input: GETDEPARTMENTSFILTER, options?: RpcOptions): UnaryCall<GETDEPARTMENTSFILTER, AllDEPARTMENTS> {
        const method = this.methods[43], opt = this._transport.mergeOptions(options);
        return stackIntercept<GETDEPARTMENTSFILTER, AllDEPARTMENTS>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetUserDepartments
     */
    getUserDepartments(input: GETUSERDEPARTMENTSREQ, options?: RpcOptions): UnaryCall<GETUSERDEPARTMENTSREQ, USERDEPARTMENTSRES> {
        const method = this.methods[44], opt = this._transport.mergeOptions(options);
        return stackIntercept<GETUSERDEPARTMENTSREQ, USERDEPARTMENTSRES>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: EditUserDepartments
     */
    editUserDepartments(input: USERDEPARTMENTSMESG, options?: RpcOptions): UnaryCall<USERDEPARTMENTSMESG, MessageResponse> {
        const method = this.methods[45], opt = this._transport.mergeOptions(options);
        return stackIntercept<USERDEPARTMENTSMESG, MessageResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteUserDepartments
     */
    deleteUserDepartments(input: DEPARTMENTIID, options?: RpcOptions): UnaryCall<DEPARTMENTIID, MessageResponse> {
        const method = this.methods[46], opt = this._transport.mergeOptions(options);
        return stackIntercept<DEPARTMENTIID, MessageResponse>("unary", this._transport, method, opt, input);
    }
}
