// @generated by protobuf-ts 2.9.4 with parameter use_proto_field_name,add_pb_suffix,force_optimize_code_size,ts_nocheck,long_type_string
// @generated from protobuf file "MasProvider.proto" (package "MasProvider", syntax proto2)
// tslint:disable
// @ts-nocheck
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
import { MasDateTime } from "./date_pb";
/**
 * @generated from protobuf message MasProvider.ArrSITES
 */
export interface ArrSITES {
    /**
     * @generated from protobuf field: repeated MasProvider.SITES sITES = 1;
     */
    sITES: SITES[];
}
/**
 * @generated from protobuf message MasProvider.SITES
 */
export interface SITES {
    /**
     * @generated from protobuf field: optional int32 CODE = 1 [json_name = "CODE"];
     */
    CODE?: number; // @gotags: gorm:"primaryKey"
    /**
     * @generated from protobuf field: optional string DESCRIBE = 2 [json_name = "DESCRIBE"];
     */
    DESCRIBE?: string;
    /**
     * @generated from protobuf field: optional bool IS_ACTIVE = 3 [json_name = "ISACTIVE"];
     */
    IS_ACTIVE?: boolean;
    /**
     * @generated from protobuf field: optional int64 SEQ = 4 [json_name = "SEQ"];
     */
    SEQ?: string;
    /**
     * @generated from protobuf field: optional string BILLING_IP = 5 [json_name = "BILLINGIP"];
     */
    BILLING_IP?: string;
    /**
     * @generated from protobuf field: optional string BILLING_PASSWORD = 6 [json_name = "BILLINGPASSWORD"];
     */
    BILLING_PASSWORD?: string;
    /**
     * @generated from protobuf field: optional string BILLING_PORT_NO = 7 [json_name = "BILLINGPORTNO"];
     */
    BILLING_PORT_NO?: string;
    /**
     * @generated from protobuf field: optional string BILLING_USERNAME = 8 [json_name = "BILLINGUSERNAME"];
     */
    BILLING_USERNAME?: string;
    /**
     * @generated from protobuf field: MasProvider.PROJECT_TAGS PROJECT_TAG = 9 [json_name = "PROJECTTAG"];
     */
    PROJECT_TAG: PROJECT_TAGS; // @gotags: `gorm:"not null"`
    /**
     * @generated from protobuf field: optional string SITE_IMAGE = 10 [json_name = "SITEIMAGE"];
     */
    SITE_IMAGE?: string; // @gotags: gorm:"type:nvarchar(max)"
    /**
     * @generated from protobuf field: optional bool HAS_MAS = 11 [json_name = "HASMAS"];
     */
    HAS_MAS?: boolean;
    /**
     * @generated from protobuf field: optional string DESCRIBE_EN = 12 [json_name = "DESCRIBEEN"];
     */
    DESCRIBE_EN?: string;
}
/**
 * @generated from protobuf message MasProvider.GetSettingValueRq
 */
export interface GetSettingValueRq {
    /**
     * @generated from protobuf field: string keyword = 1;
     */
    keyword: string;
    /**
     * @generated from protobuf field: optional int32 SITE_CODE = 2 [json_name = "SITECODE"];
     */
    SITE_CODE?: number;
}
/**
 * @generated from protobuf message MasProvider.GetDepartmentRq
 */
export interface GetDepartmentRq {
    /**
     * @generated from protobuf field: int64 departmentID = 1;
     */
    departmentID: string;
}
/**
 * @generated from protobuf message MasProvider.StationRq
 */
export interface StationRq {
    /**
     * @generated from protobuf field: int64 SiteCode = 1 [json_name = "SiteCode"];
     */
    SiteCode: string;
    /**
     * @generated from protobuf field: int64 StationNo = 2 [json_name = "StationNo"];
     */
    StationNo: string;
}
/**
 * @generated from protobuf message MasProvider.SiteCode
 */
export interface SiteCode {
    /**
     * @generated from protobuf field: optional int32 code = 1;
     */
    code?: number;
}
/**
 * @generated from protobuf message MasProvider.STATIONS
 */
export interface STATIONS {
    /**
     * @generated from protobuf field: optional int64 SITE_CODE = 1 [json_name = "SITECODE"];
     */
    SITE_CODE?: string; // @gotags: gorm:"-"
    /**
     * @generated from protobuf field: int64 STATION_NO = 2 [json_name = "STATIONNO"];
     */
    STATION_NO: string; // @gotags: gorm:"primaryKey"
    /**
     * @generated from protobuf field: optional string NAME = 3 [json_name = "NAME"];
     */
    NAME?: string;
    /**
     * @generated from protobuf field: optional string DESCRIPTION = 4 [json_name = "DESCRIPTION"];
     */
    DESCRIPTION?: string;
    /**
     * @generated from protobuf field: optional int64 ISCURRENT = 5 [json_name = "ISCURRENT"];
     */
    ISCURRENT?: string;
    /**
     * @generated from protobuf field: optional int64 DB_STANDALONE = 6 [json_name = "DBSTANDALONE"];
     */
    DB_STANDALONE?: string;
    /**
     * @generated from protobuf field: optional int64 DB_ACCESS = 7 [json_name = "DBACCESS"];
     */
    DB_ACCESS?: string;
    /**
     * @generated from protobuf field: optional int64 IS_HEADQUARTERS = 8 [json_name = "ISHEADQUARTERS"];
     */
    IS_HEADQUARTERS?: string;
    /**
     * @generated from protobuf field: optional int64 IS_MAINTSITE = 9 [json_name = "ISMAINTSITE"];
     */
    IS_MAINTSITE?: string;
    /**
     * @generated from protobuf field: optional int64 IS_MRREADING = 10 [json_name = "ISMRREADING"];
     */
    IS_MRREADING?: string;
    /**
     * @generated from protobuf field: optional int64 IS_CSERVICES = 11 [json_name = "ISCSERVICES"];
     */
    IS_CSERVICES?: string;
    /**
     * @generated from protobuf field: optional int64 IS_RECEIPTING = 12 [json_name = "ISRECEIPTING"];
     */
    IS_RECEIPTING?: string;
    /**
     * @generated from protobuf field: optional string TEL_WORK = 13 [json_name = "TELWORK"];
     */
    TEL_WORK?: string;
    /**
     * @generated from protobuf field: optional string TEL_FAX = 14 [json_name = "TELFAX"];
     */
    TEL_FAX?: string;
    /**
     * @generated from protobuf field: optional string TEL_EMAIL = 15 [json_name = "TELEMAIL"];
     */
    TEL_EMAIL?: string;
    /**
     * @generated from protobuf field: optional string TEL_AHOURS = 16 [json_name = "TELAHOURS"];
     */
    TEL_AHOURS?: string;
    /**
     * @generated from protobuf field: optional string TEL_COMPL = 17 [json_name = "TELCOMPL"];
     */
    TEL_COMPL?: string;
    /**
     * @generated from protobuf field: optional string LN_ADDRESS1 = 18 [json_name = "LNADDRESS1"];
     */
    LN_ADDRESS1?: string;
    /**
     * @generated from protobuf field: optional string LN_ADDRESS2 = 19 [json_name = "LNADDRESS2"];
     */
    LN_ADDRESS2?: string;
    /**
     * @generated from protobuf field: optional string LN_ADDRESS3 = 20 [json_name = "LNADDRESS3"];
     */
    LN_ADDRESS3?: string;
    /**
     * @generated from protobuf field: optional string LN_CITY = 21 [json_name = "LNCITY"];
     */
    LN_CITY?: string;
    /**
     * @generated from protobuf field: optional int64 WORKING_MON = 22 [json_name = "WORKINGMON"];
     */
    WORKING_MON?: string;
    /**
     * @generated from protobuf field: optional int64 WORKING_TUE = 23 [json_name = "WORKINGTUE"];
     */
    WORKING_TUE?: string;
    /**
     * @generated from protobuf field: optional int64 WORKING_WED = 24 [json_name = "WORKINGWED"];
     */
    WORKING_WED?: string;
    /**
     * @generated from protobuf field: optional int64 WORKING_THU = 25 [json_name = "WORKINGTHU"];
     */
    WORKING_THU?: string;
    /**
     * @generated from protobuf field: optional int64 WORKING_FRI = 26 [json_name = "WORKINGFRI"];
     */
    WORKING_FRI?: string;
    /**
     * @generated from protobuf field: optional int64 WORKING_SAT = 27 [json_name = "WORKINGSAT"];
     */
    WORKING_SAT?: string;
    /**
     * @generated from protobuf field: optional int64 WORKING_SUN = 28 [json_name = "WORKINGSUN"];
     */
    WORKING_SUN?: string;
    /**
     * @generated from protobuf field: optional int64 OVERTIME_MON = 29 [json_name = "OVERTIMEMON"];
     */
    OVERTIME_MON?: string;
    /**
     * @generated from protobuf field: optional int64 OVERTIME_TUE = 30 [json_name = "OVERTIMETUE"];
     */
    OVERTIME_TUE?: string;
    /**
     * @generated from protobuf field: optional int64 OVERTIME_WED = 31 [json_name = "OVERTIMEWED"];
     */
    OVERTIME_WED?: string;
    /**
     * @generated from protobuf field: optional int64 OVERTIME_THU = 32 [json_name = "OVERTIMETHU"];
     */
    OVERTIME_THU?: string;
    /**
     * @generated from protobuf field: optional int64 OVERTIME_FRI = 33 [json_name = "OVERTIMEFRI"];
     */
    OVERTIME_FRI?: string;
    /**
     * @generated from protobuf field: optional int64 OVERTIME_SAT = 34 [json_name = "OVERTIMESAT"];
     */
    OVERTIME_SAT?: string;
    /**
     * @generated from protobuf field: optional int64 OVERTIME_SUN = 35 [json_name = "OVERTIMESUN"];
     */
    OVERTIME_SUN?: string;
    /**
     * @generated from protobuf field: optional string SITE_MEMO = 36 [json_name = "SITEMEMO"];
     */
    SITE_MEMO?: string;
    /**
     * @generated from protobuf field: optional central.types.MasDateTime STAMP_DATE = 37 [json_name = "STAMPDATE"];
     */
    STAMP_DATE?: MasDateTime;
    /**
     * @generated from protobuf field: optional string STAMP_USER = 38 [json_name = "STAMPUSER"];
     */
    STAMP_USER?: string;
    /**
     * @generated from protobuf field: optional int64 MAINTSITE_CODE = 39 [json_name = "MAINTSITECODE"];
     */
    MAINTSITE_CODE?: string;
    /**
     * @generated from protobuf field: optional int64 DEFAULTWAREHOUSE = 40 [json_name = "DEFAULTWAREHOUSE"];
     */
    DEFAULTWAREHOUSE?: string;
    /**
     * @generated from protobuf field: optional int64 DEFAULTDEPOT = 41 [json_name = "DEFAULTDEPOT"];
     */
    DEFAULTDEPOT?: string;
    /**
     * @generated from protobuf field: optional int32 WAREHOUSESETTING = 42 [json_name = "WAREHOUSESETTING"];
     */
    WAREHOUSESETTING?: number;
    /**
     * @generated from protobuf field: optional int32 DEPOTDSETTING = 43 [json_name = "DEPOTDSETTING"];
     */
    DEPOTDSETTING?: number;
    /**
     * @generated from protobuf field: optional string IP_ADDRESS = 44 [json_name = "IPADDRESS"];
     */
    IP_ADDRESS?: string;
    /**
     * @generated from protobuf field: optional int64 PORT_NO = 45 [json_name = "PORTNO"];
     */
    PORT_NO?: string;
    /**
     * @generated from protobuf field: optional int64 SECTOR_CODE = 46 [json_name = "SECTORCODE"];
     */
    SECTOR_CODE?: string;
    /**
     * @generated from protobuf field: optional string SECTOR_NAME = 47 [json_name = "SECTORNAME"];
     */
    SECTOR_NAME?: string;
    /**
     * @generated from protobuf field: optional string LN_POSTAL = 48 [json_name = "LNPOSTAL"];
     */
    LN_POSTAL?: string;
    /**
     * @generated from protobuf field: optional bool IS_VIRUAL_STATION = 49 [json_name = "ISVIRUALSTATION"];
     */
    IS_VIRUAL_STATION?: boolean;
}
/**
 * @generated from protobuf message MasProvider.ArrSTATIONS
 */
export interface ArrSTATIONS {
    /**
     * @generated from protobuf field: repeated MasProvider.STATIONS sTATIONS = 1;
     */
    sTATIONS: STATIONS[];
}
/**
 * @generated from protobuf message MasProvider.SETTINGS
 */
export interface SETTINGS {
    /**
     * @generated from protobuf field: string KEY_WORD = 1 [json_name = "KEYWORD"];
     */
    KEY_WORD: string; // @gotags: gorm:"primaryKey"
    /**
     * @generated from protobuf field: optional string KEY_VALUE = 2 [json_name = "KEYVALUE"];
     */
    KEY_VALUE?: string;
    /**
     * @generated from protobuf field: optional string DESCRIPTION = 3 [json_name = "DESCRIPTION"];
     */
    DESCRIPTION?: string;
}
/**
 * @generated from protobuf message MasProvider.DEPARTMENTS
 */
export interface DEPARTMENTS {
    /**
     * @generated from protobuf field: int64 ID = 1 [json_name = "ID"];
     */
    ID: string; // @gotags: gorm:"primaryKey"
    /**
     * @generated from protobuf field: optional string DESCRIPTION = 2 [json_name = "DESCRIPTION"];
     */
    DESCRIPTION?: string;
}
/**
 * @generated from protobuf message MasProvider.EMPTY
 */
export interface EMPTY {
}
/**
 * @generated from protobuf enum MasProvider.PROJECT_TAGS
 */
export enum PROJECT_TAGS {
    /**
     * @generated from protobuf enum value: EDAMS5 = 0;
     */
    EDAMS5 = 0,
    /**
     * @generated from protobuf enum value: EDAMS4 = 1;
     */
    EDAMS4 = 1,
    /**
     * @generated from protobuf enum value: GIZA_SYSTEMS = 2;
     */
    GIZA_SYSTEMS = 2,
    /**
     * @generated from protobuf enum value: MONOFIA = 3;
     */
    MONOFIA = 3,
    /**
     * @generated from protobuf enum value: SOHAG = 4;
     */
    SOHAG = 4,
    /**
     * @generated from protobuf enum value: OTHERS = 5;
     */
    OTHERS = 5
}
// @generated message type with reflection information, may provide speed optimized methods
class ArrSITES$Type extends MessageType<ArrSITES> {
    constructor() {
        super("MasProvider.ArrSITES", [
            { no: 1, name: "sITES", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => SITES }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message MasProvider.ArrSITES
 */
export const ArrSITES = new ArrSITES$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SITES$Type extends MessageType<SITES> {
    constructor() {
        super("MasProvider.SITES", [
            { no: 1, name: "CODE", kind: "scalar", localName: "CODE", jsonName: "CODE", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "DESCRIBE", kind: "scalar", localName: "DESCRIBE", jsonName: "DESCRIBE", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "IS_ACTIVE", kind: "scalar", localName: "IS_ACTIVE", jsonName: "ISACTIVE", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "SEQ", kind: "scalar", localName: "SEQ", jsonName: "SEQ", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 5, name: "BILLING_IP", kind: "scalar", localName: "BILLING_IP", jsonName: "BILLINGIP", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "BILLING_PASSWORD", kind: "scalar", localName: "BILLING_PASSWORD", jsonName: "BILLINGPASSWORD", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "BILLING_PORT_NO", kind: "scalar", localName: "BILLING_PORT_NO", jsonName: "BILLINGPORTNO", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "BILLING_USERNAME", kind: "scalar", localName: "BILLING_USERNAME", jsonName: "BILLINGUSERNAME", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "PROJECT_TAG", kind: "enum", localName: "PROJECT_TAG", jsonName: "PROJECTTAG", T: () => ["MasProvider.PROJECT_TAGS", PROJECT_TAGS] },
            { no: 10, name: "SITE_IMAGE", kind: "scalar", localName: "SITE_IMAGE", jsonName: "SITEIMAGE", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "HAS_MAS", kind: "scalar", localName: "HAS_MAS", jsonName: "HASMAS", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 12, name: "DESCRIBE_EN", kind: "scalar", localName: "DESCRIBE_EN", jsonName: "DESCRIBEEN", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message MasProvider.SITES
 */
export const SITES = new SITES$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetSettingValueRq$Type extends MessageType<GetSettingValueRq> {
    constructor() {
        super("MasProvider.GetSettingValueRq", [
            { no: 1, name: "keyword", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "SITE_CODE", kind: "scalar", localName: "SITE_CODE", jsonName: "SITECODE", opt: true, T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message MasProvider.GetSettingValueRq
 */
export const GetSettingValueRq = new GetSettingValueRq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetDepartmentRq$Type extends MessageType<GetDepartmentRq> {
    constructor() {
        super("MasProvider.GetDepartmentRq", [
            { no: 1, name: "departmentID", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message MasProvider.GetDepartmentRq
 */
export const GetDepartmentRq = new GetDepartmentRq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StationRq$Type extends MessageType<StationRq> {
    constructor() {
        super("MasProvider.StationRq", [
            { no: 1, name: "SiteCode", kind: "scalar", localName: "SiteCode", jsonName: "SiteCode", T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "StationNo", kind: "scalar", localName: "StationNo", jsonName: "StationNo", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message MasProvider.StationRq
 */
export const StationRq = new StationRq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SiteCode$Type extends MessageType<SiteCode> {
    constructor() {
        super("MasProvider.SiteCode", [
            { no: 1, name: "code", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message MasProvider.SiteCode
 */
export const SiteCode = new SiteCode$Type();
// @generated message type with reflection information, may provide speed optimized methods
class STATIONS$Type extends MessageType<STATIONS> {
    constructor() {
        super("MasProvider.STATIONS", [
            { no: 1, name: "SITE_CODE", kind: "scalar", localName: "SITE_CODE", jsonName: "SITECODE", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "STATION_NO", kind: "scalar", localName: "STATION_NO", jsonName: "STATIONNO", T: 3 /*ScalarType.INT64*/ },
            { no: 3, name: "NAME", kind: "scalar", localName: "NAME", jsonName: "NAME", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "DESCRIPTION", kind: "scalar", localName: "DESCRIPTION", jsonName: "DESCRIPTION", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "ISCURRENT", kind: "scalar", localName: "ISCURRENT", jsonName: "ISCURRENT", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 6, name: "DB_STANDALONE", kind: "scalar", localName: "DB_STANDALONE", jsonName: "DBSTANDALONE", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 7, name: "DB_ACCESS", kind: "scalar", localName: "DB_ACCESS", jsonName: "DBACCESS", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 8, name: "IS_HEADQUARTERS", kind: "scalar", localName: "IS_HEADQUARTERS", jsonName: "ISHEADQUARTERS", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 9, name: "IS_MAINTSITE", kind: "scalar", localName: "IS_MAINTSITE", jsonName: "ISMAINTSITE", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 10, name: "IS_MRREADING", kind: "scalar", localName: "IS_MRREADING", jsonName: "ISMRREADING", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 11, name: "IS_CSERVICES", kind: "scalar", localName: "IS_CSERVICES", jsonName: "ISCSERVICES", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 12, name: "IS_RECEIPTING", kind: "scalar", localName: "IS_RECEIPTING", jsonName: "ISRECEIPTING", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 13, name: "TEL_WORK", kind: "scalar", localName: "TEL_WORK", jsonName: "TELWORK", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 14, name: "TEL_FAX", kind: "scalar", localName: "TEL_FAX", jsonName: "TELFAX", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 15, name: "TEL_EMAIL", kind: "scalar", localName: "TEL_EMAIL", jsonName: "TELEMAIL", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 16, name: "TEL_AHOURS", kind: "scalar", localName: "TEL_AHOURS", jsonName: "TELAHOURS", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 17, name: "TEL_COMPL", kind: "scalar", localName: "TEL_COMPL", jsonName: "TELCOMPL", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 18, name: "LN_ADDRESS1", kind: "scalar", localName: "LN_ADDRESS1", jsonName: "LNADDRESS1", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 19, name: "LN_ADDRESS2", kind: "scalar", localName: "LN_ADDRESS2", jsonName: "LNADDRESS2", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 20, name: "LN_ADDRESS3", kind: "scalar", localName: "LN_ADDRESS3", jsonName: "LNADDRESS3", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 21, name: "LN_CITY", kind: "scalar", localName: "LN_CITY", jsonName: "LNCITY", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 22, name: "WORKING_MON", kind: "scalar", localName: "WORKING_MON", jsonName: "WORKINGMON", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 23, name: "WORKING_TUE", kind: "scalar", localName: "WORKING_TUE", jsonName: "WORKINGTUE", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 24, name: "WORKING_WED", kind: "scalar", localName: "WORKING_WED", jsonName: "WORKINGWED", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 25, name: "WORKING_THU", kind: "scalar", localName: "WORKING_THU", jsonName: "WORKINGTHU", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 26, name: "WORKING_FRI", kind: "scalar", localName: "WORKING_FRI", jsonName: "WORKINGFRI", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 27, name: "WORKING_SAT", kind: "scalar", localName: "WORKING_SAT", jsonName: "WORKINGSAT", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 28, name: "WORKING_SUN", kind: "scalar", localName: "WORKING_SUN", jsonName: "WORKINGSUN", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 29, name: "OVERTIME_MON", kind: "scalar", localName: "OVERTIME_MON", jsonName: "OVERTIMEMON", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 30, name: "OVERTIME_TUE", kind: "scalar", localName: "OVERTIME_TUE", jsonName: "OVERTIMETUE", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 31, name: "OVERTIME_WED", kind: "scalar", localName: "OVERTIME_WED", jsonName: "OVERTIMEWED", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 32, name: "OVERTIME_THU", kind: "scalar", localName: "OVERTIME_THU", jsonName: "OVERTIMETHU", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 33, name: "OVERTIME_FRI", kind: "scalar", localName: "OVERTIME_FRI", jsonName: "OVERTIMEFRI", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 34, name: "OVERTIME_SAT", kind: "scalar", localName: "OVERTIME_SAT", jsonName: "OVERTIMESAT", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 35, name: "OVERTIME_SUN", kind: "scalar", localName: "OVERTIME_SUN", jsonName: "OVERTIMESUN", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 36, name: "SITE_MEMO", kind: "scalar", localName: "SITE_MEMO", jsonName: "SITEMEMO", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 37, name: "STAMP_DATE", kind: "message", localName: "STAMP_DATE", jsonName: "STAMPDATE", T: () => MasDateTime },
            { no: 38, name: "STAMP_USER", kind: "scalar", localName: "STAMP_USER", jsonName: "STAMPUSER", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 39, name: "MAINTSITE_CODE", kind: "scalar", localName: "MAINTSITE_CODE", jsonName: "MAINTSITECODE", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 40, name: "DEFAULTWAREHOUSE", kind: "scalar", localName: "DEFAULTWAREHOUSE", jsonName: "DEFAULTWAREHOUSE", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 41, name: "DEFAULTDEPOT", kind: "scalar", localName: "DEFAULTDEPOT", jsonName: "DEFAULTDEPOT", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 42, name: "WAREHOUSESETTING", kind: "scalar", localName: "WAREHOUSESETTING", jsonName: "WAREHOUSESETTING", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 43, name: "DEPOTDSETTING", kind: "scalar", localName: "DEPOTDSETTING", jsonName: "DEPOTDSETTING", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 44, name: "IP_ADDRESS", kind: "scalar", localName: "IP_ADDRESS", jsonName: "IPADDRESS", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 45, name: "PORT_NO", kind: "scalar", localName: "PORT_NO", jsonName: "PORTNO", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 46, name: "SECTOR_CODE", kind: "scalar", localName: "SECTOR_CODE", jsonName: "SECTORCODE", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 47, name: "SECTOR_NAME", kind: "scalar", localName: "SECTOR_NAME", jsonName: "SECTORNAME", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 48, name: "LN_POSTAL", kind: "scalar", localName: "LN_POSTAL", jsonName: "LNPOSTAL", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 49, name: "IS_VIRUAL_STATION", kind: "scalar", localName: "IS_VIRUAL_STATION", jsonName: "ISVIRUALSTATION", opt: true, T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message MasProvider.STATIONS
 */
export const STATIONS = new STATIONS$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ArrSTATIONS$Type extends MessageType<ArrSTATIONS> {
    constructor() {
        super("MasProvider.ArrSTATIONS", [
            { no: 1, name: "sTATIONS", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => STATIONS }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message MasProvider.ArrSTATIONS
 */
export const ArrSTATIONS = new ArrSTATIONS$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SETTINGS$Type extends MessageType<SETTINGS> {
    constructor() {
        super("MasProvider.SETTINGS", [
            { no: 1, name: "KEY_WORD", kind: "scalar", localName: "KEY_WORD", jsonName: "KEYWORD", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "KEY_VALUE", kind: "scalar", localName: "KEY_VALUE", jsonName: "KEYVALUE", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "DESCRIPTION", kind: "scalar", localName: "DESCRIPTION", jsonName: "DESCRIPTION", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message MasProvider.SETTINGS
 */
export const SETTINGS = new SETTINGS$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DEPARTMENTS$Type extends MessageType<DEPARTMENTS> {
    constructor() {
        super("MasProvider.DEPARTMENTS", [
            { no: 1, name: "ID", kind: "scalar", localName: "ID", jsonName: "ID", T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "DESCRIPTION", kind: "scalar", localName: "DESCRIPTION", jsonName: "DESCRIPTION", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message MasProvider.DEPARTMENTS
 */
export const DEPARTMENTS = new DEPARTMENTS$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EMPTY$Type extends MessageType<EMPTY> {
    constructor() {
        super("MasProvider.EMPTY", []);
    }
}
/**
 * @generated MessageType for protobuf message MasProvider.EMPTY
 */
export const EMPTY = new EMPTY$Type();
/**
 * @generated ServiceType for protobuf service MasProvider.MasProvider
 */
export const MasProvider = new ServiceType("MasProvider.MasProvider", [
    { name: "GetStationByStationNo", options: {}, I: StationRq, O: STATIONS },
    { name: "GetMasStations", options: {}, I: EMPTY, O: ArrSTATIONS },
    { name: "GetSettingValue", options: {}, I: GetSettingValueRq, O: SETTINGS },
    { name: "GetDepartment", options: {}, I: GetDepartmentRq, O: DEPARTMENTS },
    { name: "GetAllSites", options: {}, I: EMPTY, O: ArrSITES },
    { name: "GetSiteLogo", options: {}, I: SiteCode, O: SITES }
]);
