// @generated by protobuf-ts 2.9.4 with parameter use_proto_field_name,add_pb_suffix,force_optimize_code_size,ts_nocheck,long_type_string
// @generated from protobuf file "MasProvider.proto" (package "MasProvider", syntax proto2)
// tslint:disable
// @ts-nocheck
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { MasProvider } from "./MasProvider_pb";
import type { SITES } from "./MasProvider_pb";
import type { SiteCode } from "./MasProvider_pb";
import type { ArrSITES } from "./MasProvider_pb";
import type { DEPARTMENTS } from "./MasProvider_pb";
import type { GetDepartmentRq } from "./MasProvider_pb";
import type { SETTINGS } from "./MasProvider_pb";
import type { GetSettingValueRq } from "./MasProvider_pb";
import type { ArrSTATIONS } from "./MasProvider_pb";
import type { EMPTY } from "./MasProvider_pb";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { STATIONS } from "./MasProvider_pb";
import type { StationRq } from "./MasProvider_pb";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * MAS PROVIDER
 *
 * @generated from protobuf service MasProvider.MasProvider
 */
export interface IMasProviderClient {
    /**
     * stations
     *
     * @generated from protobuf rpc: GetStationByStationNo(MasProvider.StationRq) returns (MasProvider.STATIONS);
     */
    getStationByStationNo(input: StationRq, options?: RpcOptions): UnaryCall<StationRq, STATIONS>;
    /**
     * @generated from protobuf rpc: GetMasStations(MasProvider.EMPTY) returns (MasProvider.ArrSTATIONS);
     */
    getMasStations(input: EMPTY, options?: RpcOptions): UnaryCall<EMPTY, ArrSTATIONS>;
    /**
     * @generated from protobuf rpc: GetSettingValue(MasProvider.GetSettingValueRq) returns (MasProvider.SETTINGS);
     */
    getSettingValue(input: GetSettingValueRq, options?: RpcOptions): UnaryCall<GetSettingValueRq, SETTINGS>;
    /**
     * @generated from protobuf rpc: GetDepartment(MasProvider.GetDepartmentRq) returns (MasProvider.DEPARTMENTS);
     */
    getDepartment(input: GetDepartmentRq, options?: RpcOptions): UnaryCall<GetDepartmentRq, DEPARTMENTS>;
    /**
     * @generated from protobuf rpc: GetAllSites(MasProvider.EMPTY) returns (MasProvider.ArrSITES);
     */
    getAllSites(input: EMPTY, options?: RpcOptions): UnaryCall<EMPTY, ArrSITES>;
    /**
     * @generated from protobuf rpc: GetSiteLogo(MasProvider.SiteCode) returns (MasProvider.SITES);
     */
    getSiteLogo(input: SiteCode, options?: RpcOptions): UnaryCall<SiteCode, SITES>;
}
/**
 * MAS PROVIDER
 *
 * @generated from protobuf service MasProvider.MasProvider
 */
export class MasProviderClient implements IMasProviderClient, ServiceInfo {
    typeName = MasProvider.typeName;
    methods = MasProvider.methods;
    options = MasProvider.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * stations
     *
     * @generated from protobuf rpc: GetStationByStationNo(MasProvider.StationRq) returns (MasProvider.STATIONS);
     */
    getStationByStationNo(input: StationRq, options?: RpcOptions): UnaryCall<StationRq, STATIONS> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<StationRq, STATIONS>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetMasStations(MasProvider.EMPTY) returns (MasProvider.ArrSTATIONS);
     */
    getMasStations(input: EMPTY, options?: RpcOptions): UnaryCall<EMPTY, ArrSTATIONS> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<EMPTY, ArrSTATIONS>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetSettingValue(MasProvider.GetSettingValueRq) returns (MasProvider.SETTINGS);
     */
    getSettingValue(input: GetSettingValueRq, options?: RpcOptions): UnaryCall<GetSettingValueRq, SETTINGS> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetSettingValueRq, SETTINGS>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetDepartment(MasProvider.GetDepartmentRq) returns (MasProvider.DEPARTMENTS);
     */
    getDepartment(input: GetDepartmentRq, options?: RpcOptions): UnaryCall<GetDepartmentRq, DEPARTMENTS> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetDepartmentRq, DEPARTMENTS>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAllSites(MasProvider.EMPTY) returns (MasProvider.ArrSITES);
     */
    getAllSites(input: EMPTY, options?: RpcOptions): UnaryCall<EMPTY, ArrSITES> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<EMPTY, ArrSITES>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetSiteLogo(MasProvider.SiteCode) returns (MasProvider.SITES);
     */
    getSiteLogo(input: SiteCode, options?: RpcOptions): UnaryCall<SiteCode, SITES> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<SiteCode, SITES>("unary", this._transport, method, opt, input);
    }
}
