// @generated by protobuf-ts 2.9.4 with parameter use_proto_field_name,add_pb_suffix,force_optimize_code_size,ts_nocheck,long_type_string
// @generated from protobuf file "operation.proto" (package "edams", syntax proto3)
// tslint:disable
// @ts-nocheck
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { BillingEngineService } from "./operation_pb";
import type { APP_EXTERNAL_ACTIVITY } from "./bpmreqedams_pb";
import type { InvoiceAgreemReq } from "./operation_pb";
import type { CustDataAndArrINVOICES } from "./operation_pb";
import type { CustkeyRq } from "./operation_pb";
import type { UpdateSettingsRequest } from "./operation_pb";
import type { GetSettingsResponse } from "./operation_pb";
import type { CalcResponceArr } from "./operation_pb";
import type { CalcRequestArr } from "./operation_pb";
import type { BillingSteps } from "./operation_pb";
import type { SearchResponse } from "./operation_pb";
import type { SearchRequest } from "./operation_pb";
import type { BillingStatusStatistcs } from "./operation_pb";
import type { StatisticsRequest } from "./operation_pb";
import type { PoolStatus } from "./operation_pb";
import type { Billgroups } from "./operation_pb";
import type { BillgroupRequest } from "./operation_pb";
import type { BillingCycleStatusRequest } from "./operation_pb";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { arrReadingRecord } from "./operation_pb";
import type { GetLastReadingRq } from "./operation_pb";
import type { CustomStep } from "./operation_pb";
import type { CustomSteps } from "./operation_pb";
import type { CustomHocks } from "./operation_pb";
import type { ProcedureName } from "./operation_pb";
import type { CustomHock } from "./operation_pb";
import type { StepReportsErrorsWarnings } from "./operation_pb";
import type { StepReports } from "./operation_pb";
import type { StepReportResponce } from "./operation_pb";
import type { StepReportRequest } from "./operation_pb";
import type { BILLS_EXPECTED } from "./operation_pb";
import type { STEPRq } from "./operation_pb";
import type { BillingCycleList } from "./operation_pb";
import type { NewCycleRequest } from "./operation_pb";
import type { CalcIndividualRequest } from "./operation_pb";
import type { CalcResponce } from "./operation_pb";
import type { CalcRequest } from "./operation_pb";
import type { BillingCycle } from "./operation_pb";
import type { BillCycleRequest } from "./operation_pb";
import type { ServiceName } from "./operation_pb";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { Version } from "./operation_pb";
import type { Empty } from "./operation_pb";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service edams.BillingEngineService
 */
export interface IBillingEngineServiceClient {
    /**
     * @generated from protobuf rpc: GetVersion(edams.Empty) returns (edams.Version);
     */
    getVersion(input: Empty, options?: RpcOptions): UnaryCall<Empty, Version>;
    /**
     * @generated from protobuf rpc: GetServiceName(edams.Empty) returns (edams.ServiceName);
     */
    getServiceName(input: Empty, options?: RpcOptions): UnaryCall<Empty, ServiceName>;
    /**
     * @generated from protobuf rpc: GetBillingCycle(edams.BillCycleRequest) returns (edams.BillingCycle);
     */
    getBillingCycle(input: BillCycleRequest, options?: RpcOptions): UnaryCall<BillCycleRequest, BillingCycle>;
    /**
     * @generated from protobuf rpc: ProcessBillingStep(edams.CalcRequest) returns (edams.CalcResponce);
     */
    processBillingStep(input: CalcRequest, options?: RpcOptions): UnaryCall<CalcRequest, CalcResponce>;
    /**
     * @generated from protobuf rpc: ReverseBillingStep(edams.CalcRequest) returns (edams.CalcResponce);
     */
    reverseBillingStep(input: CalcRequest, options?: RpcOptions): UnaryCall<CalcRequest, CalcResponce>;
    /**
     * @generated from protobuf rpc: ProcessBillingStepIndividual(edams.CalcIndividualRequest) returns (edams.CalcResponce);
     */
    processBillingStepIndividual(input: CalcIndividualRequest, options?: RpcOptions): UnaryCall<CalcIndividualRequest, CalcResponce>;
    /**
     * @generated from protobuf rpc: ReverseBillingStepIndividual(edams.CalcIndividualRequest) returns (edams.CalcResponce);
     */
    reverseBillingStepIndividual(input: CalcIndividualRequest, options?: RpcOptions): UnaryCall<CalcIndividualRequest, CalcResponce>;
    /**
     * @generated from protobuf rpc: NewBillingCycle(edams.NewCycleRequest) returns (edams.BillingCycle);
     */
    newBillingCycle(input: NewCycleRequest, options?: RpcOptions): UnaryCall<NewCycleRequest, BillingCycle>;
    /**
     * @generated from protobuf rpc: CloseBillingCycle(edams.BillCycleRequest) returns (edams.CalcResponce);
     */
    closeBillingCycle(input: BillCycleRequest, options?: RpcOptions): UnaryCall<BillCycleRequest, CalcResponce>;
    /**
     * @generated from protobuf rpc: GetBillingCycleList(edams.Empty) returns (edams.BillingCycleList);
     */
    getBillingCycleList(input: Empty, options?: RpcOptions): UnaryCall<Empty, BillingCycleList>;
    /**
     * @generated from protobuf rpc: GetBillingCycleByNextValidStep(edams.STEPRq) returns (edams.BillingCycleList);
     */
    getBillingCycleByNextValidStep(input: STEPRq, options?: RpcOptions): UnaryCall<STEPRq, BillingCycleList>;
    /**
     * rpc RecalcBills(BillResponce)returns(Empty);
     *
     * @generated from protobuf rpc: RecalcBills(edams.BILLS_EXPECTED) returns (edams.Empty);
     */
    recalcBills(input: BILLS_EXPECTED, options?: RpcOptions): UnaryCall<BILLS_EXPECTED, Empty>;
    /**
     * rpc Setup(Empty) returns (Empty){}
     *
     * @generated from protobuf rpc: GetStepReports(edams.StepReportRequest) returns (edams.StepReportResponce);
     */
    getStepReports(input: StepReportRequest, options?: RpcOptions): UnaryCall<StepReportRequest, StepReportResponce>;
    /**
     * @generated from protobuf rpc: GetAllStepReports(edams.Empty) returns (edams.StepReports);
     */
    getAllStepReports(input: Empty, options?: RpcOptions): UnaryCall<Empty, StepReports>;
    /**
     * @generated from protobuf rpc: GetStepReportsErrorsWarnings(edams.StepReportRequest) returns (edams.StepReportsErrorsWarnings);
     */
    getStepReportsErrorsWarnings(input: StepReportRequest, options?: RpcOptions): UnaryCall<StepReportRequest, StepReportsErrorsWarnings>;
    /**
     * @generated from protobuf rpc: AddOrUpdateHock(edams.CustomHock) returns (edams.Empty);
     */
    addOrUpdateHock(input: CustomHock, options?: RpcOptions): UnaryCall<CustomHock, Empty>;
    /**
     * @generated from protobuf rpc: RemoveHock(edams.ProcedureName) returns (edams.Empty);
     */
    removeHock(input: ProcedureName, options?: RpcOptions): UnaryCall<ProcedureName, Empty>;
    /**
     * @generated from protobuf rpc: GetHocks(edams.Empty) returns (edams.CustomHocks);
     */
    getHocks(input: Empty, options?: RpcOptions): UnaryCall<Empty, CustomHocks>;
    /**
     * @generated from protobuf rpc: GetPredefinedCustomSteps(edams.Empty) returns (edams.CustomSteps);
     */
    getPredefinedCustomSteps(input: Empty, options?: RpcOptions): UnaryCall<Empty, CustomSteps>;
    /**
     * @generated from protobuf rpc: AddOrUpdateCustomStep(edams.CustomStep) returns (edams.Empty);
     */
    addOrUpdateCustomStep(input: CustomStep, options?: RpcOptions): UnaryCall<CustomStep, Empty>;
    /**
     * @generated from protobuf rpc: RemoveCustomStep(edams.ProcedureName) returns (edams.Empty);
     */
    removeCustomStep(input: ProcedureName, options?: RpcOptions): UnaryCall<ProcedureName, Empty>;
    /**
     * @generated from protobuf rpc: GetCustomSteps(edams.Empty) returns (edams.CustomSteps);
     */
    getCustomSteps(input: Empty, options?: RpcOptions): UnaryCall<Empty, CustomSteps>;
    /**
     * @generated from protobuf rpc: GetLastInvoicedReading(edams.GetLastReadingRq) returns (edams.arrReadingRecord);
     */
    getLastInvoicedReading(input: GetLastReadingRq, options?: RpcOptions): UnaryCall<GetLastReadingRq, arrReadingRecord>;
    /**
     * stream
     *
     * @generated from protobuf rpc: GetBillingStatus(edams.BillingCycleStatusRequest) returns (stream edams.BillingCycle);
     */
    getBillingStatus(input: BillingCycleStatusRequest, options?: RpcOptions): ServerStreamingCall<BillingCycleStatusRequest, BillingCycle>;
    /**
     * @generated from protobuf rpc: GetBillingGroups(edams.BillgroupRequest) returns (edams.Billgroups);
     */
    getBillingGroups(input: BillgroupRequest, options?: RpcOptions): UnaryCall<BillgroupRequest, Billgroups>;
    /**
     * @generated from protobuf rpc: GetPoolStatus(edams.Empty) returns (edams.PoolStatus);
     */
    getPoolStatus(input: Empty, options?: RpcOptions): UnaryCall<Empty, PoolStatus>;
    /**
     * @generated from protobuf rpc: GetStatistics(edams.StatisticsRequest) returns (edams.BillingStatusStatistcs);
     */
    getStatistics(input: StatisticsRequest, options?: RpcOptions): UnaryCall<StatisticsRequest, BillingStatusStatistcs>;
    /**
     * @generated from protobuf rpc: Search(edams.SearchRequest) returns (edams.SearchResponse);
     */
    search(input: SearchRequest, options?: RpcOptions): UnaryCall<SearchRequest, SearchResponse>;
    /**
     * @generated from protobuf rpc: UpdateEstimCons(edams.SearchResponse) returns (edams.Empty);
     */
    updateEstimCons(input: SearchResponse, options?: RpcOptions): UnaryCall<SearchResponse, Empty>;
    /**
     * @generated from protobuf rpc: GetBillingSteps(edams.Empty) returns (edams.BillingSteps);
     */
    getBillingSteps(input: Empty, options?: RpcOptions): UnaryCall<Empty, BillingSteps>;
    /**
     * @generated from protobuf rpc: ProccessBillgroupsForStep(edams.CalcRequestArr) returns (edams.CalcResponceArr);
     */
    proccessBillgroupsForStep(input: CalcRequestArr, options?: RpcOptions): UnaryCall<CalcRequestArr, CalcResponceArr>;
    /**
     * @generated from protobuf rpc: GetSettings(edams.Empty) returns (edams.GetSettingsResponse);
     */
    getSettings(input: Empty, options?: RpcOptions): UnaryCall<Empty, GetSettingsResponse>;
    /**
     * @generated from protobuf rpc: UpdateSettings(edams.UpdateSettingsRequest) returns (edams.Empty);
     */
    updateSettings(input: UpdateSettingsRequest, options?: RpcOptions): UnaryCall<UpdateSettingsRequest, Empty>;
    /**
     * Adjust Agrem
     *
     * @generated from protobuf rpc: GetAllUnCollectedCustInvoices(edams.CustkeyRq) returns (edams.CustDataAndArrINVOICES);
     */
    getAllUnCollectedCustInvoices(input: CustkeyRq, options?: RpcOptions): UnaryCall<CustkeyRq, CustDataAndArrINVOICES>;
    /**
     * @generated from protobuf rpc: CreateInvoiceAgreem(edams.InvoiceAgreemReq) returns (edams.Empty);
     */
    createInvoiceAgreem(input: InvoiceAgreemReq, options?: RpcOptions): UnaryCall<InvoiceAgreemReq, Empty>;
    /**
     * go application
     *
     * @generated from protobuf rpc: Execute(edams.APP_EXTERNAL_ACTIVITY) returns (edams.APP_EXTERNAL_ACTIVITY);
     */
    execute(input: APP_EXTERNAL_ACTIVITY, options?: RpcOptions): UnaryCall<APP_EXTERNAL_ACTIVITY, APP_EXTERNAL_ACTIVITY>;
}
/**
 * @generated from protobuf service edams.BillingEngineService
 */
export class BillingEngineServiceClient implements IBillingEngineServiceClient, ServiceInfo {
    typeName = BillingEngineService.typeName;
    methods = BillingEngineService.methods;
    options = BillingEngineService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetVersion(edams.Empty) returns (edams.Version);
     */
    getVersion(input: Empty, options?: RpcOptions): UnaryCall<Empty, Version> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, Version>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetServiceName(edams.Empty) returns (edams.ServiceName);
     */
    getServiceName(input: Empty, options?: RpcOptions): UnaryCall<Empty, ServiceName> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, ServiceName>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetBillingCycle(edams.BillCycleRequest) returns (edams.BillingCycle);
     */
    getBillingCycle(input: BillCycleRequest, options?: RpcOptions): UnaryCall<BillCycleRequest, BillingCycle> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<BillCycleRequest, BillingCycle>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ProcessBillingStep(edams.CalcRequest) returns (edams.CalcResponce);
     */
    processBillingStep(input: CalcRequest, options?: RpcOptions): UnaryCall<CalcRequest, CalcResponce> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<CalcRequest, CalcResponce>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ReverseBillingStep(edams.CalcRequest) returns (edams.CalcResponce);
     */
    reverseBillingStep(input: CalcRequest, options?: RpcOptions): UnaryCall<CalcRequest, CalcResponce> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<CalcRequest, CalcResponce>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ProcessBillingStepIndividual(edams.CalcIndividualRequest) returns (edams.CalcResponce);
     */
    processBillingStepIndividual(input: CalcIndividualRequest, options?: RpcOptions): UnaryCall<CalcIndividualRequest, CalcResponce> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<CalcIndividualRequest, CalcResponce>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ReverseBillingStepIndividual(edams.CalcIndividualRequest) returns (edams.CalcResponce);
     */
    reverseBillingStepIndividual(input: CalcIndividualRequest, options?: RpcOptions): UnaryCall<CalcIndividualRequest, CalcResponce> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<CalcIndividualRequest, CalcResponce>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: NewBillingCycle(edams.NewCycleRequest) returns (edams.BillingCycle);
     */
    newBillingCycle(input: NewCycleRequest, options?: RpcOptions): UnaryCall<NewCycleRequest, BillingCycle> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<NewCycleRequest, BillingCycle>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CloseBillingCycle(edams.BillCycleRequest) returns (edams.CalcResponce);
     */
    closeBillingCycle(input: BillCycleRequest, options?: RpcOptions): UnaryCall<BillCycleRequest, CalcResponce> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<BillCycleRequest, CalcResponce>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetBillingCycleList(edams.Empty) returns (edams.BillingCycleList);
     */
    getBillingCycleList(input: Empty, options?: RpcOptions): UnaryCall<Empty, BillingCycleList> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, BillingCycleList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetBillingCycleByNextValidStep(edams.STEPRq) returns (edams.BillingCycleList);
     */
    getBillingCycleByNextValidStep(input: STEPRq, options?: RpcOptions): UnaryCall<STEPRq, BillingCycleList> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<STEPRq, BillingCycleList>("unary", this._transport, method, opt, input);
    }
    /**
     * rpc RecalcBills(BillResponce)returns(Empty);
     *
     * @generated from protobuf rpc: RecalcBills(edams.BILLS_EXPECTED) returns (edams.Empty);
     */
    recalcBills(input: BILLS_EXPECTED, options?: RpcOptions): UnaryCall<BILLS_EXPECTED, Empty> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<BILLS_EXPECTED, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * rpc Setup(Empty) returns (Empty){}
     *
     * @generated from protobuf rpc: GetStepReports(edams.StepReportRequest) returns (edams.StepReportResponce);
     */
    getStepReports(input: StepReportRequest, options?: RpcOptions): UnaryCall<StepReportRequest, StepReportResponce> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return stackIntercept<StepReportRequest, StepReportResponce>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAllStepReports(edams.Empty) returns (edams.StepReports);
     */
    getAllStepReports(input: Empty, options?: RpcOptions): UnaryCall<Empty, StepReports> {
        const method = this.methods[13], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, StepReports>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetStepReportsErrorsWarnings(edams.StepReportRequest) returns (edams.StepReportsErrorsWarnings);
     */
    getStepReportsErrorsWarnings(input: StepReportRequest, options?: RpcOptions): UnaryCall<StepReportRequest, StepReportsErrorsWarnings> {
        const method = this.methods[14], opt = this._transport.mergeOptions(options);
        return stackIntercept<StepReportRequest, StepReportsErrorsWarnings>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AddOrUpdateHock(edams.CustomHock) returns (edams.Empty);
     */
    addOrUpdateHock(input: CustomHock, options?: RpcOptions): UnaryCall<CustomHock, Empty> {
        const method = this.methods[15], opt = this._transport.mergeOptions(options);
        return stackIntercept<CustomHock, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RemoveHock(edams.ProcedureName) returns (edams.Empty);
     */
    removeHock(input: ProcedureName, options?: RpcOptions): UnaryCall<ProcedureName, Empty> {
        const method = this.methods[16], opt = this._transport.mergeOptions(options);
        return stackIntercept<ProcedureName, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetHocks(edams.Empty) returns (edams.CustomHocks);
     */
    getHocks(input: Empty, options?: RpcOptions): UnaryCall<Empty, CustomHocks> {
        const method = this.methods[17], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, CustomHocks>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetPredefinedCustomSteps(edams.Empty) returns (edams.CustomSteps);
     */
    getPredefinedCustomSteps(input: Empty, options?: RpcOptions): UnaryCall<Empty, CustomSteps> {
        const method = this.methods[18], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, CustomSteps>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AddOrUpdateCustomStep(edams.CustomStep) returns (edams.Empty);
     */
    addOrUpdateCustomStep(input: CustomStep, options?: RpcOptions): UnaryCall<CustomStep, Empty> {
        const method = this.methods[19], opt = this._transport.mergeOptions(options);
        return stackIntercept<CustomStep, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RemoveCustomStep(edams.ProcedureName) returns (edams.Empty);
     */
    removeCustomStep(input: ProcedureName, options?: RpcOptions): UnaryCall<ProcedureName, Empty> {
        const method = this.methods[20], opt = this._transport.mergeOptions(options);
        return stackIntercept<ProcedureName, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCustomSteps(edams.Empty) returns (edams.CustomSteps);
     */
    getCustomSteps(input: Empty, options?: RpcOptions): UnaryCall<Empty, CustomSteps> {
        const method = this.methods[21], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, CustomSteps>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetLastInvoicedReading(edams.GetLastReadingRq) returns (edams.arrReadingRecord);
     */
    getLastInvoicedReading(input: GetLastReadingRq, options?: RpcOptions): UnaryCall<GetLastReadingRq, arrReadingRecord> {
        const method = this.methods[22], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetLastReadingRq, arrReadingRecord>("unary", this._transport, method, opt, input);
    }
    /**
     * stream
     *
     * @generated from protobuf rpc: GetBillingStatus(edams.BillingCycleStatusRequest) returns (stream edams.BillingCycle);
     */
    getBillingStatus(input: BillingCycleStatusRequest, options?: RpcOptions): ServerStreamingCall<BillingCycleStatusRequest, BillingCycle> {
        const method = this.methods[23], opt = this._transport.mergeOptions(options);
        return stackIntercept<BillingCycleStatusRequest, BillingCycle>("serverStreaming", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetBillingGroups(edams.BillgroupRequest) returns (edams.Billgroups);
     */
    getBillingGroups(input: BillgroupRequest, options?: RpcOptions): UnaryCall<BillgroupRequest, Billgroups> {
        const method = this.methods[24], opt = this._transport.mergeOptions(options);
        return stackIntercept<BillgroupRequest, Billgroups>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetPoolStatus(edams.Empty) returns (edams.PoolStatus);
     */
    getPoolStatus(input: Empty, options?: RpcOptions): UnaryCall<Empty, PoolStatus> {
        const method = this.methods[25], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, PoolStatus>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetStatistics(edams.StatisticsRequest) returns (edams.BillingStatusStatistcs);
     */
    getStatistics(input: StatisticsRequest, options?: RpcOptions): UnaryCall<StatisticsRequest, BillingStatusStatistcs> {
        const method = this.methods[26], opt = this._transport.mergeOptions(options);
        return stackIntercept<StatisticsRequest, BillingStatusStatistcs>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Search(edams.SearchRequest) returns (edams.SearchResponse);
     */
    search(input: SearchRequest, options?: RpcOptions): UnaryCall<SearchRequest, SearchResponse> {
        const method = this.methods[27], opt = this._transport.mergeOptions(options);
        return stackIntercept<SearchRequest, SearchResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateEstimCons(edams.SearchResponse) returns (edams.Empty);
     */
    updateEstimCons(input: SearchResponse, options?: RpcOptions): UnaryCall<SearchResponse, Empty> {
        const method = this.methods[28], opt = this._transport.mergeOptions(options);
        return stackIntercept<SearchResponse, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetBillingSteps(edams.Empty) returns (edams.BillingSteps);
     */
    getBillingSteps(input: Empty, options?: RpcOptions): UnaryCall<Empty, BillingSteps> {
        const method = this.methods[29], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, BillingSteps>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ProccessBillgroupsForStep(edams.CalcRequestArr) returns (edams.CalcResponceArr);
     */
    proccessBillgroupsForStep(input: CalcRequestArr, options?: RpcOptions): UnaryCall<CalcRequestArr, CalcResponceArr> {
        const method = this.methods[30], opt = this._transport.mergeOptions(options);
        return stackIntercept<CalcRequestArr, CalcResponceArr>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetSettings(edams.Empty) returns (edams.GetSettingsResponse);
     */
    getSettings(input: Empty, options?: RpcOptions): UnaryCall<Empty, GetSettingsResponse> {
        const method = this.methods[31], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, GetSettingsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateSettings(edams.UpdateSettingsRequest) returns (edams.Empty);
     */
    updateSettings(input: UpdateSettingsRequest, options?: RpcOptions): UnaryCall<UpdateSettingsRequest, Empty> {
        const method = this.methods[32], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateSettingsRequest, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * Adjust Agrem
     *
     * @generated from protobuf rpc: GetAllUnCollectedCustInvoices(edams.CustkeyRq) returns (edams.CustDataAndArrINVOICES);
     */
    getAllUnCollectedCustInvoices(input: CustkeyRq, options?: RpcOptions): UnaryCall<CustkeyRq, CustDataAndArrINVOICES> {
        const method = this.methods[33], opt = this._transport.mergeOptions(options);
        return stackIntercept<CustkeyRq, CustDataAndArrINVOICES>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateInvoiceAgreem(edams.InvoiceAgreemReq) returns (edams.Empty);
     */
    createInvoiceAgreem(input: InvoiceAgreemReq, options?: RpcOptions): UnaryCall<InvoiceAgreemReq, Empty> {
        const method = this.methods[34], opt = this._transport.mergeOptions(options);
        return stackIntercept<InvoiceAgreemReq, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * go application
     *
     * @generated from protobuf rpc: Execute(edams.APP_EXTERNAL_ACTIVITY) returns (edams.APP_EXTERNAL_ACTIVITY);
     */
    execute(input: APP_EXTERNAL_ACTIVITY, options?: RpcOptions): UnaryCall<APP_EXTERNAL_ACTIVITY, APP_EXTERNAL_ACTIVITY> {
        const method = this.methods[35], opt = this._transport.mergeOptions(options);
        return stackIntercept<APP_EXTERNAL_ACTIVITY, APP_EXTERNAL_ACTIVITY>("unary", this._transport, method, opt, input);
    }
}
