// @generated by protobuf-ts 2.9.4 with parameter use_proto_field_name,add_pb_suffix,force_optimize_code_size,ts_nocheck,long_type_string
// @generated from protobuf file "queries.proto" (package "PkgQueries", syntax proto2)
// tslint:disable
// @ts-nocheck
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { QueryService } from "./queries_pb";
import type { ArrCustREADINGS } from "./queries_pb";
import type { ArrWalletDetails } from "./queries_pb";
import type { WalletDetailsRq } from "./queries_pb";
import type { JSON_TEST } from "./queries_pb";
import type { TEST } from "./queries_pb";
import type { ArrCST_HISTORY } from "./queries_pb";
import type { ArrBILL_PRINT } from "./queries_pb";
import type { ArrREADINGS } from "./queries_pb";
import type { ArrCustAgreem } from "./queries_pb";
import type { ArrSTATMENT } from "./queries_pb";
import type { ArrTRANSACTIONS } from "./queries_pb";
import type { CUSTOMER_MAIN_DATA } from "./queries_pb";
import type { CustkeyRq } from "./queries_pb";
import type { ArrCUSTOMER_Books } from "./queries_pb";
import type { BillgroupRq } from "./queries_pb";
import type { ArrBILLING_GROUPS } from "./queries_pb";
import type { Empty } from "./queries_pb";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { SearchCustomerRs } from "./queries_pb";
import type { SearchCustomerRq } from "./queries_pb";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * import "date.proto";
 *
 * @generated from protobuf service PkgQueries.QueryService
 */
export interface IQueryServiceClient {
    /**
     * @generated from protobuf rpc: SearchCustomer(PkgQueries.SearchCustomerRq) returns (PkgQueries.SearchCustomerRs);
     */
    searchCustomer(input: SearchCustomerRq, options?: RpcOptions): UnaryCall<SearchCustomerRq, SearchCustomerRs>;
    /**
     * @generated from protobuf rpc: GetAllBillgroups(PkgQueries.Empty) returns (PkgQueries.ArrBILLING_GROUPS);
     */
    getAllBillgroups(input: Empty, options?: RpcOptions): UnaryCall<Empty, ArrBILLING_GROUPS>;
    /**
     * @generated from protobuf rpc: GetCustomerBooksByBillgroup(PkgQueries.BillgroupRq) returns (PkgQueries.ArrCUSTOMER_Books);
     */
    getCustomerBooksByBillgroup(input: BillgroupRq, options?: RpcOptions): UnaryCall<BillgroupRq, ArrCUSTOMER_Books>;
    /**
     * @generated from protobuf rpc: GetCustomerMainDataByCustkey(PkgQueries.CustkeyRq) returns (PkgQueries.CUSTOMER_MAIN_DATA);
     */
    getCustomerMainDataByCustkey(input: CustkeyRq, options?: RpcOptions): UnaryCall<CustkeyRq, CUSTOMER_MAIN_DATA>;
    /**
     * @generated from protobuf rpc: GetCustomerTransactions(PkgQueries.CustkeyRq) returns (PkgQueries.ArrTRANSACTIONS);
     */
    getCustomerTransactions(input: CustkeyRq, options?: RpcOptions): UnaryCall<CustkeyRq, ArrTRANSACTIONS>;
    /**
     * @generated from protobuf rpc: GetCustomerStatements(PkgQueries.CustkeyRq) returns (PkgQueries.ArrSTATMENT);
     */
    getCustomerStatements(input: CustkeyRq, options?: RpcOptions): UnaryCall<CustkeyRq, ArrSTATMENT>;
    /**
     * @generated from protobuf rpc: GetCustomerAgreements(PkgQueries.CustkeyRq) returns (PkgQueries.ArrCustAgreem);
     */
    getCustomerAgreements(input: CustkeyRq, options?: RpcOptions): UnaryCall<CustkeyRq, ArrCustAgreem>;
    /**
     * @generated from protobuf rpc: GetCustomerReadings(PkgQueries.CustkeyRq) returns (PkgQueries.ArrREADINGS);
     */
    getCustomerReadings(input: CustkeyRq, options?: RpcOptions): UnaryCall<CustkeyRq, ArrREADINGS>;
    /**
     * @generated from protobuf rpc: GetBillPrintCust(PkgQueries.CustkeyRq) returns (PkgQueries.ArrBILL_PRINT);
     */
    getBillPrintCust(input: CustkeyRq, options?: RpcOptions): UnaryCall<CustkeyRq, ArrBILL_PRINT>;
    /**
     * @generated from protobuf rpc: GetAllCustomerHistory(PkgQueries.CustkeyRq) returns (PkgQueries.ArrCST_HISTORY);
     */
    getAllCustomerHistory(input: CustkeyRq, options?: RpcOptions): UnaryCall<CustkeyRq, ArrCST_HISTORY>;
    /**
     * @generated from protobuf rpc: TestRpc(PkgQueries.TEST) returns (PkgQueries.JSON_TEST);
     */
    testRpc(input: TEST, options?: RpcOptions): UnaryCall<TEST, JSON_TEST>;
    /**
     * @generated from protobuf rpc: GetCustWalletDetails(PkgQueries.WalletDetailsRq) returns (PkgQueries.ArrWalletDetails);
     */
    getCustWalletDetails(input: WalletDetailsRq, options?: RpcOptions): UnaryCall<WalletDetailsRq, ArrWalletDetails>;
    /**
     * @generated from protobuf rpc: GetCustomermetersReadings(PkgQueries.CustkeyRq) returns (PkgQueries.ArrCustREADINGS);
     */
    getCustomermetersReadings(input: CustkeyRq, options?: RpcOptions): UnaryCall<CustkeyRq, ArrCustREADINGS>;
}
/**
 * import "date.proto";
 *
 * @generated from protobuf service PkgQueries.QueryService
 */
export class QueryServiceClient implements IQueryServiceClient, ServiceInfo {
    typeName = QueryService.typeName;
    methods = QueryService.methods;
    options = QueryService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: SearchCustomer(PkgQueries.SearchCustomerRq) returns (PkgQueries.SearchCustomerRs);
     */
    searchCustomer(input: SearchCustomerRq, options?: RpcOptions): UnaryCall<SearchCustomerRq, SearchCustomerRs> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<SearchCustomerRq, SearchCustomerRs>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAllBillgroups(PkgQueries.Empty) returns (PkgQueries.ArrBILLING_GROUPS);
     */
    getAllBillgroups(input: Empty, options?: RpcOptions): UnaryCall<Empty, ArrBILLING_GROUPS> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, ArrBILLING_GROUPS>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCustomerBooksByBillgroup(PkgQueries.BillgroupRq) returns (PkgQueries.ArrCUSTOMER_Books);
     */
    getCustomerBooksByBillgroup(input: BillgroupRq, options?: RpcOptions): UnaryCall<BillgroupRq, ArrCUSTOMER_Books> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<BillgroupRq, ArrCUSTOMER_Books>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCustomerMainDataByCustkey(PkgQueries.CustkeyRq) returns (PkgQueries.CUSTOMER_MAIN_DATA);
     */
    getCustomerMainDataByCustkey(input: CustkeyRq, options?: RpcOptions): UnaryCall<CustkeyRq, CUSTOMER_MAIN_DATA> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<CustkeyRq, CUSTOMER_MAIN_DATA>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCustomerTransactions(PkgQueries.CustkeyRq) returns (PkgQueries.ArrTRANSACTIONS);
     */
    getCustomerTransactions(input: CustkeyRq, options?: RpcOptions): UnaryCall<CustkeyRq, ArrTRANSACTIONS> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<CustkeyRq, ArrTRANSACTIONS>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCustomerStatements(PkgQueries.CustkeyRq) returns (PkgQueries.ArrSTATMENT);
     */
    getCustomerStatements(input: CustkeyRq, options?: RpcOptions): UnaryCall<CustkeyRq, ArrSTATMENT> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<CustkeyRq, ArrSTATMENT>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCustomerAgreements(PkgQueries.CustkeyRq) returns (PkgQueries.ArrCustAgreem);
     */
    getCustomerAgreements(input: CustkeyRq, options?: RpcOptions): UnaryCall<CustkeyRq, ArrCustAgreem> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<CustkeyRq, ArrCustAgreem>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCustomerReadings(PkgQueries.CustkeyRq) returns (PkgQueries.ArrREADINGS);
     */
    getCustomerReadings(input: CustkeyRq, options?: RpcOptions): UnaryCall<CustkeyRq, ArrREADINGS> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<CustkeyRq, ArrREADINGS>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetBillPrintCust(PkgQueries.CustkeyRq) returns (PkgQueries.ArrBILL_PRINT);
     */
    getBillPrintCust(input: CustkeyRq, options?: RpcOptions): UnaryCall<CustkeyRq, ArrBILL_PRINT> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<CustkeyRq, ArrBILL_PRINT>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAllCustomerHistory(PkgQueries.CustkeyRq) returns (PkgQueries.ArrCST_HISTORY);
     */
    getAllCustomerHistory(input: CustkeyRq, options?: RpcOptions): UnaryCall<CustkeyRq, ArrCST_HISTORY> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<CustkeyRq, ArrCST_HISTORY>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: TestRpc(PkgQueries.TEST) returns (PkgQueries.JSON_TEST);
     */
    testRpc(input: TEST, options?: RpcOptions): UnaryCall<TEST, JSON_TEST> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<TEST, JSON_TEST>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCustWalletDetails(PkgQueries.WalletDetailsRq) returns (PkgQueries.ArrWalletDetails);
     */
    getCustWalletDetails(input: WalletDetailsRq, options?: RpcOptions): UnaryCall<WalletDetailsRq, ArrWalletDetails> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<WalletDetailsRq, ArrWalletDetails>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCustomermetersReadings(PkgQueries.CustkeyRq) returns (PkgQueries.ArrCustREADINGS);
     */
    getCustomermetersReadings(input: CustkeyRq, options?: RpcOptions): UnaryCall<CustkeyRq, ArrCustREADINGS> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return stackIntercept<CustkeyRq, ArrCustREADINGS>("unary", this._transport, method, opt, input);
    }
}
