// @generated by protobuf-ts 2.9.4 with parameter use_proto_field_name,add_pb_suffix,force_optimize_code_size,ts_nocheck,long_type_string
// @generated from protobuf file "statments.proto" (package "micromas", syntax proto3)
// tslint:disable
// @ts-nocheck
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { StatementsService } from "./statments_pb";
import type { HistoryReply } from "./statments_pb";
import type { HistoryRequest } from "./statments_pb";
import type { PullStatmentsReply } from "./statments_pb";
import type { PullStatmentsReq } from "./statments_pb";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { VersionResponse } from "./common_pb";
import type { Empty } from "./common_pb";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * The greeting service definition.
 *
 * @generated from protobuf service micromas.StatementsService
 */
export interface IStatementsServiceClient {
    /**
     * @generated from protobuf rpc: Version(micromas.Empty) returns (micromas.VersionResponse);
     */
    version(input: Empty, options?: RpcOptions): UnaryCall<Empty, VersionResponse>;
    /**
     * @generated from protobuf rpc: PullStatmentsFromBilling(micromas.PullStatmentsReq) returns (micromas.PullStatmentsReply);
     */
    pullStatmentsFromBilling(input: PullStatmentsReq, options?: RpcOptions): UnaryCall<PullStatmentsReq, PullStatmentsReply>;
    /**
     * @generated from protobuf rpc: GetHistory(micromas.HistoryRequest) returns (micromas.HistoryReply);
     */
    getHistory(input: HistoryRequest, options?: RpcOptions): UnaryCall<HistoryRequest, HistoryReply>;
}
/**
 * The greeting service definition.
 *
 * @generated from protobuf service micromas.StatementsService
 */
export class StatementsServiceClient implements IStatementsServiceClient, ServiceInfo {
    typeName = StatementsService.typeName;
    methods = StatementsService.methods;
    options = StatementsService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Version(micromas.Empty) returns (micromas.VersionResponse);
     */
    version(input: Empty, options?: RpcOptions): UnaryCall<Empty, VersionResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, VersionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: PullStatmentsFromBilling(micromas.PullStatmentsReq) returns (micromas.PullStatmentsReply);
     */
    pullStatmentsFromBilling(input: PullStatmentsReq, options?: RpcOptions): UnaryCall<PullStatmentsReq, PullStatmentsReply> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<PullStatmentsReq, PullStatmentsReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetHistory(micromas.HistoryRequest) returns (micromas.HistoryReply);
     */
    getHistory(input: HistoryRequest, options?: RpcOptions): UnaryCall<HistoryRequest, HistoryReply> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<HistoryRequest, HistoryReply>("unary", this._transport, method, opt, input);
    }
}
