// @generated by protobuf-ts 2.9.4 with parameter use_proto_field_name,add_pb_suffix,force_optimize_code_size,ts_nocheck,long_type_string
// @generated from protobuf file "statments.proto" (package "micromas", syntax proto3)
// tslint:disable
// @ts-nocheck
import { VersionResponse } from "./common_pb";
import { Empty } from "./common_pb";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
import { MasDateTime } from "./date_pb";
import { MasDate } from "./date_pb";
/**
 * @generated from protobuf message micromas.TableProcess
 */
export interface TableProcess {
    /**
     * @generated from protobuf field: string TableName = 1 [json_name = "TableName"];
     */
    TableName: string;
    /**
     * @generated from protobuf field: int64 Inserted = 2 [json_name = "Inserted"];
     */
    Inserted: string;
    /**
     * @generated from protobuf field: string Deleted = 3 [json_name = "Deleted"];
     */
    Deleted: string;
    /**
     * @generated from protobuf field: string Updated = 4 [json_name = "Updated"];
     */
    Updated: string;
}
/**
 * @generated from protobuf message micromas.HistoryRequest
 */
export interface HistoryRequest {
    /**
     * @generated from protobuf field: int32 StationNo = 1 [json_name = "StationNo"];
     */
    StationNo: number;
    /**
     * @generated from protobuf field: optional string Custkey = 2 [json_name = "Custkey"];
     */
    Custkey?: string;
    /**
     * @generated from protobuf field: optional int32 UserId = 3 [json_name = "UserId"];
     */
    UserId?: number;
    /**
     * @generated from protobuf field: optional central.types.MasDate StartDate = 4 [json_name = "StartDate"];
     */
    StartDate?: MasDate;
    /**
     * @generated from protobuf field: optional central.types.MasDate EndDate = 5 [json_name = "EndDate"];
     */
    EndDate?: MasDate;
    /**
     * @generated from protobuf field: int32 PageSize = 6 [json_name = "PageSize"];
     */
    PageSize: number;
    /**
     * @generated from protobuf field: int32 PageIndex = 7 [json_name = "PageIndex"];
     */
    PageIndex: number;
}
/**
 * @generated from protobuf message micromas.HistoryReply
 */
export interface HistoryReply {
    /**
     * @generated from protobuf field: repeated micromas.PullStatmentsReply PullStatments = 1 [json_name = "PullStatments"];
     */
    PullStatments: PullStatmentsReply[];
    /**
     * @generated from protobuf field: int64 TOTAL_COUNT = 2 [json_name = "TOTALCOUNT"];
     */
    TOTAL_COUNT: string;
}
/**
 * @generated from protobuf message micromas.PullStatmentsReq
 */
export interface PullStatmentsReq {
    /**
     * @generated from protobuf field: optional int32 StationNo = 1 [json_name = "StationNo"];
     */
    StationNo?: number;
    /**
     * @generated from protobuf field: string Billgroup = 2 [json_name = "Billgroup"];
     */
    Billgroup: string;
    /**
     * @generated from protobuf field: string BookNo = 3 [json_name = "BookNo"];
     */
    BookNo: string;
    /**
     * @generated from protobuf field: string WalkNo = 4 [json_name = "WalkNo"];
     */
    WalkNo: string;
    /**
     * @generated from protobuf field: optional central.types.MasDate StartDate = 5 [json_name = "StartDate"];
     */
    StartDate?: MasDate;
    /**
     * @generated from protobuf field: optional central.types.MasDate EndDate = 6 [json_name = "EndDate"];
     */
    EndDate?: MasDate;
    /**
     * @generated from protobuf field: optional string UserId = 7 [json_name = "UserId"];
     */
    UserId?: string;
    /**
     * @generated from protobuf field: optional string Custkey = 8 [json_name = "Custkey"];
     */
    Custkey?: string;
    /**
     * @generated from protobuf field: optional micromas.PullRequestMode Mode = 9 [json_name = "Mode"];
     */
    Mode?: PullRequestMode;
    /**
     * @generated from protobuf field: optional bool WithCollectedBill = 10 [json_name = "WithCollectedBill"];
     */
    WithCollectedBill?: boolean;
}
/**
 * The response message containing the greetings
 *
 * @generated from protobuf message micromas.PullStatmentsReply
 */
export interface PullStatmentsReply {
    /**
     * @generated from protobuf field: bool HasError = 1 [json_name = "HasError"];
     */
    HasError: boolean;
    /**
     * @generated from protobuf field: string Message = 2 [json_name = "Message"];
     */
    Message: string;
    /**
     * @generated from protobuf field: optional central.types.MasDateTime ProcessStartTime = 4 [json_name = "ProcessStartTime"];
     */
    ProcessStartTime?: MasDateTime;
    /**
     * @generated from protobuf field: optional central.types.MasDateTime ProcessEndTime = 5 [json_name = "ProcessEndTime"];
     */
    ProcessEndTime?: MasDateTime;
    /**
     * @generated from protobuf field: optional micromas.PullStatmentsReq Request = 6 [json_name = "Request"];
     */
    Request?: PullStatmentsReq;
    /**
     * @generated from protobuf field: repeated micromas.ProcessWalk SusccsedWalks = 7 [json_name = "SusccsedWalks"];
     */
    SusccsedWalks: ProcessWalk[];
    /**
     * @generated from protobuf field: repeated micromas.ProcessWalk FailedWalks = 8 [json_name = "FailedWalks"];
     */
    FailedWalks: ProcessWalk[];
    /**
     * @generated from protobuf field: repeated micromas.TableProcess TableProceses = 9 [json_name = "TableProceses"];
     */
    TableProceses: TableProcess[];
    /**
     * @generated from protobuf field: string Billgroup = 10 [json_name = "Billgroup"];
     */
    Billgroup: string;
    /**
     * @generated from protobuf field: bool IS_Walk = 11 [json_name = "ISWalk"];
     */
    IS_Walk: boolean;
}
/**
 * @generated from protobuf message micromas.ProcessWalk
 */
export interface ProcessWalk {
    /**
     * @generated from protobuf field: string Billgroup = 1 [json_name = "Billgroup"];
     */
    Billgroup: string;
    /**
     * @generated from protobuf field: string BookNo = 2 [json_name = "BookNo"];
     */
    BookNo: string;
    /**
     * @generated from protobuf field: string WalkNo = 3 [json_name = "WalkNo"];
     */
    WalkNo: string;
    /**
     * @generated from protobuf field: string Message = 4 [json_name = "Message"];
     */
    Message: string;
    /**
     * @generated from protobuf field: int32 SucssededBills = 5 [json_name = "SucssededBills"];
     */
    SucssededBills: number;
    /**
     * @generated from protobuf field: bool IsSucsseded = 6 [json_name = "IsSucsseded"];
     */
    IsSucsseded: boolean;
}
/**
 * @generated from protobuf enum micromas.PullRequestMode
 */
export enum PullRequestMode {
    /**
     * @generated from protobuf enum value: PullRequestModeNew = 0;
     */
    PullRequestModeNew = 0,
    /**
     * @generated from protobuf enum value: PullRequestModeUpdate = 1;
     */
    PullRequestModeUpdate = 1
}
// @generated message type with reflection information, may provide speed optimized methods
class TableProcess$Type extends MessageType<TableProcess> {
    constructor() {
        super("micromas.TableProcess", [
            { no: 1, name: "TableName", kind: "scalar", localName: "TableName", jsonName: "TableName", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "Inserted", kind: "scalar", localName: "Inserted", jsonName: "Inserted", T: 3 /*ScalarType.INT64*/ },
            { no: 3, name: "Deleted", kind: "scalar", localName: "Deleted", jsonName: "Deleted", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "Updated", kind: "scalar", localName: "Updated", jsonName: "Updated", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message micromas.TableProcess
 */
export const TableProcess = new TableProcess$Type();
// @generated message type with reflection information, may provide speed optimized methods
class HistoryRequest$Type extends MessageType<HistoryRequest> {
    constructor() {
        super("micromas.HistoryRequest", [
            { no: 1, name: "StationNo", kind: "scalar", localName: "StationNo", jsonName: "StationNo", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "Custkey", kind: "scalar", localName: "Custkey", jsonName: "Custkey", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "UserId", kind: "scalar", localName: "UserId", jsonName: "UserId", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "StartDate", kind: "message", localName: "StartDate", jsonName: "StartDate", T: () => MasDate },
            { no: 5, name: "EndDate", kind: "message", localName: "EndDate", jsonName: "EndDate", T: () => MasDate },
            { no: 6, name: "PageSize", kind: "scalar", localName: "PageSize", jsonName: "PageSize", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "PageIndex", kind: "scalar", localName: "PageIndex", jsonName: "PageIndex", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message micromas.HistoryRequest
 */
export const HistoryRequest = new HistoryRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class HistoryReply$Type extends MessageType<HistoryReply> {
    constructor() {
        super("micromas.HistoryReply", [
            { no: 1, name: "PullStatments", kind: "message", localName: "PullStatments", jsonName: "PullStatments", repeat: 1 /*RepeatType.PACKED*/, T: () => PullStatmentsReply },
            { no: 2, name: "TOTAL_COUNT", kind: "scalar", localName: "TOTAL_COUNT", jsonName: "TOTALCOUNT", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message micromas.HistoryReply
 */
export const HistoryReply = new HistoryReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PullStatmentsReq$Type extends MessageType<PullStatmentsReq> {
    constructor() {
        super("micromas.PullStatmentsReq", [
            { no: 1, name: "StationNo", kind: "scalar", localName: "StationNo", jsonName: "StationNo", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "Billgroup", kind: "scalar", localName: "Billgroup", jsonName: "Billgroup", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "BookNo", kind: "scalar", localName: "BookNo", jsonName: "BookNo", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "WalkNo", kind: "scalar", localName: "WalkNo", jsonName: "WalkNo", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "StartDate", kind: "message", localName: "StartDate", jsonName: "StartDate", T: () => MasDate },
            { no: 6, name: "EndDate", kind: "message", localName: "EndDate", jsonName: "EndDate", T: () => MasDate },
            { no: 7, name: "UserId", kind: "scalar", localName: "UserId", jsonName: "UserId", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "Custkey", kind: "scalar", localName: "Custkey", jsonName: "Custkey", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "Mode", kind: "enum", localName: "Mode", jsonName: "Mode", opt: true, T: () => ["micromas.PullRequestMode", PullRequestMode] },
            { no: 10, name: "WithCollectedBill", kind: "scalar", localName: "WithCollectedBill", jsonName: "WithCollectedBill", opt: true, T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message micromas.PullStatmentsReq
 */
export const PullStatmentsReq = new PullStatmentsReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PullStatmentsReply$Type extends MessageType<PullStatmentsReply> {
    constructor() {
        super("micromas.PullStatmentsReply", [
            { no: 1, name: "HasError", kind: "scalar", localName: "HasError", jsonName: "HasError", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "Message", kind: "scalar", localName: "Message", jsonName: "Message", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "ProcessStartTime", kind: "message", localName: "ProcessStartTime", jsonName: "ProcessStartTime", T: () => MasDateTime },
            { no: 5, name: "ProcessEndTime", kind: "message", localName: "ProcessEndTime", jsonName: "ProcessEndTime", T: () => MasDateTime },
            { no: 6, name: "Request", kind: "message", localName: "Request", jsonName: "Request", T: () => PullStatmentsReq },
            { no: 7, name: "SusccsedWalks", kind: "message", localName: "SusccsedWalks", jsonName: "SusccsedWalks", repeat: 1 /*RepeatType.PACKED*/, T: () => ProcessWalk },
            { no: 8, name: "FailedWalks", kind: "message", localName: "FailedWalks", jsonName: "FailedWalks", repeat: 1 /*RepeatType.PACKED*/, T: () => ProcessWalk },
            { no: 9, name: "TableProceses", kind: "message", localName: "TableProceses", jsonName: "TableProceses", repeat: 1 /*RepeatType.PACKED*/, T: () => TableProcess },
            { no: 10, name: "Billgroup", kind: "scalar", localName: "Billgroup", jsonName: "Billgroup", T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "IS_Walk", kind: "scalar", localName: "IS_Walk", jsonName: "ISWalk", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message micromas.PullStatmentsReply
 */
export const PullStatmentsReply = new PullStatmentsReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ProcessWalk$Type extends MessageType<ProcessWalk> {
    constructor() {
        super("micromas.ProcessWalk", [
            { no: 1, name: "Billgroup", kind: "scalar", localName: "Billgroup", jsonName: "Billgroup", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "BookNo", kind: "scalar", localName: "BookNo", jsonName: "BookNo", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "WalkNo", kind: "scalar", localName: "WalkNo", jsonName: "WalkNo", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "Message", kind: "scalar", localName: "Message", jsonName: "Message", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "SucssededBills", kind: "scalar", localName: "SucssededBills", jsonName: "SucssededBills", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "IsSucsseded", kind: "scalar", localName: "IsSucsseded", jsonName: "IsSucsseded", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message micromas.ProcessWalk
 */
export const ProcessWalk = new ProcessWalk$Type();
/**
 * @generated ServiceType for protobuf service micromas.StatementsService
 */
export const StatementsService = new ServiceType("micromas.StatementsService", [
    { name: "Version", options: {}, I: Empty, O: VersionResponse },
    { name: "PullStatmentsFromBilling", options: {}, I: PullStatmentsReq, O: PullStatmentsReply },
    { name: "GetHistory", options: {}, I: HistoryRequest, O: HistoryReply }
]);
