import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import "./index.css";
import App from "./App.tsx";
import { BrowserRouter } from "react-router-dom";
import "devextreme/dist/css/dx.light.compact.css";

// shim for CommonJS modules generated by protobuf
// eslint-disable-next-line @typescript-eslint/no-explicit-any
(window as any).exports = {};
// eslint-disable-next-line @typescript-eslint/no-explicit-any
(window as any).module = { exports: (window as any).exports };
createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </StrictMode>,
);
