// source: services/collection.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var messages_collectionmessages_pb = require('../messages/collectionmessages_pb.js');
goog.object.extend(proto, messages_collectionmessages_pb);
var serverhostmessages_collectionmessages_pb = require('../serverhostmessages/collectionmessages_pb.js');
goog.object.extend(proto, serverhostmessages_collectionmessages_pb);
goog.exportSymbol('proto.services.CalcChargeRequest', null, global);
goog.exportSymbol('proto.services.CalcChargeResponse', null, global);
goog.exportSymbol('proto.services.GetCashierBalanceRequest', null, global);
goog.exportSymbol('proto.services.GetPaymentForHqRequest', null, global);
goog.exportSymbol('proto.services.HqCollectBillRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.services.GetCashierBalanceRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.services.GetCashierBalanceRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.services.GetCashierBalanceRequest.displayName = 'proto.services.GetCashierBalanceRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.services.GetPaymentForHqRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.services.GetPaymentForHqRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.services.GetPaymentForHqRequest.displayName = 'proto.services.GetPaymentForHqRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.services.CalcChargeRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.services.CalcChargeRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.services.CalcChargeRequest.displayName = 'proto.services.CalcChargeRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.services.CalcChargeResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.services.CalcChargeResponse.repeatedFields_, null);
};
goog.inherits(proto.services.CalcChargeResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.services.CalcChargeResponse.displayName = 'proto.services.CalcChargeResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.services.HqCollectBillRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.services.HqCollectBillRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.services.HqCollectBillRequest.displayName = 'proto.services.HqCollectBillRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.services.GetCashierBalanceRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.services.GetCashierBalanceRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.services.GetCashierBalanceRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.GetCashierBalanceRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    custkey: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.services.GetCashierBalanceRequest}
 */
proto.services.GetCashierBalanceRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.services.GetCashierBalanceRequest;
  return proto.services.GetCashierBalanceRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.services.GetCashierBalanceRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.services.GetCashierBalanceRequest}
 */
proto.services.GetCashierBalanceRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCustkey(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.services.GetCashierBalanceRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.services.GetCashierBalanceRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.services.GetCashierBalanceRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.GetCashierBalanceRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string custKey = 1;
 * @return {string}
 */
proto.services.GetCashierBalanceRequest.prototype.getCustkey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.services.GetCashierBalanceRequest} returns this
 */
proto.services.GetCashierBalanceRequest.prototype.setCustkey = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.GetCashierBalanceRequest} returns this
 */
proto.services.GetCashierBalanceRequest.prototype.clearCustkey = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.GetCashierBalanceRequest.prototype.hasCustkey = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.services.GetPaymentForHqRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.services.GetPaymentForHqRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.services.GetPaymentForHqRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.GetPaymentForHqRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    key: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    searchby: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    alldata: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    oldone: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    forquery: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    october: jspb.Message.getBooleanFieldWithDefault(msg, 6, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.services.GetPaymentForHqRequest}
 */
proto.services.GetPaymentForHqRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.services.GetPaymentForHqRequest;
  return proto.services.GetPaymentForHqRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.services.GetPaymentForHqRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.services.GetPaymentForHqRequest}
 */
proto.services.GetPaymentForHqRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    case 2:
      var value = /** @type {!proto.messages.SearchBy} */ (reader.readEnum());
      msg.setSearchby(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAlldata(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setOldone(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setForquery(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setOctober(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.services.GetPaymentForHqRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.services.GetPaymentForHqRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.services.GetPaymentForHqRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.GetPaymentForHqRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {!proto.messages.SearchBy} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeBool(
      3,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeBool(
      4,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeBool(
      5,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeBool(
      6,
      f
    );
  }
};


/**
 * required string Key = 1;
 * @return {string}
 */
proto.services.GetPaymentForHqRequest.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.services.GetPaymentForHqRequest} returns this
 */
proto.services.GetPaymentForHqRequest.prototype.setKey = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.GetPaymentForHqRequest} returns this
 */
proto.services.GetPaymentForHqRequest.prototype.clearKey = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.GetPaymentForHqRequest.prototype.hasKey = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional messages.SearchBy searchBy = 2;
 * @return {!proto.messages.SearchBy}
 */
proto.services.GetPaymentForHqRequest.prototype.getSearchby = function() {
  return /** @type {!proto.messages.SearchBy} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.messages.SearchBy} value
 * @return {!proto.services.GetPaymentForHqRequest} returns this
 */
proto.services.GetPaymentForHqRequest.prototype.setSearchby = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.GetPaymentForHqRequest} returns this
 */
proto.services.GetPaymentForHqRequest.prototype.clearSearchby = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.GetPaymentForHqRequest.prototype.hasSearchby = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bool allData = 3;
 * @return {boolean}
 */
proto.services.GetPaymentForHqRequest.prototype.getAlldata = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.services.GetPaymentForHqRequest} returns this
 */
proto.services.GetPaymentForHqRequest.prototype.setAlldata = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.GetPaymentForHqRequest} returns this
 */
proto.services.GetPaymentForHqRequest.prototype.clearAlldata = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.GetPaymentForHqRequest.prototype.hasAlldata = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional bool oldOne = 4;
 * @return {boolean}
 */
proto.services.GetPaymentForHqRequest.prototype.getOldone = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.services.GetPaymentForHqRequest} returns this
 */
proto.services.GetPaymentForHqRequest.prototype.setOldone = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.GetPaymentForHqRequest} returns this
 */
proto.services.GetPaymentForHqRequest.prototype.clearOldone = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.GetPaymentForHqRequest.prototype.hasOldone = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional bool forQuery = 5;
 * @return {boolean}
 */
proto.services.GetPaymentForHqRequest.prototype.getForquery = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.services.GetPaymentForHqRequest} returns this
 */
proto.services.GetPaymentForHqRequest.prototype.setForquery = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.GetPaymentForHqRequest} returns this
 */
proto.services.GetPaymentForHqRequest.prototype.clearForquery = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.GetPaymentForHqRequest.prototype.hasForquery = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional bool october = 6;
 * @return {boolean}
 */
proto.services.GetPaymentForHqRequest.prototype.getOctober = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.services.GetPaymentForHqRequest} returns this
 */
proto.services.GetPaymentForHqRequest.prototype.setOctober = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.GetPaymentForHqRequest} returns this
 */
proto.services.GetPaymentForHqRequest.prototype.clearOctober = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.GetPaymentForHqRequest.prototype.hasOctober = function() {
  return jspb.Message.getField(this, 6) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.services.CalcChargeRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.services.CalcChargeRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.services.CalcChargeRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.CalcChargeRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    amount: (f = jspb.Message.getOptionalFloatingPointField(msg, 1)) == null ? undefined : f,
    paymentmethod: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.services.CalcChargeRequest}
 */
proto.services.CalcChargeRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.services.CalcChargeRequest;
  return proto.services.CalcChargeRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.services.CalcChargeRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.services.CalcChargeRequest}
 */
proto.services.CalcChargeRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setAmount(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPaymentmethod(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.services.CalcChargeRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.services.CalcChargeRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.services.CalcChargeRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.CalcChargeRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional double amount = 1;
 * @return {number}
 */
proto.services.CalcChargeRequest.prototype.getAmount = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.services.CalcChargeRequest} returns this
 */
proto.services.CalcChargeRequest.prototype.setAmount = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.CalcChargeRequest} returns this
 */
proto.services.CalcChargeRequest.prototype.clearAmount = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.CalcChargeRequest.prototype.hasAmount = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 paymentMethod = 2;
 * @return {number}
 */
proto.services.CalcChargeRequest.prototype.getPaymentmethod = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.CalcChargeRequest} returns this
 */
proto.services.CalcChargeRequest.prototype.setPaymentmethod = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.CalcChargeRequest} returns this
 */
proto.services.CalcChargeRequest.prototype.clearPaymentmethod = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.CalcChargeRequest.prototype.hasPaymentmethod = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.services.CalcChargeResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.services.CalcChargeResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.services.CalcChargeResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.services.CalcChargeResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.CalcChargeResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    amountsList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.services.CalcChargeResponse}
 */
proto.services.CalcChargeResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.services.CalcChargeResponse;
  return proto.services.CalcChargeResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.services.CalcChargeResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.services.CalcChargeResponse}
 */
proto.services.CalcChargeResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.addAmounts(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.services.CalcChargeResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.services.CalcChargeResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.services.CalcChargeResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.CalcChargeResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAmountsList();
  if (f.length > 0) {
    writer.writeRepeatedDouble(
      1,
      f
    );
  }
};


/**
 * repeated double amounts = 1;
 * @return {!Array<number>}
 */
proto.services.CalcChargeResponse.prototype.getAmountsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 1));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.services.CalcChargeResponse} returns this
 */
proto.services.CalcChargeResponse.prototype.setAmountsList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.services.CalcChargeResponse} returns this
 */
proto.services.CalcChargeResponse.prototype.addAmounts = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.services.CalcChargeResponse} returns this
 */
proto.services.CalcChargeResponse.prototype.clearAmountsList = function() {
  return this.setAmountsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.services.HqCollectBillRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.services.HqCollectBillRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.services.HqCollectBillRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.HqCollectBillRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    paymentNo: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    custkey: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    locked: (f = jspb.Message.getBooleanField(msg, 3)) == null ? undefined : f,
    chequeno: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f,
    chequebank: (f = jspb.Message.getField(msg, 5)) == null ? undefined : f,
    discount: (f = jspb.Message.getOptionalFloatingPointField(msg, 6)) == null ? undefined : f,
    discountdocumentno: (f = jspb.Message.getField(msg, 7)) == null ? undefined : f,
    comment: (f = jspb.Message.getField(msg, 8)) == null ? undefined : f,
    paymentmethod: (f = jspb.Message.getField(msg, 9)) == null ? undefined : f,
    totalamountpayment: (f = jspb.Message.getOptionalFloatingPointField(msg, 10)) == null ? undefined : f,
    charge1: (f = jspb.Message.getOptionalFloatingPointField(msg, 11)) == null ? undefined : f,
    charge2: (f = jspb.Message.getOptionalFloatingPointField(msg, 12)) == null ? undefined : f,
    charge3: (f = jspb.Message.getOptionalFloatingPointField(msg, 13)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.services.HqCollectBillRequest}
 */
proto.services.HqCollectBillRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.services.HqCollectBillRequest;
  return proto.services.HqCollectBillRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.services.HqCollectBillRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.services.HqCollectBillRequest}
 */
proto.services.HqCollectBillRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPaymentNo(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCustkey(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setLocked(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setChequeno(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setChequebank(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setDiscount(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setDiscountdocumentno(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setComment(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPaymentmethod(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTotalamountpayment(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setCharge1(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setCharge2(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setCharge3(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.services.HqCollectBillRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.services.HqCollectBillRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.services.HqCollectBillRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.HqCollectBillRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeBool(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeString(
      5,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeDouble(
      6,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeString(
      7,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeString(
      8,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 9));
  if (f != null) {
    writer.writeInt32(
      9,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 10));
  if (f != null) {
    writer.writeDouble(
      10,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 11));
  if (f != null) {
    writer.writeDouble(
      11,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 12));
  if (f != null) {
    writer.writeDouble(
      12,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 13));
  if (f != null) {
    writer.writeDouble(
      13,
      f
    );
  }
};


/**
 * optional string payment_no = 1;
 * @return {string}
 */
proto.services.HqCollectBillRequest.prototype.getPaymentNo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.services.HqCollectBillRequest} returns this
 */
proto.services.HqCollectBillRequest.prototype.setPaymentNo = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.HqCollectBillRequest} returns this
 */
proto.services.HqCollectBillRequest.prototype.clearPaymentNo = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.HqCollectBillRequest.prototype.hasPaymentNo = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string custkey = 2;
 * @return {string}
 */
proto.services.HqCollectBillRequest.prototype.getCustkey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.services.HqCollectBillRequest} returns this
 */
proto.services.HqCollectBillRequest.prototype.setCustkey = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.HqCollectBillRequest} returns this
 */
proto.services.HqCollectBillRequest.prototype.clearCustkey = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.HqCollectBillRequest.prototype.hasCustkey = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bool locked = 3;
 * @return {boolean}
 */
proto.services.HqCollectBillRequest.prototype.getLocked = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.services.HqCollectBillRequest} returns this
 */
proto.services.HqCollectBillRequest.prototype.setLocked = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.HqCollectBillRequest} returns this
 */
proto.services.HqCollectBillRequest.prototype.clearLocked = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.HqCollectBillRequest.prototype.hasLocked = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string chequeNo = 4;
 * @return {string}
 */
proto.services.HqCollectBillRequest.prototype.getChequeno = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.services.HqCollectBillRequest} returns this
 */
proto.services.HqCollectBillRequest.prototype.setChequeno = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.HqCollectBillRequest} returns this
 */
proto.services.HqCollectBillRequest.prototype.clearChequeno = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.HqCollectBillRequest.prototype.hasChequeno = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string chequeBank = 5;
 * @return {string}
 */
proto.services.HqCollectBillRequest.prototype.getChequebank = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.services.HqCollectBillRequest} returns this
 */
proto.services.HqCollectBillRequest.prototype.setChequebank = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.HqCollectBillRequest} returns this
 */
proto.services.HqCollectBillRequest.prototype.clearChequebank = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.HqCollectBillRequest.prototype.hasChequebank = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional double discount = 6;
 * @return {number}
 */
proto.services.HqCollectBillRequest.prototype.getDiscount = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.services.HqCollectBillRequest} returns this
 */
proto.services.HqCollectBillRequest.prototype.setDiscount = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.HqCollectBillRequest} returns this
 */
proto.services.HqCollectBillRequest.prototype.clearDiscount = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.HqCollectBillRequest.prototype.hasDiscount = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional string discountDocumentNo = 7;
 * @return {string}
 */
proto.services.HqCollectBillRequest.prototype.getDiscountdocumentno = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.services.HqCollectBillRequest} returns this
 */
proto.services.HqCollectBillRequest.prototype.setDiscountdocumentno = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.HqCollectBillRequest} returns this
 */
proto.services.HqCollectBillRequest.prototype.clearDiscountdocumentno = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.HqCollectBillRequest.prototype.hasDiscountdocumentno = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional string comment = 8;
 * @return {string}
 */
proto.services.HqCollectBillRequest.prototype.getComment = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.services.HqCollectBillRequest} returns this
 */
proto.services.HqCollectBillRequest.prototype.setComment = function(value) {
  return jspb.Message.setField(this, 8, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.HqCollectBillRequest} returns this
 */
proto.services.HqCollectBillRequest.prototype.clearComment = function() {
  return jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.HqCollectBillRequest.prototype.hasComment = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional int32 paymentMethod = 9;
 * @return {number}
 */
proto.services.HqCollectBillRequest.prototype.getPaymentmethod = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.HqCollectBillRequest} returns this
 */
proto.services.HqCollectBillRequest.prototype.setPaymentmethod = function(value) {
  return jspb.Message.setField(this, 9, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.HqCollectBillRequest} returns this
 */
proto.services.HqCollectBillRequest.prototype.clearPaymentmethod = function() {
  return jspb.Message.setField(this, 9, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.HqCollectBillRequest.prototype.hasPaymentmethod = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional double totalAmountPayment = 10;
 * @return {number}
 */
proto.services.HqCollectBillRequest.prototype.getTotalamountpayment = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 10, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.services.HqCollectBillRequest} returns this
 */
proto.services.HqCollectBillRequest.prototype.setTotalamountpayment = function(value) {
  return jspb.Message.setField(this, 10, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.HqCollectBillRequest} returns this
 */
proto.services.HqCollectBillRequest.prototype.clearTotalamountpayment = function() {
  return jspb.Message.setField(this, 10, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.HqCollectBillRequest.prototype.hasTotalamountpayment = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional double charge1 = 11;
 * @return {number}
 */
proto.services.HqCollectBillRequest.prototype.getCharge1 = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 11, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.services.HqCollectBillRequest} returns this
 */
proto.services.HqCollectBillRequest.prototype.setCharge1 = function(value) {
  return jspb.Message.setField(this, 11, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.HqCollectBillRequest} returns this
 */
proto.services.HqCollectBillRequest.prototype.clearCharge1 = function() {
  return jspb.Message.setField(this, 11, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.HqCollectBillRequest.prototype.hasCharge1 = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional double charge2 = 12;
 * @return {number}
 */
proto.services.HqCollectBillRequest.prototype.getCharge2 = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 12, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.services.HqCollectBillRequest} returns this
 */
proto.services.HqCollectBillRequest.prototype.setCharge2 = function(value) {
  return jspb.Message.setField(this, 12, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.HqCollectBillRequest} returns this
 */
proto.services.HqCollectBillRequest.prototype.clearCharge2 = function() {
  return jspb.Message.setField(this, 12, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.HqCollectBillRequest.prototype.hasCharge2 = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional double charge3 = 13;
 * @return {number}
 */
proto.services.HqCollectBillRequest.prototype.getCharge3 = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 13, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.services.HqCollectBillRequest} returns this
 */
proto.services.HqCollectBillRequest.prototype.setCharge3 = function(value) {
  return jspb.Message.setField(this, 13, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.HqCollectBillRequest} returns this
 */
proto.services.HqCollectBillRequest.prototype.clearCharge3 = function() {
  return jspb.Message.setField(this, 13, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.HqCollectBillRequest.prototype.hasCharge3 = function() {
  return jspb.Message.getField(this, 13) != null;
};


goog.object.extend(exports, proto.services);
